KhronosGroup/SYCL-CTS

cmake/AddSYCLExecutable.cmake
cmake/FindhipSYCL.cmake

This extends the cmake infrastructure to allow for compilation with hipSYCL. Other implementations are not affected. Also note that compilation at the moment still fails (mostly due to OpenCL stuff) and is still work in progress.
Signed-off-by: Aksel Alpay <aksel.alpay@uni-heidelberg.de>

Add initial support for hipSYCL

---

tests/accessor/accessor_api_image.cpp
tests/accessor/accessor_api_image_common.h
tests/accessor/accessor_constructors_image.cpp

Images is optional feature, so conformance tests must skip the test
if feature is not supported.
Add image support check to accessor_constructors_image test.

Make image accessor feature checks conditional

---

tests/group/group_api.cpp

Group API test builds test kernels at run time using
build_with_kernel_type method of cl::sycl::program class.
Skip these test cases if online compilation is not supported.
Signed-off-by: Alexey Bader <alexey.bader@intel.com>
(cherry picked from commit be801b896f64684c5f5c4b04cc5fd16c233009ba)

Do not rely on availability of compiler/linker

---

tests/opencl_interop/opencl_interop_constructors.cpp
tests/opencl_interop/opencl_interop_get.cpp
tests/opencl_interop/opencl_interop_kernel.cpp
util/test_base_opencl.cpp
util/test_base_opencl.h

The changes to this test are all related to optional features: online
compilation, image, sampler.
- Test cases using unsupported optional features are skipped.
- Code using sampler::get() has been removed as it's not defined by the
specification.
- Remove test case checking handler::set_arg method with stream
parameter.

OpenCL interoperability test fixes

---

tests/accessor/accessor_api_common_buffer_local.h

According to the comments, test is supposed to do two checks in the following order: write using `id`, check the results, write using `size_t`, check the results.
Current order is write using `id`, write using `size_t`, check the results, check the results.

Re-order unaligned writes and checks.

---

tests/opencl_interop/opencl_interop_constructors.cpp

Appears to be a copy/paste error from the earlier buffer test, when moving to multi-channel image testing.

Make backing buffer large enough to avoid buffer overrun

---

tests/buffer/buffer_api.cpp
tests/buffer/buffer_constructors.cpp

According to the SYCL specification clarifications from
https://github.com/KhronosGroup/SYCL-Docs/pull/39, while constructing
sub buffer the offset and range specified by baseIndex and subRange
which passed to `buffer(buffer)` constructor together must represent a
contiguous region of the original SYCL buffer. Besides, the sum of
`baseIndex` and `subRange` in any dimension must not exceed the parent
buffer (`b`) size (`bufferRange`) in that dimension.
This patch changes an offset for sub buffer so it forms a contiguous region,
and calculates sub buffer range based on given offset and parent buffer range.
Patch by Ivan Karachun.
Signed-off-by: Alexey Bader <alexey.bader@intel.com>

Changed sub buffer construction parameters

---

cmake/FindIntel_SYCL.cmake
tests/common/cts_selector.h

This patch allows new options for Intel SYCL to be passed to the SYCL CTS.
A minor fix is included that will resolve #13. The correct vendor information is now used within the device selector.

Allow additional flags to be passed to Intel SYCL

---

tests/opencl_interop/opencl_interop_constructors.cpp
tests/opencl_interop/opencl_interop_get.cpp
tests/opencl_interop/opencl_interop_kernel.cpp
util/test_base_opencl.cpp
util/test_base_opencl.h

Test devices that do not support online compile using binaries in same
directory as executable

Enable opencl_interop on implementations w/o online compilation support

---

tests/group/group_async_work_group_copy.cpp
tests/nd_item/nd_item_async_work_group_copy.cpp

async_work_group_copy test cases using strides copy the same number of elements as buffer holds, but buffer allocations do not take "strides" into consideration, which leads to out-of-bounds accesses.

Fix out of bounds access in async_work_group_copy tests

---

tests/h_item/h_item_api.cpp

Class template `h_item_api_kernel_single` has two template parameters
number of dimensions and the current dimension index. Setting the
current index equal to the number of dimensions is undefined behavior.
Current index must be less than number of dimensions.

Fix undefined behavior in h_item test

---

tests/buffer/buffer_constructors.cpp
tests/common/common.h
tests/common/common_vec.h
tests/image/image_api.cpp
tests/kernel/kernel_api.cpp
tests/kernel/kernel_constructors.cpp
tests/kernel/kernel_info.cpp
tests/opencl_interop/opencl_interop_constructors.cpp
tests/opencl_interop/opencl_interop_get.cpp
tests/opencl_interop/opencl_interop_kernel.cpp
tests/program/program_api.cpp
tests/program/program_constructors.cpp
tests/program/program_info.cpp

SYCL CTS has a separate test checking interoperability with OpenCL.
There are some cases when this functionality is tested in other tests.
There are also cases of unnecessary inheritance from interoperability
utility class. Patch fixes described problems.
Patch by Artur Gainullin <artur.gainullin@intel.com>

Move interoperability test cases to the opencl_interop test

---

tests/accessor/accessor_constructors_buffer_utility.h

Made these methods return the values of the accessor, not the buffer
from which this accessor was created.
Patch by Alexey Voronov <alexey.voronov@intel.com>.

Fix more checks for accessor's get_count()/get_size() methods

---

util/test_base_opencl.cpp

constexpr implies const in this case.

[NFC] Remove unnecessary const qualifier

---

run_conformance_tests.py
tools/stylesheet.xml

1. `--additional-ctest-args`
2. Replaces the `--verbose` option
3. Include CTest call in conformance report

Support additional CTest arguments

---

tests/nd_item/nd_item_mem_fence.cpp

Align requested work-group size with the implementation limitations.
- requested work-group size can't be greater than the maximum work-group
size supported by the device
- requested work-group size can't be greater than the maximum work-group
size supported by a kernel on specified device
Signed-off-by: Alexey Bader <alexey.bader@intel.com>

Adjust work-group size in nd_item mem_fence test

---

tests/accessor/accessor_api_image_common.h
tests/accessor/accessor_api_local_common.h

* https://github.com/KhronosGroup/SYCL-Docs/pull/31
* Removed `get_size` check for image accessors
* Check `get_range` for local accessors
* Check `get_range` for image accessors

Accessor `get_size` and `get_range` fixes

---

tests/handler/handler_copy.cpp

Add new tests covering cases when source and destination parameters of
"explicit copy API" have different types.

Enhance handler copy test cases

---

cmake/FindIntel_SYCL.cmake

- Use proper device triple
- Use device code split feature to improve JIT build time

Improve CTS build process with Intel compiler

---

tests/accessor/accessor_constructors_image_utility.h
tests/accessor/accessor_constructors_utility.h

Follow-up https://github.com/KhronosGroup/SYCL-CTS/pull/35, which
adjusts accessor API change from
https://github.com/KhronosGroup/SYCL-Docs/pull/31.

Update image accessors API

---

tests/hierarchical/hierarchical_implicit_reduce.cpp

Fixes #46 
* Removed early return
* Fixed segfault
* Use `localId` as index instead of `i` for local data
* Use 64-bit integers
* Simplified `Adder` and `Multiplier`
* Fixed default value for `Multiplier`
* Use `write` access mode for group sums in first pass
* Ensure `mTotal` is written to `parallel_for_work_group`
* Pass proper ranges to
* Better error messages
* clang-format

Re-enabled hierarchical_implicit_reduce

---

tests/hierarchical/hierarchical_functor.cpp

'this' with a capture default of '=' is not allowed for kernel
functions in SYCL 1.2.1. Fix hierarchical_functor test to capture by
reference in parallel_for_work_item.
Patch by Artur Gainullin <artur.gainullin@intel.com>

Implicit capture of 'this' by '=' is not allowed

---

CMakeLists.txt
tests/context/context_constructors.cpp
tests/device/device_api.cpp
tests/device/device_constructors.cpp
tests/event/event_api.cpp
tests/event/event_constructors.cpp
tests/kernel/kernel_constructors.cpp
tests/opencl_interop/CMakeLists.txt
tests/platform/platform_constructors.cpp
tests/program/program_api.cpp
tests/program/program_constructors.cpp
tests/queue/queue_api.cpp

Adds the `SYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS` CMake option (`ON` by default) which defines the `SYCL_CTS_TEST_OPENCL_INTEROP` macro. This is used to enable or disable OpenCL interoperability tests, such as uses of the `get` method on select SYCL objects.
This commit also fixes the `SYCL_CTS_ENABLE_DOUBLE_TESTS` and `SYCL_CTS_ENABLE_HALF_TESTS` options default values.

OpenCL interoperabilty tests option

---

tests/device/device_constructors.cpp
tests/platform/platform_constructors.cpp

The device/platform equality testing is overly strict.
It's performing negative testing that doesn't allow implementations to cache devices and platforms so that things can reasonably compare equal when users expect them to.
Signed-off-by: James Brodman <james.brodman@intel.com>

Remove overly strict test conditions.

---

cmake/FindIntel_SYCL.cmake

Intel's implementation is about to switch default SYCL version to
SYCL-2020 and it will be a breaking change for test_header, which checks
if `CL_SYCL_LANGUAGE_VERSION` macro is defined by the compiler.

Specify SYCL standard version for Intel implementation

---

tests/handler/handler_invoke_api.cpp

I've noticed on various occasions that for some SYCL implementations and platform combinations, the global kernel offset mechanism doesn't seem to work quite right, in that the ids received by the kernel function are not properly shifted one way or another. Since the offset API is very near and dear to my heart, I'd like to propose adding functionality to the CTS that explicitly tests for this.
To that end, I've adjusted the `handler_invoke_api` test suite to not only check whether a kernel is launched at all, but also whether it receives the correct indices corresponding to the requested iteration space. I guess it could be debated whether these checks belong to the `item`/`h_item`/`nd_item` tests instead, but I feel like they better fit with the launch API, as this is where the …

Test that handler invoke APIs pass correct indices to kernels

---

CMakeLists.txt
tests/CMakeLists.txt

Enable cmake options filtering out half/double tests at compile time:
- SYCL_CTS_ENABLE_HALF_TESTS
- SYCL_CTS_ENABLE_DOUBLE_TESTS
Default option values are switched to ON, because:
- neither SYCL_CTS_ENABLE_DOUBLE_TESTS nor SYCL_CTS_ENABLE_HALF_TESTS
affect any of the current tests in the CTS:
tests currently behave like if these options are ON by default
- half types should be available at the compile time according to the
SYCL 1.2.1, 5.1 and SYCL 2020, D.6.1
- in case there is no  fp16/fp64 extension available for device, a
feature_not_supported exception should be thrown at the runtime
- double types should be available at the compile time according to
the SYCL 1.2.1, 4.10.1 and 6.5
- according to the SYCL 2020, 6.5 an implementation may not raise an
error in case application did not …

Enable half/double cmake options

---

tests/math_builtin_api/modules/sycl_types.py
tests/math_builtin_api/modules/test_generator.py

Fixed ommiting tests for char and vec<char,N>
Remaining gap (test coverage): result correctness isn't checked

Extend type coverage for relational and integer functions

---

tests/image/image_api.cpp
tests/image/image_api_fp16.cpp
tests/image/image_common.h
tests/image/image_constructors.cpp

Added type coverage for get_access() for cl_int4, cl_uint4, cl_half4
Added type coverage for Image<N, AllocatorT> for AllocatorT - not default
Added type coverage for constructors for:
image_channel_order = (image_channel_order::a, r, rx, rg, rgx, ra, rgb, rgbx, argb, intensity, luminance, abgr)
image_channel_type = (image_channel_type::snorm_int8, snorm_int16, unorm_short_565, unorm_short_555, unorm_int_101010)
Changed test name image_api to image_api_core to allow it to be run separately from image_api_fp16.
Remaining gap (test coverage): other accessMode for get_access(),
constructor image(cl_mem , const context &, event )

Improve data type coverage for Image.

---

tests/stream/stream_api.cpp
tests/stream/stream_api_common.h
tests/stream/stream_api_fp16.cpp
tests/stream/stream_api_fp64.cpp

Changed test name stream_api to stream_api_core to allow it to be run separately from other stream_api tests.
Added type coverage for
- id<dim = 1,2>, range<dim = 1,2>, item<dim = 1,2>, nd_item<dim = 1,2>,
group<dim = 1,2>, nd_range<dim = 1,2>, h_item<dim = 1,2>
- stream_manipulator::flush
- vec<typename T, int numElements = (1, 2, 3, 4, 8 or 16)>
where T = (char, signed char, unsigned char, int, unsigned int, short,
unsigned short, long int, unsigned long int, long long int, unsigned
long long int, cl_char, cl_uchar, cl_int, cl_uint, cl_short,
cl_ushort, cl_long, cl_ulong, byte, float, double, half, cl_float,
cl_double, cl_half)
Added const correctness check
Remaining gap (test coverage): get_size() result correctness,
get_work_item_buffer_size()
exceeding totalBufferSize and …

Improved data type coverage for stream

---

cmake/FindIntel_SYCL.cmake

`fp-model` default value might enable optimizations that are not
value-safe on floating-point data.

[CMake] Set explicit value of fp-model option for Intel compiler

---

tests/group/group_async_work_group_copy.cpp
tests/group/group_async_work_group_copy_common.h
tests/group/group_async_work_group_copy_fp16.cpp
tests/group/group_async_work_group_copy_fp64.cpp
tests/nd_item/nd_item_async_work_group_copy.cpp
tests/nd_item/nd_item_async_work_group_copy_common.h
tests/nd_item/nd_item_async_work_group_copy_fp16.cpp
tests/nd_item/nd_item_async_work_group_copy_fp64.cpp

Changed test names *work_group_copy to *work_group_copy_core to allow it to be run separately from other *work_group_copy tests.
Added type coverage for
- nd_item::async_work_group_copy member functions
- group::async_work_group_copy member functions

Extending Type coverage for nd_item and group classes

---

CMakeLists.txt
tests/accessor/accessor_api_image_common.h

The DPCPP CUDA backend currently only support reading from and writing to image accessors with data type corresponding to the channel data type of the underlying image.
This changes the channel types of images used in the accessor tests to correspond to the supported accessor data types when using the DPCPP CUDA backend.

Change accessor image channel data types when using DPCPP CUDA backend

---

CMakeLists.txt
cmake/FindComputeCpp.cmake
cmake/FindIntel_SYCL.cmake
cmake/FindhipSYCL.cmake

SYCL 2020 requires compiler to support C++17 at least.
Update SYCL version for DPC++ compiler from 1.2.1 to 2020.

[CMake] Update C++ and SYCL versions for 2020.

---

tests/common/common_vec.h
tests/vector_operators/generate_vector_operators.py
util/accuracy.h
util/type_traits.h

Changing the verification of vec division operator for floating point types to allow errors within 2.5 ulp (according to OpenCL spec, section 7.4)

Allow small ULP errors for vec operator/

---

CMakeLists.txt
README.rst
run_conformance_tests.py
tools/stylesheet.xml

Improving data type coverage up to the full one can give an
unreasonable performance overhead for the specific functionality,
like accessors.
Type coverage for the default mode should be balanced in terms of
coverage and performance, but there should be an option to make all
extra checks when performance doesn't matter.

Add extensive mode cmake option

---

cmake/FindIntel_SYCL.cmake

Intel Compiler on windows accepts `/fp:keyword` for fp-model control,
instead of `-ffp-model=keyword`.
Signed-off-by: Yilong Guo <yilong.guo@intel.com>

[SYCL-1.2.1][CMake] Fix fp-model flag on windows for Intel Compiler

---

tests/accessor/accessor_api_common_buffer_local.h
tests/accessor/accessor_api_image_common.h
tests/atomic/atomic_api_32.cpp
tests/atomic/atomic_api_64_base.cpp
tests/atomic/atomic_api_64_extended.cpp
tests/atomic/atomic_constructors_common.h
tests/common/get_cts_object.h
tests/invoke/invoke_kernel_param_sizes.cpp
tests/invoke/invoke_kernel_params.cpp
tests/invoke/invoke_template_kernels.cpp
tests/item/item_1d.cpp
tests/item/item_2d.cpp
tests/item/item_3d.cpp
tests/kernel/kernel_constructors.cpp
tests/nd_item/nd_item.cpp
tests/program/program_constructors.cpp
tests/stream/stream_constructors.cpp

SYCL 2020 is changing kernel functions to be const.

Changing the conformance tests to use const kernel functions

---

tests/group/group_constructors.cpp
tests/nd_item/nd_item_constructors.cpp
util/array.h

Provide replacement type for fixed-width array to use in kernel functions. Implicitly uses pointer arithmetic for C++ ranged-for.

Provide std::array replacement for kernel code

---

tests/common/get_cts_object.h

We have tests where running multiple work-items used mainly to avoid
false-positives, running the same test N times. Barriers is an
example of such functionality.
When we extend such tests for multiple dimensions, it's reasonable to
run the same number of checks for different dimensionality. This
function allows us to easily provide custom ranges for different
dimensions, still using the same number of work-items.

Add fixed range construction helper

---

tests/common/type_coverage.h

Type coverage requires:
- scalar and vector types support;
- similar calls for different types, with proper type name logging
all over test code base. These facade functions make possible to avoid code duplication

Add type coverage facade functions

---

tests/group/group_api.cpp
tests/nd_item/nd_item_api.cpp

Changed test name nd_item to nd_item_api along with its file name
to allow it to be run separately from other nd_item tests.
Fixed gaps:
- nd_item::get_global_range()
- nd_item::get_local_range()
- dimensions 1 and 2 for tests in group_api.cpp
- added result verification for nd_item::get_*_linear_id()
Extra gaps fixed:
- added return type verification for group_api calls
Not covered by this commit:
- nd_item and group constructors and equality operators gaps
- nd_item and group mem_fence() and barrier() gaps
- nd_item and group async_work_group_copy() and wait_for() gaps
- group::parallel_for_work_item()
Depends on PR: #80 
Commit to start review: b8e60f0 - "Improve test coverage for nd_item and group range, id and subscripts"

Improve test coverage for nd_item and group range, id and subscripts

---

tests/handler/handler_copy.cpp

In similar vein to #54, this PR improves the "handler_copy" tests to be much more robust, verifying that the various explicit memory operations actually do what they are supposed to do. Since these operations are highly configurable and thus prone to edge case bugs, I've spent considerable time on a solution that (I think) covers most if not all possible combinations.
Note that the test suite should probably be called "handler_explicit_memory_operations" or something similar, but I've decided to stick with the existing file name and terminology used within the test cases. So do keep in mind that while I'll mostly be talking about "copies" here, this usually also includes the `handler::fill` and to a lesser extent the `handler::update_host` function.
For a more complete changelog please …

Improve copy tests

---

tests/common/get_cts_object.h

To provide a uniform way to retrieve id for different dimensions

Add id construction helper

---

util/extensions.h

Makes possible common codebase for different extensions with further tag-based code path divergence. Provides single responsibility point for extensions availability check.

Add facade for extensions availability check

---

CMakeLists.txt
cmake/FindIntel_SYCL.cmake
cmake/FindhipSYCL.cmake

Same as #87, but for `SYCL-2020`. Actually there have been some changes to `FindIntel_SYCL.cmake` (e.g. in #76), so I had to adjust the patch slightly.

[2020] Set CMake project language to CXX

---

tests/event/event_info.cpp

This improves the tests for `event::get_info` and `event::get_profiling_info`:
- Remove query for deprecated `sycl::info::event::reference_count`.
- Check that command execution status is updated correctly without prior call to `event::wait`. This was the initial reason for taking this up, as the DPC++ CUDA backend currently has this bug.
- Update return types of `event::get_profiling_info` for SYCL 2020.
- Do basic sanity checks on profiling timestamps.
- Transition everything to the new `::sycl` namespace (for which I added a local alias, as to not depend on #108).

Improve event_info tests

---

test_plans/README.md
test_plans/spec-constants.asciidoc
test_plans/spec-constants.md

We are starting to write test pans for SYCL 2020 features before
writing actual conformance tests.  This is at an example test plan,
which serves as an example plan and also describes the tests needed
for the specialization constant API.

Add a test plan for spec constants

---

tests/buffer/buffer_api_common.h

`unsigned` is not supposed to hold memory size, so using it that way
leads to incorrect memory size values due to overflow on certain
platforms where sizeof(unsigned) < sizeof(size_t).
Patch by Rajiv Deodhar.

Use size_t data for buffer size calculation

---

test_plans/spec-constants.asciidoc

Since `specialization_id` variables need to be declared `constexpr`,
it is not possible to declare an external reference to one.  However,
we can declare the variable `inline constexpr` to achieve a similar
effect.

Update spec const test plan: don't use extern

---

tests/accessor/accessor_api_image_common.h
tests/accessor/accessor_api_local_common.h
tests/accessor/accessor_types_core.h

Fix three compilation issues within accessor tests:
- use vec::element_type for image accessors
- fix atomic64 code path for local accessors
- fix user types verification

Fix tests for accessors

---

tests/h_item/h_item_api.cpp
tests/h_item/h_item_constructors.cpp
tests/h_item/h_item_equality.cpp

Local id values are stored from each work-group asynchronously.
We are using the fact that all bitwise-equal values go into the same memory to simplify the test logic.

Improve result verification for h_item API

---

tests/common/sycl.h

SYCL 2020 introduces a new canonical namespace, `::sycl`, which is defined within the new `<sycl/sycl.hpp>` header. To ease the transition of the CTS to the new namespace, this creates an alias `sycl = cl::sycl`, while keeping the SYCL 1.2.1 header path `<CL/sycl.hpp>` for the time being.
For the record, I also tried going the reverse route, i.e., including `<sycl/sycl.hpp>`, and defining `namespace cl { namespace sycl = ::sycl; }`. However that didn't work, as DPC++ already exports that alias (while e.g. hipSYCL doesn't - the spec isn't super clear on this), and ComputeCpp 2.4 doesn't seem to support the new header at all.

Add sycl = ::cl::sycl namespace alias

---

tests/host_task/CMakeLists.txt
tests/host_task/host_task_interop_api.cpp
tests/host_task/host_task_invoke_api.cpp

Provide testing host tasks and sycl::interop_handle::get_native function.
Test for sycl::interop_handle::get_native function can be launched only if OpenCL back-end supported.

Added host task test suite

---

cmake/FindIntel_SYCL.cmake

this commit, does this:
- Alleviate the CMake script from device triple checks
- Fix the quote sequence for GPU AOT options' passing

Refactor the setting of Intel CTS flags

---

tests/usm/usm.h
tests/usm/usm_aligned_alloc.cpp
tests/usm/usm_aligned_alloc_device.cpp
tests/usm/usm_aligned_alloc_host.cpp
tests/usm/usm_aligned_alloc_shared.cpp
tests/usm/usm_allocate_free.h
tests/usm/usm_allocations_helper.h
tests/usm/usm_allocator_api.cpp
tests/usm/usm_allocator_api.h
tests/usm/usm_allocator_api_aligned.cpp
tests/usm/usm_allocator_constructors.cpp
tests/usm/usm_allocator_constructors.h
tests/usm/usm_fill_memset_memcpy.cpp
tests/usm/usm_get_pointer_queries.cpp
tests/usm/usm_malloc.cpp
tests/usm/usm_malloc_device.cpp
tests/usm/usm_malloc_host.cpp
tests/usm/usm_malloc_shared.cpp

Provide tests for:
- usm::malloc and usm::aligned_alloc overloads for all sycl::usm::alloc kinds
- usm::malloc_(device/host/shared) overloads
- usm::aligned_alloc_(device/host/shared) overloads
- usm::free
- usm_allocator constructors
- usm_allocator api
This PR relies on #131 to use common file: tests/usm/usm.h
**Please review from this commit:** https://github.com/KhronosGroup/SYCL-CTS/commit/ef0f0f98cb39306d2e61d2b53dccaf3ba36a80ae

Add tests for usm allocate/free functions and usm_allocator

---

tests/usm/usm.h
tests/usm/usm_fill_memset_memcpy.cpp
tests/usm/usm_get_pointer_queries.cpp

Provide verification to cooperation USM functions get_pointer_type
and get_pointer_device with four memory allocation types:
host, device, shared and non USM allocation.

Add new test for get_pointer_type and get_pointer_device USM API

---

README.rst
runtests.py
tests/CMakeLists.txt
tests/common/cts_selector.h
util/selector.cpp
util/selector.h
util/test_manager.cpp

Hardcoding vendor names makes it difficult to run the CTS on custom devices.
This patch removes default platform selection code altogether.
It's still possible to specify the device type to run on,
but implementations should provide their own ways
of performing selection between multiple platforms.
This includes completely removing the `--platform` argument,
the `ctsplat` enum value, and the `get/set_default_platform` functions.
Changed argument parsing to `parse_known_args`
to allow existing script calls to still work.

Remove default platform selection

---

tests/math_builtin_api/CMakeLists.txt

`SYCL_CTS_ENABLE_HALF_TESTS` and `SYCL_CTS_ENABLE_DOUBLE_TESTS`
were applied to most tests, but not to `math_builtin_api`.

Skip half and double builtin tests if not enabled

---

CMakeLists.txt
cmake/AddSYCLExecutable.cmake
cmake/FindComputeCpp.cmake
cmake/FindIntel_SYCL.cmake
cmake/FindhipSYCL.cmake

The CTS sets some preprocessor definitions using `add_definitions`,
which causes host/device inconsistencies when using a split-compiler approach.
This patch adds `add_device_compiler_definitions`
and `add_host_and_device_compiler_definitions`
that are meant to unify preprocessor definitions between host and device compilers.
It is expected that this won't have an impact on single-compiler implementations
since only host definitions matter in that case.

add_device_compiler_definitions

---

CMakeLists.txt
README.rst
util/logger.h

Sometimes it's important to have more detailed output from the tests up to the trace of actions made.
Providing such information on the regular basis would pull the performance down. Therefore compile-time switch is required to avoid all message construction routines entirely. Lambda usage makes possible to avoid heavy message construction in case compile-time switch is off. String, string view and string literal instances can be used without overhead.
As a side note, currently tests within `tests/accessors` are using undocumented `#ifdef VERBOSE_LOG` for the purpose of trace output.

Provide debug level for logs

---

tests/exception_handling/synchronous_exceptions.cpp

Fix missing namespace in synchronous_exceptions test

---

tests/CMakeLists.txt
tests/math_builtin_api/CMakeLists.txt

Bringing https://github.com/KhronosGroup/SYCL-CTS/pull/71 and https://github.com/KhronosGroup/SYCL-CTS/pull/138 into the SYCL 2020 branch.

Skip half and double builtin tests if not enabled [SYCL 2020]

---

tests/specialization_constants/specialization_constants_defined_various_ways.h
tests/specialization_constants/specialization_constants_defined_various_ways_core.cpp
tests/specialization_constants/specialization_constants_defined_various_ways_fp16.cpp
tests/specialization_constants/specialization_constants_defined_various_ways_fp64.cpp
tests/specialization_constants/specialization_constants_defined_various_ways_helper.h
tests/specialization_constants/specialization_constants_defined_various_ways_via_kb_core.cpp
tests/specialization_constants/specialization_constants_defined_various_ways_via_kb_fp16.cpp
tests/specialization_constants/specialization_constants_defined_various_ways_via_kb_fp64.cpp

Provides tests for specialization constants defined various ways
Based on #140  (got common code (tests/specialization_constants/specialization_constants_common.h) from this PR)
Please review from commit: 9a6354a6fd0439433f928452250c5bfeb841b0af

Add test for specialization constants defined various ways

---

tests/usm/usm_api.h
tests/usm/usm_api_copy_queue_no_events.cpp
tests/usm/usm_api_fill_queue_no_events.cpp
tests/usm/usm_api_mem_advise_queue_no_events.cpp
tests/usm/usm_api_memcpy_queue_no_events.cpp
tests/usm/usm_api_memset_queue_no_events.cpp
tests/usm/usm_api_prefetch_queue_no_events.cpp
util/exceptions.h

Provides tests for queue shortcut functions for USM operations: copy, memcpy, fill, memset, prefetch, mem_advise.
All USM allocation types are verified. For copy and memcpy tests all permutations of USM allocation and non-USM pointer are verified. For mem_advise() and prefetch() calls only method availability is verified.
This commit doesn't provide tests for:
handler functions for USM operations
queue USM shortcut functions overloads with events

Provide tests for queue USM API

---

tests/usm/usm_api.h
tests/usm/usm_api_copy_queue_multiple_events.cpp
tests/usm/usm_api_copy_queue_single_event.cpp
tests/usm/usm_api_fill_queue_multiple_events.cpp
tests/usm/usm_api_fill_queue_single_event.cpp
tests/usm/usm_api_mem_advise_queue_multiple_events.cpp
tests/usm/usm_api_mem_advise_queue_single_event.cpp
tests/usm/usm_api_memcpy_queue_multiple_events.cpp
tests/usm/usm_api_memcpy_queue_single_event.cpp
tests/usm/usm_api_memset_queue_multiple_events.cpp
tests/usm/usm_api_memset_queue_single_event.cpp
tests/usm/usm_api_prefetch_queue_multiple_events.cpp
tests/usm/usm_api_prefetch_queue_single_event.cpp
util/exceptions.h

Provides tests for queue shortcut functions with one or multiply events for USM operations: copy, memcpy, fill, memset, prefetch, mem_advise
Common code was received from PR #152
Please start review from this commit: ab446b940d371580cc7fe03d368c5186ec17804e

Add tests for queue USM API with one or multiply sycl::event

---

tests/specialization_constants/specialization_constants_external.h
tests/specialization_constants/specialization_constants_external_core.cpp
tests/specialization_constants/specialization_constants_external_fp16.cpp
tests/specialization_constants/specialization_constants_external_fp64.cpp
tests/specialization_constants/specialization_constants_separate_unit.cpp

Provides tests for specialization constants external
Based on #140  (got common code (tests/specialization_constants/specialization_constants_common.h) from this PR)
Please review from commit: cfde845a30bc9af1c719d32257e6ab5af0e3a50a

Add test for specialization constants external

---

tests/specialization_constants/specialization_constants_via_kernel_bundle.h
tests/specialization_constants/specialization_constants_via_kernel_bundle_core.cpp
tests/specialization_constants/specialization_constants_via_kernel_bundle_fp16.cpp
tests/specialization_constants/specialization_constants_via_kernel_bundle_fp64.cpp

Provides tests for specialization constants via kernel bundle
Based on #140 (got common code (tests/specialization_constants/specialization_constants_common.h) from this PR)
Please review from commit: 34c9d6c5a0aba5e414839b99b8c651bfb5b27a64

Add test for specialization constants via kernel bundle

---

tests/multi_ptr/multi_ptr_api_fp16.cpp
tests/multi_ptr/multi_ptr_constructors_fp16.cpp

Recent SYCL 1.2.1 and SYCL 2020 specification put half type to sycl
namespace. This change replaces use of the half type from global
namespace with sycl::half.

Remove use of half from global namespace

---

CMakeLists.txt
cmake/AddSYCLExecutable.cmake
cmake/FindComputeCpp.cmake
cmake/FindIntel_SYCL.cmake
cmake/FindhipSYCL.cmake

Bringing https://github.com/KhronosGroup/SYCL-CTS/pull/139 into the SYCL 2020 branch.
I also noticed that `SYCL_CTS_INTEL_PI_CUDA` isn't set like it is in the 1.2.1 branch, so I included that change, I can remove it if needed.

add_device_compiler_definitions [SYCL 2020]

---

tests/buffer/buffer_api_common.h
tests/buffer/buffer_constructors_common.h
tests/buffer/buffer_storage_common.h

Update buffer_allocator to have templates
Rename deprecated functions get_count() and get_size() to size() and byte_size()

Update tests for buffer for SYCL2020

---

tests/atomic/atomic_api_64_base.cpp
tests/atomic/atomic_api_64_extended.cpp
tests/atomic/atomic_constructors_64.cpp
tests/platform/platform_api.cpp
util/extensions.h
util/test_manager.cpp

- All has_extension(string) calls replaced with has(aspect)
- Removed has_extension(string) calls with extension without corresponding sycl::aspect (according to Table 189. "SYCL support for OpenCL 1.2 extensions" from the SYCL 2020 Spec)

(Deprecated API) Remove has_extension() and replace it with .has() method

---

tests/item/item_1d.cpp
tests/item/item_2d.cpp
tests/item/item_3d.cpp
tests/nd_item/nd_item_api.cpp
tests/nd_item/nd_item_constructors.cpp
tests/nd_range/nd_range_api.cpp
tests/nd_range/nd_range_constructors.cpp

Offsets to nd_range, nd_item and item classes have been deprecated in SYCL 2020.

Remove checks with offset for nd_range, nd_item and item classes

---

tests/accessor/accessor_api_buffer_common.h
tests/accessor/accessor_api_image_common.h
tests/accessor/accessor_api_local_common.h
tests/accessor/accessor_constructors_buffer_utility.h
tests/accessor/accessor_constructors_utility.h
tests/group/group_mem_fence_common.h
tests/host_task/host_task_invoke_api.cpp
tests/nd_item/nd_item_mem_fence_common.h

get_count() is deprecated in SYCL 2020
Usage of it in buffer, vector and opencl_interop tests are changed in other patches

Update member function of various classes 'get_count' to 'size'

---

tests/usm/usm_api.h
tests/usm/usm_api_copy_handler_no_events.cpp
tests/usm/usm_api_fill_handler_no_events.cpp
tests/usm/usm_api_mem_advise_handler_no_events.cpp
tests/usm/usm_api_memcpy_handler_no_events.cpp
tests/usm/usm_api_memset_handler_no_events.cpp
tests/usm/usm_api_prefetch_handler_no_events.cpp
util/exceptions.h

Provides tests for overloads of the handler's functions for USM operations: copy, memcpy, fill, memset, prefetch and mem_advise.
This tests does not provide verification for handler's functions with events
Common code was received from PR #152
Please start review from this commit: f5518702459424b717c7dd65fa59e1511834ebfb

Provides tests for USM API without events

---

CMakeLists.txt
cmake/AddSYCLExecutable.cmake
cmake/FindDPCPP.cmake
cmake/FindIntel_SYCL.cmake

Intel_SYCL is still supported, but deprecated.

Rename Intel_SYCL implementation to DPCPP.

---

tests/specialization_constants/specialization_constants_common.h
tests/specialization_constants/specialization_constants_same_command_group_common.h
tests/specialization_constants/specialization_constants_same_command_group_core.cpp
tests/specialization_constants/specialization_constants_same_command_group_fp16.cpp
tests/specialization_constants/specialization_constants_same_command_group_fp64.cpp

Provides tests for specialization constants with same command group
Based on #140  (got common code (tests/specialization_constants/specialization_constants_common.h) from this PR)
Please review from commit: 2249a311bcc2cbdc502bb694620818aa04b7786e

Add test for specialization constants same command group

---

tests/specialization_constants/specialization_constants_via_handler_common.h
tests/specialization_constants/specialization_constants_via_handler_core.cpp
tests/specialization_constants/specialization_constants_via_handler_fp16.cpp
tests/specialization_constants/specialization_constants_via_handler_fp64.cpp

Provides tests for specialization constants via handler
Based on #140  (got common code (tests/specialization_constants/specialization_constants_common.h) from this PR)
Please review from commit: ef09455e3934f62dbbc29a8a2e4e21aac7764139

Add test for specialization constants via handler

---

tests/opencl_interop/opencl_interop_constructors.cpp
tests/opencl_interop/opencl_interop_get.cpp
tests/opencl_interop/opencl_interop_kernel.cpp
util/test_base_opencl.cpp

Added check if SYCL_BACKEND_OPENCL is defined
Replaced method get() with function get_native()
Replaced removed constructors with make_*()
Removed checks for program's get_compile_options and get_link_options in opencl_interop_kernel.cpp as program is removed and there are no clear counterparts in kernel_bundle for it.

Update opencl_interop tests for SYCL 2020 style

---

tests/accessor/accessor_api_image_common.h

Upper coordinate in case of floating-point CoordT should use different texels for linear filtration.
See ["Filter Mode CLK_FILTER_LINEAR"](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#addressing-and-filter-modes) in OpenCL C Specification we are using according to the SYCL 1.2.1 par.3.

Fix reference values for sampled access with linear filtration

---

tests/address_space/address_space_common.h
util/kernel_names.h

There is a plenty of restrictions on types for kernel names.
Still we may need to cover some types that should not be used for kernel names and kernel names' template parameters. Such type
coverage still require some generic code, so to avoid passing specific kernel names all the way through generic code we may just use some adapter to construct safe kernel name right in place.

Provide adapter for type usage in kernel names

---

tests/accessor/accessor_api_buffer_common.h
tests/accessor/accessor_api_image_common.h
tests/accessor/accessor_api_local_common.h
tests/buffer/buffer_api_common.h
tests/common/common_vec.h
tests/item/item_1d.cpp
tests/item/item_2d.cpp
tests/item/item_3d.cpp
tests/nd_item/nd_item_api.cpp
tests/nd_item/nd_item_constructors.cpp
tests/nd_range/nd_range_api.cpp
tests/nd_range/nd_range_constructors.cpp
tests/platform/platform_api.cpp

Return checks for deprecated APIs that were removed in following PRs: https://github.com/KhronosGroup/SYCL-CTS/pull/168, https://github.com/KhronosGroup/SYCL-CTS/pull/163, https://github.com/KhronosGroup/SYCL-CTS/pull/156, https://github.com/KhronosGroup/SYCL-CTS/pull/164, https://github.com/KhronosGroup/SYCL-CTS/pull/159

Return previously removed checks for deprecated APIs

---

tests/accessor/accessor_api_common_buffer_local.h

Fix reading uninitialized values for `sycl::access_mode::discard_read_write` in `accessor_api_buffer_*` tests.
Provides fixes for:
- `get_pointer()` test logic
- `operator[]()` test logic

Fix discard_read_write logic for accessor tests

---

util/math_reference.h

Looks like implementations implicitly include `<cmath>` to implement builtins. However, that is not required by the spec.

Do not rely on implementations to include <cmath>

---

tests/reduction/reduction_without_identity_param_common.h
tests/reduction/reduction_without_identity_param_core.cpp
tests/reduction/reduction_without_identity_param_fp16.cpp
tests/reduction/reduction_without_identity_param_fp64.cpp

Provide verification for three `sycl::reduction` overloads:
- reduction with `USM allocation` and functor
- reduction with `sycl::buffer`
- reduction with `sycl::span`
for scalar types and for different functors
Common code can be found here: [SYCL-CTS PR#165 ](https://github.com/KhronosGroup/SYCL-CTS/pull/165)

Add tests for reduction without identity value parameter

---

tests/common/common.h
tests/common/get_cts_object.h

Fix regression introduced in #179.

Avoid use of sycl::get_kernel_bundle for CCPP & hipSYCL

---

.github/workflows/cts_ci.yml

Build the set of supported test categories for each SYCL implementation during CI runs. This uses the generated exclude filters within the ./ci directory to limit the set of tests to compile for each implementation.
Limit parallel jobs to 2 (-j3 is Ninja's default on GitHub hosted runners), as we otherwise risk running out of memory.
Edit: A consequence of this is that CI runs take considerably longer. I will attempt to address this in a future PR.

Build supported test categories during CI

---

util/executor.cpp

Add message to the console with the information about number skipped tests, the message will look like:
```
--- some_test
. **Check #1 skipped**
- skip
. **Check #2 passed**
. Passed 0/1 tests (0%)
. Skipped 1/1 tests (100%)
```
The test will be marked as `Skipped` after `log.skip()` called even if some other check in the same test passed

Add possible to see which tests were skipped and which tests were passed

---

cmake/FindDPCPP.cmake

In commit 81e0863b897cd0f7ccbf5c5e1d596563ccca8555 the /subsystem:console flag
was removed from LINK_FLAGS for DPC++ on Windows. But this was done for
CMake 3.21+ only. The CMake versions until to CMake 3.20 use the
'CMAKE_CREATE_CONSOLE_EXE' variable instead of 'CMAKE_CXX_CREATE_CONSOLE_EXE
one that is used in the latest version. The 'replace' instruction for the
'CMAKE_CREATE_CONSOLE_EXE' variable is restored.

Remove /subsystem:console from LINK_FLAGS for DPC++ for CMake <= 3.20

---

tests/accessor/accessor_api_common_buffer_local.h

SYCL 2020 specifies that `accessor::get_pointer()` always returns the base buffer pointer, ignoring any offset.  Update the tests to reflect this expectation.
This is my first PR for the CTS tests on KhronosGroup.  Let me know if there are procedural conventions that I overlooked.

accessor::get_pointer() should ignore offset

---

tests/specialization_constants/specialization_constants_external.h

It's implementation-defined if a kernel is available in a bundle with `bundle_state::input`.
So if such bundle misses some kernels it shouldn't trigger a test failure.

Fix spurious failure for `specialization_constants_external` tests

---

tests/common/common.h
tests/context/context_constructors.cpp
tests/device/device_api.cpp
tests/device/device_constructors.cpp
tests/event/event_api.cpp
tests/event/event_constructors.cpp
tests/platform/platform_constructors.cpp
tests/queue/queue_api.cpp

In classes context, device, event, platform, queue

Remove member function get() that are removed in SYCL 2020

---

ci/computecpp.filter
tests/common/common.h

This should fix compilation with ComputeCpp again, which was broken in #203. Also update CI filter for ComputeCpp to include three new test categories that no longer compile (`context`, `device` and `platform`).

Fix compilation with ComputeCpp; update CI filter

---

.github/workflows/build_ci_containers.yml
.github/workflows/cts_ci.yml
ci/dpcpp.filter

This PR supersedes both #234 and #240.
Changes compared to #234:
- Bump DPC++ to 1f3f9b9 (December 19) to accommodate #240 
- Work around ComputeCpp container images not using versioned tags yet
- Don't enable a ton of new test categories for DPC++ due to compile time concerns (which we should address in a separate PR, see also the discussion on #234).
(Note that CI will fail on this initially since the new container for DPC++ is [still building](https://github.com/KhronosGroup/SYCL-CTS/runs/4586121973?check_suite_focus=true), need to re-run checks after that).

Bump DPC++ and hipSYCL versions used for CI

---

ci/computecpp.filter
ci/hipsycl.filter
tests/CMakeLists.txt
tests/common/common_by_reference.h
tests/common/common_semantics.h
tests/group/group_constructors.cpp
tests/group/group_equality.cpp
tests/h_item/h_item_equality.cpp
tests/id/id_constructors.cpp
tests/item/item_equality.cpp
tests/kernel_bundle/CMakeLists.txt
tests/kernel_bundle/get_kernel_id.h
tests/kernel_bundle/get_kernel_id_function.cpp
tests/kernel_bundle/get_kernel_ids_multiple_kernels.cpp
tests/kernel_bundle/get_kernel_ids_no_kernels.cpp
tests/kernel_bundle/get_kernel_ids_single_kernel.cpp
tests/kernel_bundle/kernel_bundle.h
tests/kernel_bundle/kernel_id_api.cpp
tests/kernel_bundle/kernel_id_common_reference_semantics.cpp
tests/nd_item/nd_item_constructors.cpp
tests/nd_item/nd_item_equality.cpp
tests/nd_range/nd_range_equality.cpp
tests/range/range_constructors.cpp
util/exceptions.h

Some of these test required containing in separate *.exe-file: `get_kernel_ids_multiple_kernels`, `get_kernel_ids_single_kernel` and `get_kernel_ids_no_kernels` because these files required stricted list of available kernels
for build this tests need call building process for each test separately: `make test_get_kernel_ids_multiple_kernels`, `make test_get_kernel_ids_single_kernel` and `make test_get_kernel_ids_no_kernels`
But if use `make` all tests will be builded

Tests for sycl::get_kernel_id and sycl::get_kernel_ids

---

cmake/FindComputeCpp.cmake

This commit updates cmake/FindComputeCpp.cmake to avoid the use of tabs in command lines. The tabs are valid but cause issues when copying and pasting commands to run them standalone, as even the pasting of a tab may trigger tab completion, depending on the shell and shell settings.
The tabs were a workaround for older CMake versions, but a sufficiently recent CMake is already required.
I have verified that with this MR applied, with the Ninja generator, the only change to the generated `build.ninja` is the removal of the tabs.
Note: this PR is against SYCL-2020 but also applies cleanly to SYCL-1.2.1/master. If this gets approved and merged to SYCL-2020, I would appreciate it if it could also be cherry-picked there, or I can create a new PR for that.

Avoid tabs in command lines

---

tests/accessor/accessor_api_image_common.h

When the acc_coord_tag::use_normalized_upper tag is used to compute
the expected values in the linear filtering mode, the value for idx + 1
is used as expected (see the return get_expected_value_linear(idx + 1)
line in the body of the T get_expected_value(image_id_t<dim, target> idx)
method of the image_accessor_api_sampled_r class). This fact is taken into
account in the image_access<dims>::get_normalized() function and works
fine for a single image but not for image arrays since for the image array,
a correct slice should be the next one when the linear filtering mode is
used and the test is run for acc_coord_tag::use_normalized_upper tag.
Signed-off-by: Pavel Samolysov <pavel.samolysov@intel.com>

Fix accessor_api_image_core test for image arrays

---

tests/accessor/accessor_api_image_common.h

The OpenCL specification rules that when int is used as the coordinates, the
filter mode must be NEAREST (see https://man.opencl.org/read_imagef1d.html):
> The read_imagef calls that take integer coordinates must use a sampler with
> filter mode set to CLK_FILTER_NEAREST, normalized coordinates set to
> CLK_NORMALIZED_COORDS_FALSE and addressing mode set to CLK_ADDRESS_CLAMP_TO_EDGE,
> CLK_ADDRESS_CLAMP or CLK_ADDRESS_NONE; otherwise the values returned are
> undefined.
Signed-off-by: Pavel Samolysov <pavel.samolysov@intel.com>

Run accessor_api_image_core test with int coords for nearest only

---

util/array.h

This fix adds include directive of the header file with `std::size_t` definition to `util/array.h`.

Small fix for `util/array.h`

---

run_conformance_tests.py

Looks like we need to escape `additional_args` , so we can pass a path within `additional_args` on Windows systems without backslashes removed by `shlex.split()` call.

Fix conformance script arguments parsing

---

tests/extension/oneapi_device_global/device_global_api_arrow_operator.cpp
tests/extension/oneapi_device_global/device_global_api_basic.cpp
tests/extension/oneapi_device_global/device_global_api_subscript_operator.cpp
tests/extension/oneapi_property_list/property_list_prop_eq_op.cpp
tests/extension/oneapi_property_list/property_list_property_value.cpp
tests/multi_ptr/multi_ptr_accessor_constructor_fp16.cpp
tests/multi_ptr/multi_ptr_accessor_constructor_fp64.cpp
tests/multi_ptr/multi_ptr_common_constructors_fp16.cpp
tests/multi_ptr/multi_ptr_common_constructors_fp64.cpp
tests/multi_ptr/multi_ptr_members_fp16.cpp
tests/multi_ptr/multi_ptr_members_fp64.cpp

This PR provides replacement of deprecated log function `log.skip` to `WARN` function from catch2 framework

Replace `log.skip` to `WARN`

---

tests/extension/oneapi_device_global/device_global_common.h
tests/extension/oneapi_device_global/device_global_functional_one_kernel.cpp

The test calls one kernel multiple times on one device and tries to read/write value from the `device_global` instance.
Depends on:
- #249 
Requires device_global class implementation and enum class `sycl::access::decorated` for build.
[Link](https://github.com/KhronosGroup/SYCL-CTS/pull/253/files/bacf91dabcdb7b8bcab10c270ec1f9377c220a72..HEAD) to changes related to this PR

Functional test for extension oneapi::device_global. One kernel multiple times

---

tests/exceptions/exceptions_make_error_code.cpp

`typeid(std::error_code())` uses `typeid(type)` overload

Hotfix type check for sycl::make_error_code

---

tests/extension/oneapi_device_global/device_global_functional_several_kernels_one_device.cpp

The test modifies the `device_global` instance in one kernel and expects to read the same value from another kernel on the same device.
Requires device_global class implementation and enum class `sycl::access::decorated` for build.
[Link](https://github.com/KhronosGroup/SYCL-CTS/pull/254/files/bacf91dabcdb7b8bcab10c270ec1f9377c220a72..HEAD) to changes related to this PR.

Functional test for extension oneapi::device_global. Several kernels on one device.

---

tests/common/type_list.h
tests/extension/oneapi_device_global/device_global_common.h
tests/extension/oneapi_device_global/device_global_queue_array_copy.cpp
tests/extension/oneapi_device_global/device_global_queue_copy.cpp

This PR provides a functional test for extension [device_global](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/DeviceGlobal/SYCL_INTEL_device_global.asciidoc)
It checks the correctness of `sycl::queue` shortcuts `copy()` with `device_global` parameter.

Add tests for queue copy overloads for device_global

---

.github/workflows/cts_ci.yml
ci/hipsycl.filter

Two new test categories now compile: platform and sub_group_mask.

Bump hipSYCL CI container version to 3d8b1cd

---

util/extensions.h

Otherwise we might trigger compilation failure depending on order of includes in test

Add missing includes in util/extensions.h

---

tests/extension/oneapi_device_global/device_global_common.h
tests/extension/oneapi_device_global/device_global_functional_spec_constants.cpp

Checks interaction of `device_global` instance with specialization constants
[Link](https://github.com/KhronosGroup/SYCL-CTS/pull/262/files/a3e2c57ea7eb8525dc8508da9022743487d57bf3..HEAD) to changes related to this PR.

Functional test for extension `oneapi::device_global`. Spec constants interaction

---

tests/extension/oneapi_device_global/device_global_common.h
tests/extension/oneapi_device_global/device_global_functional_kernel_bundle.cpp

Tests interaction with kernel bundle
[Link](https://github.com/KhronosGroup/SYCL-CTS/pull/263/files/f18ede7c70d2e5fddd3ab0171f6c63fa6be0812f..HEAD) to changes related to this PR.

Functional test for extension `oneapi::device_global`. Interaction with kernel bundle.

---

tests/extension/oneapi_device_global/device_global_common.h
tests/extension/oneapi_device_global/device_global_functional_pass_pointer.cpp

This PR provides a functional test for device_global:
Tests passing a pointer to the underlying data to another kernel
[Link](https://github.com/KhronosGroup/SYCL-CTS/pull/264/files/2567537a666401fe3c2c28d1fbc92494c0ebfb76..HEAD) to changes related to this PR.

Functional test for extension `oneapi::device_global`. Pass a pointer to the underlying `T` type to another kernel.

---

tests/extension/oneapi_device_global/device_global_common.h
tests/extension/oneapi_device_global/device_global_functional_define_various_ways.cpp

The test creates `device_global` instance in various ways and verifies that the instance was created correctly. 
[Link](https://github.com/KhronosGroup/SYCL-CTS/pull/265/files/6f2f595870aee957abf06af19bb2424b1a6c18c0..HEAD) to changes related to this PR.

Functional test for extension `oneapi::device_global`. Defined in various ways.

---

tests/extension/oneapi_device_global/device_global_common.h
tests/extension/oneapi_device_global/device_global_queue_memcpy.cpp

This PR provides a functional test for extension [device_global](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/DeviceGlobal/SYCL_INTEL_device_global.asciidoc)
It checks the correctness of `sycl::queue` shortcuts `memcpy()` with `device_global` parameter.

Add tests for queue::memcpy overloads for device_global

---

tests/usm/usm_atomic_access.h
tests/usm/usm_fill_memset_memcpy.cpp
tests/usm/usm_get_pointer_queries.cpp
util/usm_helper.h

Remove incorrect include `common.h` from `usm.helper`.
And add include `common.h` where it's actually required.

Fix includes in usm tests

---

test_plans/device_global.asciidoc

Adding test plan for recently added tests in https://github.com/KhronosGroup/SYCL-CTS/tree/SYCL-2020/tests/extension/oneapi_device_global

Add test plan for device_global

---

test_plans/compile-time-property_list.asciidoc

Adding test plan for recently added tests in https://github.com/KhronosGroup/SYCL-CTS/tree/SYCL-2020/tests/extension/oneapi_property_list

Add test plan for compile time property_list

---

tests/usm/usm_atomic_access.h

Fixes usm_atomic_access_atomic64 that used seq_cst atomics without checking if they are supported by the device. This PR changes the test to only run if seq_cst atomics are supported.
Here is a report of this test failing when run with DPC++ on a Nvidia GPU: https://github.com/intel/llvm/issues/5210

Fix usm_atomic_access_atomic64 using unsupported atomics

---

tests/usm/usm_get_pointer_queries.cpp
util/usm_helper.h

This fix is needed because the spec says that the first device
should be used if allocation is usm::alloc::host

Fix allocation USM for host device

---

ci/hipsycl.filter
tests/common/disabled_for_test_case.h
tests/id/id.cpp

This introduces a new type of test case macro that can be used to disable test cases during compile-time. This is useful for when a test case contains code that  currently does not compile for a given implementation, while other test cases in the same translation unit would otherwise compile.
A disabled test case will fail automatically at runtime.
While all Catch2 test macros could likely be supported in principle, this initial implementation is limited to these two:
- `DISABLED_FOR_TEST_CASE` (corresponding to `TEST_CASE`)
- `DISABLED_FOR_TEMPLATE_TEST_CASE_SIG` (corresponding to `TEMPLATE_TEST_CASE_SIG`)
Usage example from `id` tests:
```c++
DISABLED_FOR_TEMPLATE_TEST_CASE_SIG(hipSYCL)
("id supports unary +/- operators", "[id]", ((int D), D), 1, 2, 3)({
// ...
});
```
which then …

Add support for compile-time disabled test cases

---

tests/common/disabled_for_test_case.h

Properly forward `catchMacroProxy` into recursive call.

Fix DISABLED_FOR_* macros with >1 implementation

---

.github/workflows/cts_ci.yml

...to prime `ccache` for faster PR runs. Due to the way GitHub workflows [restrict access to the cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache), PRs cannot access `ccache` data from workflow runs on other PRs. However, PRs *can* access caches generated by workflow runs on the base (target) branch.

Run CI when pushing to SYCL-2020 branch

---

tests/id/id.cpp

The `size_t` doesn't have guarantee in size compared to `unsigned long` or `unsigned long long`.
Therefore we should either explicitly cast to `size_t` or use implicit cast.
Implicit cast fits better, because it uses the type of `get_cts_object::id<>::get()` parameters, avoiding possible support efforts in future.

Fix unsigned wrap in `id` tests

---

tests/common/disabled_for_test_case.h

...when using DISABLED_FOR_* test case macros. This is required as of ComputeCpp 2.8.0, which is based on Clang 8.
Also remove some duplicated macro definitions.

Disable _Pragma to work around Clang 8 bug

---

tests/common/disabled_for_test_case.h

This may not be needed for all implementations, but at least ComputeCpp defines `__COMPUTECPP__` inside a header, instead of on the command line.

Include SYCL header for DISABLED_FOR_* implementation detection

---

tests/event/event.cpp

Required for `std::this_thread::sleep_for`

Add `<thread>` include for event tests

---

tests/common/type_coverage.h
util/type_traits.h

This PR doesn't contain functional or logical changes, only format applying to `type_coverage` and `type_traits`. 
Mostly to simplify the review process for #306, as after merging this PR, #306 will contain only functional changes.

Apply format to `type_coverage` and `type_traits`

---

tests/accessor_legacy/accessor_types_core.h
tests/accessor_legacy/accessor_types_image_core.h
tests/buffer/buffer_type_list.h
tests/common/type_coverage.h
tests/common/type_list.h
tests/extension/oneapi_device_global/type_pack.h
tests/extension/oneapi_sub_group_mask/sub_group_mask_common.h
tests/kernel_bundle/get_kernel_bundle.h
tests/kernel_bundle/has_kernel_bundle.h
tests/kernel_bundle/has_kernel_bundle_core.h
tests/kernel_bundle/kernel_bundle.h
tests/kernel_bundle/use_kernel_bundle.h
tests/multi_ptr/multi_ptr_common.h
tests/reduction/reduction_common.h
tests/specialization_constants/specialization_constants_common.h
tests/usm/usm_atomic_access.h
util/type_traits.h

This PR provides a new function `for_all_combinations` that can combinate types, values, etc.
Refactor old functions like `for_all_type` for removing unused variable and dummy values in fold expression.
Also made constructor of `named_type_pack` private. Instead of a constructor, there is the factory function `generate_named`. This change will allow us to freely change attributes and the way to construct the actual type pack inside the class without changing existing tests.
The function `for_all_combinations` will be used in new accessor tests.
Depends on:
- #308

Improve generic code in `type_coverage.h`

---

tests/kernel_bundle/has_kernel_bundle_core_atomic64_ctx_only.cpp
tests/kernel_bundle/has_kernel_bundle_core_atomic64_dev.cpp
tests/kernel_bundle/has_kernel_bundle_core_fp16_ctx_only.cpp
tests/kernel_bundle/has_kernel_bundle_core_fp16_dev.cpp
tests/kernel_bundle/has_kernel_bundle_core_fp16_fp64_atomic64_dev_and_k_id.cpp
tests/kernel_bundle/has_kernel_bundle_core_fp16_fp64_atomic64_dev_and_k_name.cpp
tests/kernel_bundle/has_kernel_bundle_core_fp16_fp64_atomic64_k_id.cpp
tests/kernel_bundle/has_kernel_bundle_core_fp16_fp64_atomic64_k_name.cpp
tests/kernel_bundle/has_kernel_bundle_core_fp64_ctx_only.cpp
tests/kernel_bundle/has_kernel_bundle_core_fp64_dev.cpp
tests/kernel_bundle/kernels.h

As spec changed during tests implementation, this PR provides replace of non-existing attribute `sycl::requires` to `sycl::device_has` according to [paragraph 5.8.2](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_device_function_attributes) of the current spec.

Change attribute `sycl::requires` to `sycl::device_has`

---

tests/exceptions/exceptions_async_handler.cpp

Tests for [2.6. sycl::async_handler](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/exceptions.asciidoc#26-syclasync_handler)

Add tests for async_handler

---

tests/math_builtin_api/modules/test_generator.py

`float` and `half` tests shouldn't use double type values in the device code.

Fix input value type for float and half math tests

---

tests/handler/handler_copy_common.h
tests/handler/handler_copy_core.cpp
tests/handler/handler_copy_fp64.cpp

Separate checks for double type to run only if a device doesn't support fp64.

Move checks for handler::copy for double type to separate test

---

tests/extension/oneapi_device_global/device_global_handler_copy_memcpy_overloads.cpp

This provides changing of non-existing `sycl_stub` namespace to the `sycl` namespace that corresponds to the spec.

Remove stub from `device_global` test

---

tests/exceptions/exceptions_constructors.cpp

This PR provides tests for sycl::exception constructors according to [paragraph 2.4](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/exceptions.asciidoc#24-syclexception) of the test plan

Add tests for `sycl::exception` constructors

---

tests/accessor_legacy/accessor_api_image_common.h
tests/common/common.h
tests/common/common_vec.h
tests/common/value_helper.h
tests/common/value_operations.h
tests/extension/oneapi_device_global/device_global_api_basic.cpp
tests/extension/oneapi_device_global/device_global_common.h
tests/extension/oneapi_device_global/device_global_functional_define_various_ways.cpp
tests/extension/oneapi_device_global/device_global_functional_kernel_bundle.cpp
tests/extension/oneapi_device_global/device_global_functional_one_kernel.cpp
tests/extension/oneapi_device_global/device_global_functional_pass_pointer.cpp
tests/extension/oneapi_device_global/device_global_functional_several_kernels_one_device.cpp
tests/extension/oneapi_device_global/device_global_functional_spec_constants.cpp
tests/extension/oneapi_device_global/device_global_functional_unique_for_every_device.cpp
tests/extension/oneapi_device_global/device_global_functional_variables_with_same_name.cpp
tests/extension/oneapi_device_global/device_global_handler_copy_memcpy_overloads.cpp
tests/extension/oneapi_device_global/device_global_queue_array_copy.cpp
tests/extension/oneapi_device_global/device_global_queue_copy.cpp
tests/extension/oneapi_device_global/device_global_queue_memcpy.cpp
tests/reduction/reduction_without_identity_param_common.h
util/type_traits.h

As we already have `value_helper` in `device_global` and in #318, we can move functions for modifying and comparing values to separate file to reuse them in existing tests and future tests.
Depends on:
- #322

Move modify/compare functions into separate file

---

tests/common/type_list.h

They are used to initialize "float" variables and might cause troubles on
devices that don't implement optional support for double precision FP types.

Use single precision FP literals in tests/common/type_list.h

---

ci/dpcpp.filter
tests/host_task/host_task_interop_api.cpp

Per "C.6. Interoperability with the OpenCL API" of the SYCL 2020
specification native type for sycl::buffer is std::vector<cl_mem>.
Update test accordingly.
Signed-off-by: Artur Gainullin <artur.gainullin@intel.com>

Update return type for get_native_mem() per SYCL 2020

---

test_plans/exceptions.asciidoc
tests/exceptions/exception_list.cpp

Tests for [2.5. sycl::exception_list](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/exceptions.asciidoc#25-syclexception_list)
Fix test plan because for empty exception_list begin() and end() should be equal.

Add tests for sycl::exception_list

---

ci/dpcpp.filter
util/math_reference.cpp
util/math_reference.h

The definition of fract in the math_reference utils rely on nextafter. nextafter is however not declared for half until later in the header, so these changes move the definitions of fract to the source file, making the declarations of nextafter visible.
This PR also enables math_builtin_api for DPCPP after being disabled in https://github.com/KhronosGroup/SYCL-CTS/pull/341.

Move definition of fract to resolve nextafter dependency

---

tests/accessor/accessor_common.h
tests/common/section_name_builder.h
tests/common/string_makers.h

Using a builder with fluent interface makes any combination of parameters
explicit and possible. It might be useful for accessor conversion coverage
for example.
The `get_section_name` factory functions are left for backwards compatibility

Add section name builder

---

tests/accessor/accessor_common.h
tests/accessor/host_accessor_properties.h

This removes using of `stub` classes from accessor tests.
As SYCL 2020 `accessors` were not ready at the moment of tests development, stub classes with the same api as `sycl::accessor` were used for the verification that tests can be compiled successfully. There is no need for the stub classes in future lifetime of tests, so they were removed.

Remove stub from accessor tests

---

tests/multi_ptr/multi_ptr_arithmetic_op.h
tests/multi_ptr/multi_ptr_arithmetic_op_core.cpp
tests/multi_ptr/multi_ptr_arithmetic_op_fp16.cpp
tests/multi_ptr/multi_ptr_arithmetic_op_fp64.cpp

The test provides verification for the following arithmetic operators:
- `multi_ptr& operator++(multi_ptr& mp)`
- `multi_ptr operator++(multi_ptr& mp, int)`
- `multi_ptr& operator--(multi_ptr& mp)`
- `multi_ptr operator--(multi_ptr& mp, int)`
- `multi_ptr& operator+=(multi_ptr& lhs, difference_type r)`
- `multi_ptr& operator-=(multi_ptr& lhs, difference_type r)`
- `multi_ptr operator+(const multi_ptr& lhs, difference_type r)`
- `multi_ptr operator-(const multi_ptr& lhs, difference_type r)`
- `reference operator*(const multi_ptr& lhs)`

Add test on multi_ptr arithmetic operators

---

tests/multi_ptr/multi_ptr_prefetch_member.h
tests/multi_ptr/multi_ptr_prefetch_member_core.cpp
tests/multi_ptr/multi_ptr_prefetch_member_fp16.cpp
tests/multi_ptr/multi_ptr_prefetch_member_fp64.cpp

The test provides verification for `multi_ptr::prefetch` member, that it could be called with const `multi_ptr` and it is contains expected value
________
This PR depends on https://github.com/KhronosGroup/SYCL-CTS/pull/346

Add test on multi_ptr prefetch member

---

tests/common/value_operations.h
util/type_traits.h

Overloads of `value_operations::assign` and `value_operations::are_equal` for types with subscript operator uses the `size` member function for iterating the members. However it only checks for the subscript operator. This can cause compile-time errors when using these with types such as `user_struct` that define the subscript operator and a comparison operator but not the `size` member function.
This commit further restricts the aforementioned overloads by requiring the `size` member function. This is done through adding a new type trait for checking a type for the `size` member function, namely `has_size`, and a shortcut trait `has_subscript_and_size` for the conjunction of `has_subscript_operator` and `has_size`.

Require size member function for assign and are_equal

---

tests/multi_ptr/multi_ptr_convert_assignment_ops.h
tests/multi_ptr/multi_ptr_convert_assignment_ops_core.cpp
tests/multi_ptr/multi_ptr_convert_assignment_ops_fp16.cpp
tests/multi_ptr/multi_ptr_convert_assignment_ops_fp64.cpp

The test constructs destination `multi_ptr` with destination `address_space` and
`decorated` types and then calls convert assignment operator from `multi_ptr`
with source `address_space` and `decorated` types. Then verify that destination
`multi_ptr` refers to the target value
________
This PR depends on https://github.com/KhronosGroup/SYCL-CTS/pull/346

Add test on multi_ptr convert assignment operators

---

cmake/FindDPCPP.cmake

We should use dpcpp-cl driver for compatibility with MSVC host compiler.

Fix DPCPP compiler configuration

---

tests/multi_ptr/multi_ptr_comparison_op.h
tests/multi_ptr/multi_ptr_comparison_op_core.cpp
tests/multi_ptr/multi_ptr_comparison_op_fp16.cpp
tests/multi_ptr/multi_ptr_comparison_op_fp64.cpp

The test provides verification for the following comparison operators:
- `multi_ptr& operator==(const multi_ptr&, const multi_ptr&)`
- `multi_ptr operator!=(const multi_ptr&, const multi_ptr&)`
- `multi_ptr& operator<(const multi_ptr&, const multi_ptr&)`
- `multi_ptr operator>(const multi_ptr&, const multi_ptr&)`
- `multi_ptr& operator<=(const multi_ptr&, const multi_ptr&)`
- `multi_ptr& operator>=(const multi_ptr&, const multi_ptr&)`
- `bool operator<=(const multi_ptr& lhs, std::nullptr_t)`
- `bool operator<=(std::nullptr_t, const multi_ptr& rhs)`
- `bool operator>=(const multi_ptr& lhs, std::nullptr_t)`
- `bool operator>=(std::nullptr_t, const multi_ptr& rhs)`
- `bool operator==(const multi_ptr& rhs, std::nullptr_t)`
- `bool operator==(std::nullptr_t, const multi_ptr& rhs)`
- `bool …

Add test on multi_ptr comparison operators

---

tests/common/common.h
tests/group/group_api.cpp
tests/kernel/kernel_info.cpp

SYCL 2020 specification doesn't include kernel::get_work_group_info, thus calls to such methods in the tests are replaced with kernel::get_info

Substitute deprecated feature kernel::get_work_group_info with kernel::get_info

---

tests/accessor/accessor_common.h
tests/accessor/accessor_exceptions.h
tests/exceptions/exceptions_constructors.cpp
tests/optional_kernel_features/kernel_features_common.h

Added `()` to actually trigger execution of lambdas passed to the macro
or otherwise the macro didn't invoke anything. Apparently,
`static_cast<void>` on lambda compiles just fine.

Fix usages of CHECK_THROWS_MATCHES macro

---

.github/workflows/cts_ci.yml

This adds a new job to our CI pipeline that simply summarizes the results of the previous matrix job. This is useful because we can then use this job as a stand-in for the build step in GitHub's branch protection rules.
Currently, all entries in the build matrix need to be enumerated manually, and whenever the version of a SYCL implementation is updated, the rules need to be updated as well:
(Here, DPC++ was updated from caa696f to b3cbda5, so the former never runs and GitHub prevents the PR from being merged).

CI: Summarize matrix build job results in final job

---

.github/workflows/cts_ci.yml
tests/common/common.h
tests/context/context_info.cpp
tests/device/device_info.cpp
tests/event/event.cpp
tests/kernel/kernel_info.cpp
tests/platform/platform_info.cpp
tests/queue/queue_info.cpp

Change information descriptors from enum class elements to structs in
accordance with SYCL 2020. Additionally, drop some outdated descriptors
and bump the DPC++ version.

Switch to struct information descriptors

---

.github/workflows/cts_ci.yml

This adds a new step to our CI pipeline that checks whether all changes made in a PR are formatted according to `clang-format`.
I hand-rolled this functionality since there doesn't seem to be a GitHub action on the marketplace that only checks against a diff (instead always checking all files).
The changes that aren't formatted will be reported on the workflow summary page. You can see an example of what this looks like [here](https://github.com/psalz/SYCL-CTS/actions/runs/3016109194).

CI: Check that changes are formatted according to clang-format

---

docs/README.adoc

This includes a section on how to update the version of a SYCL implementation, so we hopefully avoid running into the same issue over and over again (last seen in #373 / #375).
I've also updated the section regarding the copyright header, as the header used in most files was recently changed in #369. @npmiller I assume that new files (which this section talks about) should not include the copyright for Codeplay - correct?

Flesh out developer documentation on CI and category filters

---

tests/common/common.h
tests/context/context_api.cpp
tests/context/context_constructors.cpp
tests/device/device_api.cpp
tests/device/device_constructors.cpp
tests/device_selector/device_selector_custom.cpp
tests/device_selector/device_selector_predefined.cpp
tests/kernel/kernel_api.cpp
tests/kernel/kernel_info.cpp
tests/platform/platform_api.cpp
tests/queue/queue_api.cpp
tests/queue/queue_constructors.cpp

SYCL 2020 removes the is_host member function from SYCL classes in tandem with removing the requirement that the host device must be available. This commit removes the uses of the is_host member function and fixes the expected behavior of the default device constructor to expect the resulting device to be the same as one constructed with default_selector_v.

Remove use of is_host and fix default device constructor check

---

tests/multi_ptr/multi_ptr_access_members.h
tests/multi_ptr/multi_ptr_accessor_constructor.h
tests/multi_ptr/multi_ptr_arithmetic_op.h
tests/multi_ptr/multi_ptr_arithmetic_op_core.cpp
tests/multi_ptr/multi_ptr_common_assignment_ops.h
tests/multi_ptr/multi_ptr_common_constructors.h
tests/multi_ptr/multi_ptr_comparison_op.h
tests/multi_ptr/multi_ptr_comparison_op_core.cpp
tests/multi_ptr/multi_ptr_convert_assignment_ops.h
tests/multi_ptr/multi_ptr_convert_assignment_ops_core.cpp
tests/multi_ptr/multi_ptr_explicit_conversions.h
tests/multi_ptr/multi_ptr_implicit_conversions.h
tests/multi_ptr/multi_ptr_local_accessor_constructor.h
tests/multi_ptr/multi_ptr_members.h
tests/multi_ptr/multi_ptr_prefetch_member.h
tests/multi_ptr/multi_ptr_prefetch_member_core.cpp

This commit fixes the tests for SYCL 2020 multi_ptr. The following changes are being made:
* Add missing sycl_cts namespaces.
* Add missing typename specifiers.
* Fix uses of constexpr member variables.
* Fix uses of the FAIL macro by getting case description prior to the use of the macro.
* Correctly initialize parameterized result values.
* Remove constant_space from non-legacy multi_ptr tests.
* Fix misspellings of the multi_ptr_common namespace.
* Fix auto reference declarations.
* Move run_test_with_chosen_data_type to after verify_members.
* Fix the handling of constructing multi_ptr with access::address_space::private_space by passing a preconstructed multi_ptr rather than an accessor to the corresponding tests.
* Minor fixes.

Fix SYCL 2020 multi_ptr tests

---

tests/accessor/accessor_iterator_requirement.cpp
util/named_requirement_verification/legacy_bidirectional_iterator.h
util/named_requirement_verification/legacy_forward_iterator.h
util/named_requirement_verification/legacy_random_access_iterator.h

Corresponding DPCPP implementation change: intel/llvm#6692.
This also resolves #388

Fix and enable local_accessor iterator requirements test for DPCPP implementation

---

tests/accessor/local_accessor_access_among_work_items_core.cpp
tests/accessor/local_accessor_access_among_work_items_fp16.cpp
tests/accessor/local_accessor_access_among_work_items_fp64.cpp

Otherwise no tests can be launched due to errors like:
```
$ ./bin/test_accessor
===============================================================================
No tests ran
error: test case "sycl::host_accessor properties. core types", with tags "[accessor]" already defined.
First seen at KhronosGroup/SYCL-CTS/tests/accessor/host_accessor_properties_core.cpp:24
Redefined at KhronosGroup/SYCL-CTS/tests/accessor/local_accessor_access_among_work_items_core.cpp:27
```

Make local_accessor test names unique

---

tests/device/device_constructors.cpp

Currently the device constructor test inadverdently fails if the default-constructed device uses the one selected with the default device selector, while the reverse was the intention. This commit fixes this.

Fix invalid comparison in device_constructors

---

tests/common/common_vec.h

I previously fixed a strict aliasing violation in this function in #383, but that wasn't the only thing wrong with it. Apparently one of the instantiations run during testing has an input type of sycl::vec<sycl::byte, 3> and an output type of sycl::vec<char, 4>. Originally, this would have read an undefined fourth byte from the input array through a reinterpret_casted pointer; after my previous change, it reads the undefined fourth byte via memcpy. This isn't any more undefined, but it seems to more visibly expose the problem in some cases.
I don't know why this test was written to read values past the end of arrays, but it seems like it makes more sense to only test values that are in bounds. To do this, I'm initializing the exp_ptr array to the expected output values and only copying …

Fix out of bounds access in check_as_result

---

tests/event/event.cpp

Not sure what I originally intended to do here, but reference capturing an lvalue parameter of the surrounding function into a host task lambda is a bad idea. Also update the comment on uncaught exceptions in host tasks since that has been clarified in KhronosGroup/SYCL-Docs#246.

Fix reference capture lifetime bug in event tests; update spec comment

---

tests/event/event.cpp

One of the event::wait_and_throw test cases makes the assumption that queue async handlers are somehow propagated to contexts. However, according to [Section 4.13.1.3](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_priorities_of_async_handlers) there are priorities to which async handlers are to be used, where queue is the highest, assuming the runtime can make the association between events and queues. This commit changes the test to follow the aforementioned section, assuming the queues are associated with the events. See also https://github.com/KhronosGroup/SYCL-Docs/issues/299.

Change event::wait_and_throw test case

---

tests/common/type_coverage.h

This commit adds `#include <optional>` to type_coverage.h to fix the potentially unresolvable dependency.

Add missing <optional> include in type_coverage

---

tests/accessor/accessor_common.h
tests/accessor/host_accessor_api_common.h

Function test_accessor_ptr moved from host_accessor_api_common.h to accessor_comon.h so that it can be used in other tests, for example in generic_accessor_api_common.h

Function test_accessor_ptr moved to accessor_comon.h

---

tests/accessor/accessor_common.h

const attribute added to AccT& accessor parameter in get_subscript_overload function

Fix param type in function accessor_tests_common::get_subscript_overload

---

tests/event/event.cpp

Since the destruction of the queue can trigger the exception handler, it needs to happen before any of the other fields of test_exception_handler are destroyed.

Fix test_exception_handler in event tests

---

tests/accessor/accessor_exceptions.h

Fix accessor tests for exceptions and remove check for host_accessor that was erroneously added to sycl::accessor test

Fix accessor_exeptions tests

---

tests/accessor/accessor_common.h
tests/accessor/local_accessor_access_among_work_items.h
tests/accessor/local_accessor_access_among_work_items_core.cpp
tests/accessor/local_accessor_access_among_work_items_fp16.cpp
tests/accessor/local_accessor_access_among_work_items_fp64.cpp
tests/common/value_operations.h

Fix local_accessor_access_among_work_items tests and enable tests.
Changes from https://github.com/KhronosGroup/SYCL-CTS/pull/401 are used.

Fix and enable local_accessor tests for access among work_items.

---

tests/accessor/generic_accessor_api_common.h
tests/accessor/host_accessor_api_common.h
tests/common/value_operations.h

Change test for swap to correct call and correct checks. 
Changes from #401 are used.

Fix tests for swap for sycl::accessor and sycl::host_accessor

---

tests/accessor/generic_accessor_api_common.h
tests/accessor/host_accessor_api_common.h

Add check for unspecified operator[](size_t index) const for non ranged sycl::accessor and sycl::host_accessor
Add check for reference operator[](id<Dimensions> index) const for ranged sycl::accessor and sycl::host_accessor

Cover gaps for subscript operator for accessors

---

tests/accessor/accessor_common.h
tests/accessor/generic_accessor_properties.h
tests/accessor/host_accessor_properties.h

Cover gaps for has_property and get_property methods with sycl::accessor and sycl::host_accessor initialized without no_init property

Cover test gaps for has_property and get_property methods in sycl::accessor and sycl::host_accessor

---

.github/CODEOWNERS

Replace individual accounts with dedicated team. This adds Tom to reviewers.
Add Greg to test plan reviewers.

[CI] Update code review assignment rules

---

CMakeLists.txt
cmake/AddOpenCLProxy.cmake
cmake/AddSYCLExecutable.cmake

This commit moves the OpenCL proxy configuration into a separate cmake file (cmake/AddOpenCLProxy.cmake) and includes it before including AddSYCLExecutable. This is motivated by CMake on Windows failing to configure for DPC++ due to the OpenCL proxy picking Clang as a C compiler due to FindDPCPP overwriting the compilers.
Additionally, since the OpenCL proxy needs options to be correctly configured the CTS options are declared before including both the OpenCL proxy and the SYCL executable.

Configure OpenCL proxy before configuring SYCL executable

---

tests/accessor/accessor_common.h
tests/accessor/accessor_requisite_entire_buffer.cpp
util/sycl_enums.h

According to [4.7.6.8. Ranged accessors](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:accessors.ranged)
> A ranged accessor still creates a requisite for the entire underlying buffer, even for the portions not within the range. For example, if one command writes through a ranged accessor to one region of a buffer and a second command reads through a ranged accessor from a non-overlapping region of the same buffer, the second command must still be scheduled after the first because the requisites for the two commands are on the entire buffer, not on the sub-ranges of the ranged accessors.
This test check this requirement.

Add tests for ranged accessors requirement for the entire buffer

---

tests/common/common_python_vec.py
tests/vector_alias/CMakeLists.txt
tests/vector_alias/generate_vector_alias.py

This PR updates the vector alias tests to use the aliases listed in Section 4.14.2.2 of the SYCL 2020 specification. 
Further, `half` and `double` tests are removed from the list of types to test with if the respective CMake variables are set (this is done using the already implemented `half_double_filter` CMake macro).

Update vector alias tests to use SYCL 2020 aliases

---

tests/common/type_list.h
tests/queue/queue_shortcuts_common.h
tests/queue/queue_shortcuts_explicit.h
tests/queue/queue_shortcuts_explicit_core.cpp
tests/queue/queue_shortcuts_explicit_fp16.cpp
tests/queue/queue_shortcuts_explicit_fp64.cpp
tests/queue/queue_shortcuts_kernel.h
tests/queue/queue_shortcuts_kernel_core.cpp
tests/queue/queue_shortcuts_kernel_fp16.cpp
tests/queue/queue_shortcuts_kernel_fp64.cpp
tests/queue/queue_shortcuts_usm.h
tests/queue/queue_shortcuts_usm_core.cpp
tests/queue/queue_shortcuts_usm_fp16.cpp
tests/queue/queue_shortcuts_usm_fp64.cpp

Adds tests for queue shortcut functions according to test plan #407.
Several parts of the tests are compile-time disabled for ComputeC++ and DPCPP to ensure that the tests build successfully.

Add tests for queue shortcut functions

---

test_plans/queue-shortcut-functions.asciidoc

Adds a test plan for queue shortcut functions as described in Section 4.6.5.2 of the SYCL 2020 specification.

Add test plan for queue shortcut functions

---

test_plans/device-selector.asciidoc

Adds a test plan for device selector as described in Section 4.6.1.1. of the SYCL 2020 specification.
The plan includes an updated version of the inactive (?) PR test plan for aspect selector https://github.com/KhronosGroup/SYCL-CTS/pull/83.
The plan includes the deprecation of the old device selector interface, as suggested in https://github.com/KhronosGroup/SYCL-Docs/issues/290.

Add test plan for device selector

---

test_plans/header-file.asciidoc

Adds a test plan for header files and namespaces as described in Section 4.3 of the SYCL 2020 specification.
As discussed in the workgroup meeting, two versions are proposed: a simple variant that only considers a simple program and an extensive variant which considers all existing tests.
The extensive test has a larger coverage, but also doubles both the time it takes to compile the CTS as well as the time it takes to run it.

Add test plan for header files and namespaces

---

tests/accessor/accessor_common.h
tests/accessor/generic_accessor_api_common.h
tests/accessor/host_accessor_api_common.h
tests/accessor/local_accessor_api_common.h

Add checks for begin(), end(), cbegin(), cend(), rbegin(), rend(), crbegin(), crend() for sycl::accessor, sycl::host_accessor and sycl::local_accessor

Add checks for iterator access functions for accessor

---

tests/buffer/buffer_api_common.h
tests/buffer/buffer_api_core.cpp
tests/buffer/buffer_constructors_common.h
tests/buffer/buffer_constructors_core.cpp
tests/buffer/buffer_storage_core.cpp

This PR implements the [Buffers 2020 plan](https://github.com/KhronosGroup/SYCL-CTS/pull/410)
There is a mild overlap with [Add tests for correct liniarization for accessors](https://github.com/KhronosGroup/SYCL-CTS/pull/427). That test checks whether the iterator interface linearizes as expected, while this test checks whether `get_global_id()` and `get_global_id(int)` align and move data into a buffer according to [3.11.1](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:multi-dim-linearization). (Both tests involve buffers _and_ accessors so I can understand why both teams went and implemented something similar. The approaches to the tests slightly differ.)
We found that the buffer tests lack robust check on their contents. `check_buffer_constructor` checks …

Buffers 2020 update

---

test_plans/runtime_classes.asciidoc

Adds a test plan for the missing information descriptors of the context class as described in Section 4.6.3. of the SYCL 2020 specification and of the device class as described in Section 4.6.4. of the SYCL 2020 specification.

Add test plan for context class and device class

---

test_plans/is_property.asciidoc

Adds a test plan for `is_property` and `is_property_of` as described in Section 4.5.4.1. of the SYCL 2020 specification.

Add test plan for is_property

---

test_plans/stream_class.asciidoc

Adds a test plan for the stream class as described in Section 4.16.1. of the SYCL 2020 specification.

Add test plan for stream class

---

test_plans/device_image.asciidoc

Adds a test plan for the device image class as described in Section 4.11.14. of the SYCL 2020 specification.

Add test plan for device image class

---

tests/common/get_cts_object.h

According to the SYCL 2020 specification, device selectors need not be derived from `sycl::device_selector`. This PR therefore changes the argument `selector` in `get_cts_object::device(...)` from `sycl::device_selector` to a generic template.

Make device selector argument generic

---

tests/scalars/CMakeLists.txt
tests/scalars/scalars_sycl_types.cpp

The tests in `tests/scalars` did not take the CMake variables `SYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS`, `SYCL_CTS_ENABLE_DEPRECATED_FEATURES_TESTS`, and `SYCL_CTS_ENABLE_HALF_TESTS` into account. Now
- the tests for the `sycl::cl_` types are only compiled if `SYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS` is defined,
- the tests using `sycl::byte` are only compiled if `SYCL_CTS_ENABLE_DEPRECATED_FEATURES_TESTS` is defined (since `sycl::byte` is deprecated according to [section 4.14.1 of the SYCL 2020 spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_scalar_data_types)), and
- the tests using `sycl::half` are only compiled if `SYCL_CTS_ENABLE_HALF_TESTS` is defined.

Check if tests for `sycl::cl_`, `sycl::half` and `sycl::byte` should be disabled in scalars tests

---

util/math_reference.h

The min, max, and clamp reference builtins currently assume that the type inside the vector argument and the scalar type of the other argument are the same. However, this is not necessarily the case when using the char vector alias and the char scalar type, as the former uses `int8_t` which may be defined as `signed char` or `unsigned char` which are considered different types from `char` without specified signedness.
This commit relaxes the reference implementations to allow different scalar type to the element type in the passed vector, requiring it is implicitly convertible to the element type.

Fix reference builtins for mixing vectors and scalars

---

test_plans/kernel_bundle.asciidoc

Most of kernel_bundle functionality covered by tests https://github.com/KhronosGroup/SYCL-CTS/tree/SYCL-2020/tests/kernel_bundle.
This is test plan for remaining gaps.

Add test plan for kernel_bundle

---

test_plans/queue_constructors.asciidoc

Test plan to cover gaps in queue constructors tests https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/tests/queue/queue_constructors.cpp.

Create test plan for sycl::queue constructors

---

test_plans/kernels_parameters.asciidoc

This test plan cover [4.12.4. Rules for parameter passing to kernels](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:kernel.parameter.passing) that are not covered in other groups of tests.

Add test plan for parameters passing to kernels

---

test_plans/misc_classes.asciidoc

Adds a test plan for the missing coverage of miscellaneous classes in Section 4.9. "Expressing parallelism through kernels" of the SYCL 2020 specification.

Add test plan for miscellaneous classes

---

tests/common/type_list.h
tests/common/value_operations.h
tests/extension/oneapi_device_global/device_global_api_arrow_operator.cpp
tests/extension/oneapi_device_global/device_global_api_basic.cpp
tests/extension/oneapi_device_global/device_global_api_subscript_operator.cpp
tests/extension/oneapi_device_global/device_global_exceptions.cpp
tests/extension/oneapi_device_global/device_global_functional_define_various_ways.cpp
tests/extension/oneapi_device_global/device_global_functional_kernel_bundle.cpp
tests/extension/oneapi_device_global/device_global_functional_one_kernel.cpp
tests/extension/oneapi_device_global/device_global_functional_pass_pointer.cpp
tests/extension/oneapi_device_global/device_global_functional_several_kernels_one_device.cpp
tests/extension/oneapi_device_global/device_global_functional_spec_constants.cpp
tests/extension/oneapi_device_global/device_global_functional_unique_for_every_device.cpp
tests/extension/oneapi_device_global/device_global_functional_variables_with_same_name.cpp
tests/extension/oneapi_device_global/device_global_handler_copy_memcpy_overloads.cpp
tests/extension/oneapi_device_global/device_global_queue_array_copy.cpp
tests/extension/oneapi_device_global/device_global_queue_copy.cpp
tests/extension/oneapi_device_global/device_global_queue_memcpy.cpp

This commit makes the following changes to device_global related tests:
* Moves arrow_operator_overloaded struct out of no_def_cnstr.
* Fix overloads of assign and are_equal for arrays and add device_global overload.
* Change SYCL_EXT_ONEAPI_PROPERTY_LIST to SYCL_EXT_ONEAPI_PROPERTIES after change to the corresponding extension.
* Add experimental to the namespace of properties and device_global.
* Fix failure reporting.
* Fix use of templates on `value_operations`.
* Prevent the use of different contexts expecting the same device_global.
* Fix uses of compile-time properties after changes to the extension.
* Additional small bugfixes.

Fix device_global tests

---

tests/stream/stream_api.cpp
tests/stream/stream_api_fp16.cpp
tests/stream/stream_api_fp64.cpp
tests/stream/stream_constructors.cpp

Adds tests for the stream class according to #433.

Add tests for stream class

---

test_plans/reduced_feature_set.asciidoc

Adds a test plan to modify the CTS to take into account the full and reduced feature sets of Appendix B of the SYCL 2020 specification. It addresses #365.

Add test plan for feature sets

---

test_plans/reference_semantics.asciidoc

Adds a test plan for the common reference semantics as described in Section 4.5.2. of the SYCL 2020 specification.

Add test plan for common reference semantics

---

tests/common/common.h
tests/context/context_info.cpp
tests/device/device_info.cpp

Implements test plan #448. Note: edits are mostly due to moving the test to the new test framework, and the formatting changes that implies.

Add tests for context class and device class

---

test_plans/kernel_bundle.asciidoc

Fixed leftover max_work_group_size usage.
Added missed cases for  ` has_kernel<typename KernelName>`

Fix test plan for kernel bundle

---

tests/accessor/accessor_iterator_requirement.cpp
util/named_requirement_verification/common.h
util/named_requirement_verification/equality_comparable.h
util/named_requirement_verification/legacy_bidirectional_iterator.h
util/named_requirement_verification/legacy_forward_iterator.h
util/named_requirement_verification/legacy_input_iterator.h
util/named_requirement_verification/legacy_iterator.h
util/named_requirement_verification/legacy_output_iterator.h
util/named_requirement_verification/legacy_random_access_iterator.h

According to [3.13.1. Device copyable](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec::device.copyable) - array<string_view> can only be used if the strings will be placed in USM, so change array<string_view> to array<int>

Change string_view to int in util/named_requirement_verification

---

tests/kernel_bundle/kernels.h
tests/kernel_bundle/sycl_is_compatible.cpp

Add test for sycl::is_compatible according to [2.1. Functions is_compatible](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/kernel_bundle.asciidoc#21-finctions-is_compatible)

Add test for sycl::is_compatible

---

tests/queue/queue_shortcuts_usm.h

The copied values are filled using a customized version of iota to allow for bool type. This ends up filling every element after the 0th with ones, but they are then compared with a sequence of integers. Fix this by casting the expected value to the type being checked.

Fix USM queue shortcuts check for bool

---

tests/atomic_ref/CMakeLists.txt
tests/atomic_ref/atomic_ref_common.h
tests/atomic_ref/atomic_ref_constructors.h
tests/atomic_ref/atomic_ref_constructors_core.cpp
tests/atomic_ref/atomic_ref_constructors_core_atomic64.cpp

Create tests according to 3.1.3. Common constructors section of test plan https://github.com/KhronosGroup/SYCL-CTS/pull/450

Add tests for sycl::atomic_ref constructors

---

tests/accessor/accessor_implicit_conversions_fp16.cpp
tests/accessor/accessor_implicit_conversions_fp64.cpp
tests/marray/marray_alias.cpp
tests/stream/stream_api.cpp

Several CTS option macros are defined in the top-level `CMakeLists.txt` using `add_cts_option`. The documentation for the `add_cts_option` function states: 
```cmake
```
A quick test indicates that this is indeed required. This PR fixes all violations of this rule.
A related note: the macro `SYCL_CTS_COMPILING_WITH_<IMPLEMENTATION>` is only defined when compiling with `IMPLEMENTATION`. There are many occurrences of `#if SYCL_CTS_COMPILING_WITH_<IMPLEMENTATION>` instead of `#ifdef SYCL_CTS_COMPILING_WITH_<IMPLEMENTATION>` but this is not a problem as the expression evaluates to false if it is not defined. Although it is slightly confusing.

Fix conditional inclusion for CTS options

---

tests/multi_ptr/multi_ptr_common.h

Most multi_ptr tests have variants for half and doubles. However, the full conformance type-list for multi_ptr tests include double, potentially causing issues on devices that do not support fp64.
This commit removes double from the list of types to test in the common case.

Remove double from the common type-list for multi_ptr

---

ci/dpcpp.filter

There were some fixes in the past for this test and it passes now.

[CI] Enable multi_ptr test compilation with DPC++

---

tests/multi_ptr/multi_ptr_arithmetic_op.h
tests/multi_ptr/multi_ptr_common.h
tests/multi_ptr/multi_ptr_comparison_op.h

The `multi_ptr` tests may run with `no_def_cnstr` but will fail to compile due to the existence of uninitialized arrays in certain tests requiring the default constructor. This commit adds an initializer for these arrays, skipping initialization for `def_cnstr` as it has no constructor accepting an integer.

Fix array initialization in multi_ptr for no default ctor

---

tests/kernel_bundle/CMakeLists.txt
tests/kernel_bundle/kernel_bundle_api.cpp

Add tests according to [2.2. sycl::kernel_bundle API](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/kernel_bundle.asciidoc#22-syclkernel_bundle-api) of test plan.
The tests for kernel_bundle::has_kernel and kernel_bundle::get_kernel are disabled until implemented.

Add tests for kernel_bundle API

---

test_plans/bit_cast_test_plan.asciidoc

Added a note about skipping invalid test cases, changed tested array size to "2" such that array size can be a multiple of other tested types.

Fix for sycl::bit_cast test plan

---

test_plans/parallel_for_simplifications.asciidoc

In SYCL 2020 the `parallel_for` interface has been simplified in some forms to accept a braced initializer list in place of a range.
It's described in https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_parallel_for_invoke
Test plan to check these overloads.

Add test plan for parallel_for simplifications

---

tests/queue/queue_shortcuts_explicit.h
tests/queue/queue_shortcuts_explicit_core.cpp
tests/queue/queue_shortcuts_explicit_fp16.cpp
tests/queue/queue_shortcuts_explicit_fp64.cpp

This commit enables the queue shortcut tests previously compile-time disabled for DPCPP.

Enable queue shortcut tests for DPCPP

---

test_plans/memcpy2d.asciidoc

Test plan for [sycl_ext_oneapi_memcpy2d](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_memcpy2d.asciidoc) extension.

Add test plan for sycl_ext_oneapi_memcpy2d extension

---

tests/multi_ptr/multi_ptr_legacy_api_common.h
tests/multi_ptr/multi_ptr_legacy_constructors_common.h

Modify tests because in SYCL 2020 `const` types can only be used with `read` access mode accessors and deprecated accessor with target::local can't be `read`, only `read_write` or `atomic`.
Following discussion in https://github.com/KhronosGroup/SYCL-CTS/pull/504

Remove illegal accessor cases in multi_ptr_legacy tests

---

tests/device/device_info.cpp

Enable test case for `sycl::info::device::aspects`
Also added links to issues for remaining disabled test cases

Enable device info test

---

tests/kernel_bundle/kernel_bundle_api.cpp

Enable kernel bundle api tests for `kernel_bundle::has_kernel` member functions.

Enable kernel bundle api tests

---

tests/device_selector/device_selector_aspect.cpp
tests/device_selector/device_selector_predefined.cpp

Enabled the tests however `sycl::aspect::emulated` is still excluded from type coverage  for dpcpp compiler due to absence of implementation. The issue for it is created: [sycl::aspect::emulated is not defined](https://github.com/intel/llvm/issues/8324). Added link to this issue into sources.

Enabled device selector "aspect" end "predefined" tests for dpcpp

---

tests/reduction/reducer_api_core.cpp
tests/reduction/reducer_api_fp16.cpp
tests/reduction/reducer_api_fp64.cpp

Enabled `reducer` api tests. Tests are compiled with dpcpp compiler version [DPC++ daily 2023-02-14](https://github.com/intel/llvm/releases/tag/sycl-nightly%2F20230214). For older compiler version compilation fail is going to happen.

Enable reducer tests for dpcpp compiler

---

tests/stream/stream_semantics.cpp

Added reference to issue, due to which unable to activate check function in stream_semantics.cpp.
Edited storage constructor initializer list, now it works for DPCPP

Stream semantics update

---

tests/optional_kernel_features/kernel_features_common.h
tests/optional_kernel_features/kernel_features_device_has_exceptions.cpp
tests/optional_kernel_features/kernel_features_speculative_compilation.cpp

Fix tests that are using macros to call kernel defined as a lambda.
Added kernel names to speculative compilation test.
Enable tests for DPCPP.

Fix and enable tests for optional kernel features

---

test_plans/any_device_has_all_devices_have.asciidoc

Test plan for traits `any_device_has` and `all_devices_have` that the application can use to query aspects at compilation time
that are described in [4.6.4.3. Device aspects](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:device-aspects) .

Add test plan for any_device_has and all_devices_have

---

tests/kernel/kernel_parameters.cpp

Adding passing by reference to stop T[] decay to pointer since test should check array as kernel parameter.

Fix kernel parameters test for array

---

tests/kernel_bundle/get_kernel_bundle.h
tests/kernel_bundle/kernel_bundle.h
tests/kernel_bundle/sycl_build_verify_kernel_invoked_and_kernel_in_result_bundle.cpp
tests/kernel_bundle/sycl_join_check_kernel_execution.cpp
tests/kernel_bundle/sycl_join_single_kernel_bundle.cpp
tests/kernel_bundle/sycl_link_verify_kernel_invoked_and_kernel_in_result_bundle.cpp
tests/kernel_bundle/use_kernel_bundle.h

Since `get_kernel_bundle` can throw an exception if required kernel is not compatible with any available device, remove kernels with restrictions from link and build tests and add safeguard in use_kernel_bundle tests.

Fix exception with get_kernel_bundle

---

tests/kernel_bundle/has_kernel_bundle_zero_kernels.h

Because `has_kernel_bundle(ctx, {dev}, {k_ids})` should return `true` if `{k_ids}` is empty

Fix check has_kernel_bundle with empty vector

---

tests/reduction/reduction_common.h
tests/reduction/reduction_without_identity_param_core.cpp
tests/reduction/reduction_without_identity_param_fp16.cpp
tests/reduction/reduction_without_identity_param_fp64.cpp

This commit makes the following fixes and adjustments to the reduction tests:
* Adds missing test case combinations of range type and `initialize_to_property` usage for `half` and `double` types.
* Avoid using `initialize_to_property` for identityless test cases.
* Use the correct initial value for expected reduction results with booleans.

Fix and improve reduction testing coverage

---

tests/group_functions/group_barrier.cpp
tests/group_functions/group_broadcast.cpp
tests/group_functions/group_permute.cpp
tests/group_functions/group_permute.h
tests/group_functions/group_permute_fp16.cpp
tests/group_functions/group_permute_fp64.cpp
tests/group_functions/group_reduce.cpp
tests/group_functions/group_reduce_fp16.cpp
tests/group_functions/group_reduce_fp64.cpp
tests/group_functions/group_reduce_fp64_fp16.cpp
tests/group_functions/group_scan.cpp
tests/group_functions/group_scan_fp16.cpp
tests/group_functions/group_scan_fp64.cpp
tests/group_functions/group_scan_fp64_fp16.cpp
tests/group_functions/group_shift.cpp
tests/group_functions/group_shift.h
tests/group_functions/group_shift_fp16.cpp
tests/group_functions/group_shift_fp64.cpp

Removed `group_permute` tests for `sycl::group` according to SYCL2020 specification [4.17.4.3. permute](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_permute)
`1. Constraints: Available only if std::is_same_v<std::decay_t<Group>, sub_group> is true and T is a trivially copyable type.`
Removed `group_shift` tests for `sycl::group` according to SYCL2020 specification [4.17.4.2. shift_left and shift_right](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_shift_left_and_shift_right)
`1. Constraints: Available only if std::is_same_v<std::decay_t<Group>, sub_group> is true and T is a trivially copyable type.`

Fix group_functions tests. Enable group_shift and group_pemute tests.

---

tests/sub_group/sub_group_api.cpp

The test executed kernel function on a big number of work groups using almost every work items available for work group on particular device. Test should check results for all work items in execution range, a buffer is used to keep test results. Added checking of available buffer size on device. Now if required buffer size exceeds available buffer size, work groups size is reduced.

Fix allocation too large buffer for device in sub group test

---

tests/kernel_bundle/device_image_semantics.cpp
tests/kernel_bundle/kernel_bundle_semantics.cpp

To make sure that test are getting correct device_image and kernel_bundle for semantics checks.

Fix device_image_semantics and kernel_bundle_semantics tests

---

tests/group_functions/group_barrier.cpp
tests/group_functions/group_functions_common.h

The work group size is limited for group_barrier test because of out of memory exceptions was being thrown at runtime due to large buffer size which depends on the size of the work group.

Fixed allocation of too large buffer on the device for the group_barrier test

---

CMakeLists.txt
tests/extension/oneapi_memcpy2d/CMakeLists.txt
tests/extension/oneapi_memcpy2d/memcpy2d_common.h
tests/extension/oneapi_memcpy2d/memcpy2d_handler.h
tests/extension/oneapi_memcpy2d/memcpy2d_handler_core.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_handler_exceptions.h
tests/extension/oneapi_memcpy2d/memcpy2d_handler_exceptions_core.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_handler_exceptions_fp16.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_handler_exceptions_fp64.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_handler_fp16.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_handler_fp64.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut.h
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut_core.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut_exceptions.h
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut_exceptions_core.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut_exceptions_fp16.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut_exceptions_fp64.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut_fp16.cpp
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut_fp64.cpp

Add tests for sycl_ext_oneapi_memcpy2 extension according to test plan [sycl_ext_oneapi_memcpy2 extension](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/memcpy2d.asciidoc) .

Add tests for sycl_ext_oneapi_memcpy2d extension.

---

tests/spec_constants/spec_constants_common.h

The specializations constant tests use fill_init_values to initialize reference values that are used as expected values when comparing with the default values of specialization constants. However, the current version of fill_init_values fills the individual elements of vectors and marrays with incrementing values, which do not correspond to the default values used for the specialization constants of these sizes. This commit changes them to use the same initial values.

Fix fill_init_values for spec_constants tests

---

tests/atomic_ref/atomic_ref_T_op_test.h
tests/atomic_ref/atomic_ref_T_op_test_pointers.cpp
tests/atomic_ref/atomic_ref_add_sub_op_all_types_test.h
tests/atomic_ref/atomic_ref_add_sub_op_all_types_test_pointers.cpp
tests/atomic_ref/atomic_ref_assign_op_test.h
tests/atomic_ref/atomic_ref_assign_op_test_pointers.cpp
tests/atomic_ref/atomic_ref_common.h
tests/atomic_ref/atomic_ref_compare_exchange_test.h
tests/atomic_ref/atomic_ref_compare_exchange_test_pointers.cpp
tests/atomic_ref/atomic_ref_constructors.h
tests/atomic_ref/atomic_ref_constructors_pointers.cpp
tests/atomic_ref/atomic_ref_exchange_test.h
tests/atomic_ref/atomic_ref_exchange_test_pointers.cpp
tests/atomic_ref/atomic_ref_fetch_add_sub_all_types_test.h
tests/atomic_ref/atomic_ref_fetch_add_sub_all_types_test_pointers.cpp
tests/atomic_ref/atomic_ref_incr_decr_op_test.h
tests/atomic_ref/atomic_ref_incr_decr_op_test_pointers.cpp
tests/atomic_ref/atomic_ref_is_lock_free_test.h
tests/atomic_ref/atomic_ref_is_lock_free_test_pointers.cpp
tests/atomic_ref/atomic_ref_store_test.h
tests/atomic_ref/atomic_ref_store_test_pointers.cpp

Made separate test cases for pointers types similar to `atomic64` types because size of pointers types can be 64 bits wide and could be not supported by device and to make sure that tests for pointers to `atomic64` types will be tested even if `atomic64` aspect is not supported by device and size of pointers types is less than 64 bits. Tests for pointers types will be performed if size of pointers types is less than 64 bits or if device supports `atomic64` aspect.

Separate test cases for pointers types in atomic_ref tests

---

tests/buffer/buffer_api_common.h
tests/common/get_group_range.h
tests/group_functions/group_barrier.cpp
tests/group_functions/group_broadcast.h
tests/group_functions/group_functions_common.h
tests/group_functions/group_of.h
tests/group_functions/group_permute.h
tests/group_functions/group_reduce.h
tests/group_functions/group_scan.h
tests/group_functions/group_shift.h

Request of work items adjusts to the available capabilities of underlying device in buffer tests.
Function to query available amount of work items moved from tests/group_functions/group_functions_common.h to
tests/common/get_group_range.h.

Fix hardcoded group size in buffer tests

---

test_plans/any_device_has_all_devices_have.asciidoc
tests/device_selector/device_selector_aspect.cpp

Add test for any_device_has and all_devices_have according to [test plan](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/any_device_has_all_devices_have.asciidoc).
Only devices that support the trivial kernel is considered to make sure they are supported by the code that the compiler generates, to align with that clarification https://github.com/KhronosGroup/SYCL-Docs/pull/370

Add tests for any_device_has and all_devices_have

---

ci/dpcpp.filter
tests/exceptions/exceptions_constructors.cpp
tests/exceptions/exceptions_errc_for.cpp

Part of tests are disabled (errc_for and part of constructors tests) until issue  [#182](https://github.com/KhronosGroup/SYCL-Docs/issues/182) , that concerns them is not resolved.

Enabled exceptions tests partially

---

tests/buffer/buffer_deduction_guides.cpp
tests/common/type_list.h
tests/id/id_deduction_guides.cpp
tests/multi_ptr/multi_ptr_deduction_guides.cpp
tests/range/range_deduction_guides.cpp
tests/vector_deduction_guides/CMakeLists.txt
tests/vector_deduction_guides/vec_deduction_guides.cpp

Added tests for `buffer`, `multi_ptr`, `vec`, `range` and `id` constructors deduction guides according to [test plan](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/deduction_guides.asciidoc )

Deduction guides tests implementation

---

tests/common/disabled_for_test_case.h
tests/group_functions/group_scan.cpp
tests/group_functions/group_scan.h
tests/group_functions/group_scan_fp16.cpp
tests/group_functions/group_scan_fp64.cpp
tests/group_functions/group_scan_fp64_fp16.cpp
util/accuracy.h

Re-worked tests to use results of std::exclusive_scan and std::inclusive_scan as reference values.
Refactor code to reduce repeating of similar lines.

Re-worked scan group tests to compare to the results of std::exclusive_scan and std::inclusive_scan

---

tests/kernel_bundle/kernel_bundle_api.cpp

Enabled test for kernel_bundle::get_kernel API due to kernel_bundle::get_kernel is implemented.

Enabled test for kernel_bundle::get_kernel API.

---

tests/function_objects/function_objects_core.cpp
tests/function_objects/function_objects_fp64.cpp

Enable tests for function objects for marray and vector for DPCPP because blocking issue was resolved.

Enable function_objects tests for DPCPP

---

test_plans/weak_object.asciidoc

Test plan for sycl_ext_oneapi_weak_object based on [docs](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_weak_object.asciidocrl)

Add test plan for extention sycl_ext_oneapi_weak_object

---

tests/extension/oneapi_device_global/device_global_api_arrow_operator.cpp
tests/extension/oneapi_device_global/device_global_api_basic.cpp
tests/extension/oneapi_device_global/device_global_api_subscript_operator.cpp
tests/extension/oneapi_device_global/device_global_functional_define_various_ways.cpp
tests/extension/oneapi_device_global/device_global_queue_memcpy.cpp

This commit makes the following fixes to a subset of the device_global tests:
* Change the expected type of the subscript operator to const when the device_global is const.
* Replace use of &= with direct assignment in arrow-operator tests.
* Use value_operation::are_equal to correctly compare array values.
* Add additional template arguments to device_globals in select tests to distinguish different test paths and avoid initialization from the previous runs from bleeding into the latter runs.
* Make generator usage in memcpy tests similar to the structure in the copy variant.
* Instantiate static members of dum_struct to avoid them being considered external symbols. To help remind developers to add more instantiations if more types are added to the tests, the inline modifier has been …

More fixes to device_global tests

---

tests/kernel/kernel_info.cpp

Added checks for exceptions in case of incorrect use of kernel information descriptors.
According to "[4.11.13.2. Kernel information descriptors](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#kernel)" section querying a kernel for information using `info::kernel::num_args` and `info::kernel_device_specific::global_work_size`  as info parameters throws an exception if the kernel type for that query is not valid. Added checks that an exception is thrown for these cases.

To cover gaps in kernel info test

---

test_plans/sub_group_mask.asciidoc

Cover gaps in sub_group_mask extension test plan according to updated version of specification [sycl_ext_oneapi_sub_group_mask](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_sub_group_mask.asciidoc).

Extend sub_group_mask extension test plan

---

tests/marray/marray_operators.h

Added skipping of tests with too big values for left/right shift operations that can lead to undefined behavior.

Fix undefined behavior for shift operations in marray operators tests

---

tests/accessor/accessor_common.h
tests/accessor/generic_accessor_placeholder_constructors.h
tests/accessor/generic_accessor_placeholder_constructors_core.cpp

Cover gaps that only parallel_for_work_group was checked on exception when placeholder accessor is passed as an argument to a command.

Add checks for exception for placeholder accessor for different memory operations

---

tests/reduction/reducer_api_core.cpp

Fix wrong type deduction of reducer class instance by adding std::remove_reference_t

Fix type deduction of reducer class instance in "reducer class" test

---

tests/atomic_fence/atomic_fence.cpp
tests/context/context_info.cpp
tests/device/device_info.cpp
tests/group_functions/group_barrier.cpp

Enable tests with sycl::info::device::atomic_fence_scope_capabilities and sycl::info::device::atomic_fence_order_capabilities for DPCPP because issue https://github.com/intel/llvm/issues/8293 is resolved.

Enable tests with atomic_fence_scope_capabilities and atomic_fence_order_capabilities

---

tests/host_task/host_task_interop_api.cpp
tests/host_task/host_task_invoke_api.cpp

Add expected template parameter for interop functions.
Replace `target::host_buffer` with `sycl::target::host_task`.

Fix host_task tests

---

tests/group_functions/group_reduce.cpp
tests/group_functions/group_reduce_fp16.cpp
tests/group_functions/group_reduce_fp64.cpp

Enable tests for sycl::joint_reduce for DPCPP because issue https://github.com/intel/llvm/issues/8348 is resolved.

Enable tests for sycl::joint_reduce

---

tests/marray/marray_operators.h

Enable tests for marray operators '&&' and '||' for DPCPP because issue https://github.com/intel/llvm/issues/8331 is resolved.

Enable tests for marray operators '&&' and '||'

---

tests/accessor/accessor_requisite_entire_buffer.cpp

Test uses usm_shared_allocations and should be skipped if it's not supported.

Add check for usm support to accessor test that uses usm

---

tests/queue/queue_properties.cpp

Test should be skipped if usm_device_allocations is not supported.

Fix test for queue property in_order

---

tests/common/common_vec.h
tests/vector_api/generate_vector_api.py
tests/vector_constructors/generate_vector_constructors.py
tests/vector_operators/generate_vector_operators.py

Added missed test cases for:
- unary operators -,+
- operator%
- operator DataT()
- noexcept check for size() and byte_size()
- check for swizzled vec for operator[]
- constructor vec(const ArgTN&... args)
- element_type

Add missed test cases for sycl::vec

---

tests/atomic_ref/atomic_ref_T_op_test_atomic64.cpp
tests/atomic_ref/atomic_ref_add_sub_op_all_types_test_atomic64.cpp
tests/atomic_ref/atomic_ref_assign_op_test_atomic64.cpp
tests/atomic_ref/atomic_ref_assign_op_test_core.cpp
tests/atomic_ref/atomic_ref_assign_op_test_pointers.cpp
tests/atomic_ref/atomic_ref_bitwise_op_test_atomic64.cpp
tests/atomic_ref/atomic_ref_common.h
tests/atomic_ref/atomic_ref_compare_exchange_test.h
tests/atomic_ref/atomic_ref_compare_exchange_test_atomic64.cpp
tests/atomic_ref/atomic_ref_constructors.h
tests/atomic_ref/atomic_ref_constructors_atomic64.cpp
tests/atomic_ref/atomic_ref_exchange_test_atomic64.cpp
tests/atomic_ref/atomic_ref_fetch_add_sub_all_types_test_atomic64.cpp
tests/atomic_ref/atomic_ref_fetch_bitwise_test_atomic64.cpp
tests/atomic_ref/atomic_ref_fetch_min_max_test_atomic64.cpp
tests/atomic_ref/atomic_ref_incr_decr_op_test_atomic64.cpp
tests/atomic_ref/atomic_ref_is_lock_free_test_atomic64.cpp
tests/atomic_ref/atomic_ref_static_members_atomic64.cpp
tests/atomic_ref/atomic_ref_store_test_atomic64.cpp

Added additional checking for fp64 support before running tests for type `double` and enabled tests for `operator=()` for dpcpp. Fixed a mistake in `atomic_ref` constructors tests, fixed a typo in `compare_exchange()` test.

Fix atomic ref tests

---

tests/accessor/accessor_common.h

Based on `read_write_acc`, it looks like `read_write_zero_dim_acc` should be assigning `changed_val` to element that is accessed by the given accessor `testing_acc`, and not assigning `changed_val` to a local variable. (Or, just using `testing_acc` as the LHS of the assignment.)

Fix read_write_zero_dim_acc

---

tests/group_functions/group_broadcast.cpp
tests/group_functions/group_broadcast_fp16.cpp
tests/group_functions/group_broadcast_fp64.cpp
tests/group_functions/group_of.cpp
tests/group_functions/group_reduce.cpp
tests/group_functions/group_reduce_fp16.cpp
tests/group_functions/group_reduce_fp64.cpp
tests/group_functions/group_reduce_fp64_fp16.cpp
tests/group_functions/group_scan.cpp
tests/group_functions/group_scan_fp16.cpp
tests/group_functions/group_scan_fp64.cpp
tests/group_functions/group_scan_fp64_fp16.cpp

Global static variable will be initialized at the startup point. "--device" doesn't work in this situation.

Move queue initialization into test body

---

tests/group_functions/group_scan.h

For the `joint_exclusive_scan` and `join_inclusive_scan` overloads with an `init` param of type `T`, the `binary_op(init, *first)` should have type `T`.
[4.17.4.6. `exclusive_scan` and `inclusive_scan`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_exclusive_scan_and_inclusive_scan)

Fix type of operator passed to scan

---

tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut_exceptions.h

To make sure that all submitted commands finished before releasing SECTION resources.

Add waiting on queue for memcpy2d queue shortcut exceptions tests

---

tests/context/context_constructors.cpp

SYCL 2020 spec does not contain `context(platform) and context(platform, async_handler) ` constructors, so they were removed.

Remove sycl::context(platform) constructors

---

test_plans/atomic_ref.asciidoc

Atomic behavior was out of scope for initial atomic_ref test plan. In this PR checks for that are added.

Expand atomic_ref test plan to check atomicity

---

util/math_reference.cpp

Implemented `reference::cross` function for `mfloat3`, `mfloat4`, `mdouble3` and `mdouble4`.

Implement cross function for mfloat and mdouble

---

util/math_reference.h

On MSVC there is an issue with overloads for integer types in <cmath> https://github.com/microsoft/STL/issues/519
I causes errors for max and min for integer types, this workaround let test to get reference value without fails.

Add w/a for missed overloads for int types in <cmath>

---

util/math_reference.h

`remquo` reference was changed from `std::remquo` to `reference_remquol` from `oclmath/reference_math.h` because different behavior of `std` and `sycl` spec.

math_builtin: change remquo reference

---

tests/marray/marray_members.h
tests/marray/marray_operator_helper.h
tests/marray/marray_operators.h

Add checking of ==, !=, <, >, <=, >= operators and member types of marray

Cover gaps for marray

---

tests/kernel/kernel_info.cpp
tests/kernel/kernel_semantics.cpp

Moved check_get_info_param top section that uses built_in kernel because otherwise exception is thrown as expected.
Changed semantics tests to use get_context() instead of info::kernel::num_args because there are not built_in kernels.

Fix info::kernel::num_args usage in kernel tests

---

tests/accessor_legacy/accessor_api_local_common.h
tests/address_space/address_space_common.h
tests/atomic/atomic_api_32.cpp
tests/atomic/atomic_api_64_base.cpp
tests/atomic/atomic_api_64_extended.cpp
tests/atomic/atomic_api_common.h
tests/atomic/atomic_constructors_common.h
tests/multi_ptr/multi_ptr_legacy_api_common.h
tests/multi_ptr/multi_ptr_legacy_constructors_common.h

In SYCL 2020 local accessor must not be used in a SYCL kernel function that is invoked via single_task or via the simple form of parallel_for that takes a range parameter.

Update local accessor usage in legacy tests

---

tests/vector_constructors/generate_vector_constructors.py
tests/vector_operators/generate_vector_operators.py

Added tests for const version of subscript operator type check and operator `vector_t()`

sycl::vec operator[] const and operator vector_t() tests 

---

.clang-format

Do not adapt pointer and reference alignment to the current style.
Just use PointerAlignment parameter unconditionally for consistency.

Format pointer and reference declarations consistently

---

tests/optional_kernel_features/kernel_features_common.h
tests/optional_kernel_features/kernel_features_device_has_exceptions.cpp
tests/optional_kernel_features/kernel_features_reqd_work_group_size.cpp
tests/optional_kernel_features/kernel_features_separate_unit.cpp
tests/optional_kernel_features/kernel_features_speculative_compilation.cpp
tests/optional_kernel_features/kernel_features_sub_group_size_exceptions.cpp

Added kernel functions with accessor to avoid compiler optimisation. Removed single_task call and change parallel_for to use nd_range instead of range for kernels with specicfied group size attributes.

Fix optional_kernel_features tests

---

tests/scalars/scalars_sycl_types.cpp

Due to [SYCL spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_scalar_data_types), `std::numeric_limits` must be specialized for `sycl::half` type.

sycl::half test for numeric limits specialization 

---

tests/kernel_bundle/kernel_bundle_iterator_requirements.cpp

Implemented new tests for `sycl::kernel_bundle` `begin()` and `end()` member functions return type and LegacyForwardIterator requirement.

sycl::kernel_bundle begin() end() tests 

---

tests/kernel_bundle/kernel_bundle_spec_const.cpp
tests/kernel_bundle/use_kernel_bundle_verify_that_kernel_was_invoked.cpp

Tests for `kernel_bundle` and `kernel_handler` `get_specialization_constant()` member function return type.

get_specialization_constant() return type check

---

tests/group_functions/group_reduce.cpp
tests/group_functions/group_reduce_fp16.cpp
tests/group_functions/group_reduce_fp64.cpp
tests/group_functions/group_reduce_fp64_fp16.cpp
tests/group_functions/group_scan.cpp
tests/group_functions/group_scan_fp16.cpp
tests/group_functions/group_scan_fp64.cpp
tests/group_functions/group_scan_fp64_fp16.cpp

Enabled group_functions tests due to fixed product issue [#8341](https://github.com/intel/llvm/issues/8341).

Enabled group_functions tests

---

tests/atomic_ref_stress/CMakeLists.txt
tests/atomic_ref_stress/atomic_ref_stress_atomic64.cpp
tests/atomic_ref_stress/atomic_ref_stress_common.h
tests/atomic_ref_stress/atomic_ref_stress_core.cpp

Add sycl::atomic_ref stress tests according to extension of atomic_ref test plan section [3.2 Stress tests](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/atomic_ref.asciidoc#32-stress-tests), except for section [3.2.5. Atomicity with respect to atomic operations in host code](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/atomic_ref.asciidoc#325-atomicity-with-respect-to-atomic-operations-in-host-code) because it's not clear if std::atomic_ref should be available in SYCL 2020 - https://github.com/KhronosGroup/SYCL-CTS/pull/590#discussion_r1182611654)

Add atomic_ref stress tests

---

tests/multi_ptr/multi_ptr_subscript_op_common.h
tests/multi_ptr/multi_ptr_subscript_op_core.cpp
tests/multi_ptr/multi_ptr_subscript_op_fp16.cpp
tests/multi_ptr/multi_ptr_subscript_op_fp64.cpp

Implemented tests for `multi_ptr::operator[](std::ptrdiff_t)`. Tests contain checks for standard array indexation (0 ... N-1), negative indexation (in this case 0, -1 ... -N+1) and return type

multi_ptr subscript operator tests

---

tests/common/semantics_reference.h
tests/image/image_semantics.cpp
tests/image_accessor/generic_image_accessor_semantics.cpp

This commit fixes the following in the image-related tests:
- Adds the data type template argument to `get_host_access` calls.
- Fixes storage classes for sampled and unsampled image checks.
- Replace calls to non-existant `range` memeber function to existing `get_range`.
- Replaces subscripting on host image accessors to approriate `read` calls.
- Removes a test case trying to call non-const `get_host_access` on a constant copy of an image.
- Adds optional requirements to `common_reference_semantics::check_kernel` to enforce skips for images when unsupported on the selected device.

Fix more image-related tests

---

tests/stream/stream_semantics.cpp

Enabled `bool check(const sycl::stream& stream)` in  `stream_semantics.cpp` due to solved [issue](https://github.com/intel/llvm/issues/8326)

sycl::stream enable semantics tests

---

tests/usm/usm_allocator_constructors.h

Implemented tests for `usm_allocator` constructors with empty property list.

sycl::usm_allocator tests for constructors with property_list

---

tests/scalars/scalars_fixed_width_types.cpp

Due to [spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#subsec:scalartypes) built-in scalar data types with fixed width must have same size on host and device. Added new tests case to check it.

Test for fixed width types sizes on host and device

---

tests/group_functions/group_broadcast.cpp
tests/group_functions/group_reduce.cpp
tests/group_functions/group_reduce.h
tests/group_functions/group_reduce_fp16.cpp
tests/group_functions/group_reduce_fp64.cpp
tests/group_functions/group_reduce_fp64_fp16.cpp
tests/group_functions/group_scan.cpp
tests/group_functions/group_scan_fp16.cpp
tests/group_functions/group_scan_fp64.cpp
tests/group_functions/group_scan_fp64_fp16.cpp

1. Test group reduce functions with all function objects in FULL CONFORMANCE
2. Verify results with std::accumulate
3. Update incorrect usage of `SYCL_CTS_ENABLE_FULL_CONFORMANCE`

Improve group reduce function object coverage and add result verification

---

test_plans/kernel_attributes.asciidoc
test_plans/optional_kernel_features.asciidoc

Added test plan for checks for attributes `work_group_size_hint` and `vec_type_hint` whose effects, if any, are implementation-defined.
Added test cases for `reqd_work_group_size` for different dimensions in optional kernel features test plan.

Update test plan for optional kernel features and add test plan for kernel attributes

---

tests/accessor/generic_accessor_api_common.h
tests/common/common_vec.h

Changed incorrect define SYCL_CTS_TEST_DEPRECATED_FEATURES to SYCL_CTS_ENABLE_DEPRECATED_FEATURES_TESTS in vec and accessor common headers.

Fix incorrect name of define for testing deprecated features

---

tests/scalars/scalars_fixed_width_types.cpp

Changed `int64_t` size from 1 to 8 as expected.

Typo for int64_t check in scalars_fixed_width_types

---

tests/extension/oneapi_sub_group_mask/sub_group_mask_flip_id.cpp

In `before_flip ^ (1 << local_id.get(0))`, usual arithmetic conversions say that the is converted RHS to `unsigned long`. When `local_id.get(0) == 31`, `(1 << local_id.get(0)) == (1 << 31)` is negative, so when converted to unsigned long, due to sign extension, it gets the byte pattern `ff ff ff ff 80 00 00 00`. Change `1` to `1U` so that zero extension happens and the RHS gets the byte pattern `00 00 00 00 80 00 00 00`.

Use left shift on unsigned 1

---

tests/accessor_legacy/accessor_api_buffer_atomic64.cpp
tests/accessor_legacy/accessor_api_buffer_common.h
tests/accessor_legacy/accessor_api_buffer_core.cpp
tests/accessor_legacy/accessor_api_buffer_fp16.cpp
tests/accessor_legacy/accessor_api_buffer_fp64.cpp
tests/accessor_legacy/accessor_types_core.h

Update accessor legacy tests not to use require with empty acc - because it causes exception according to Spec.
Change queue creation to once_per_unit to reduce execution time (similar to https://github.com/KhronosGroup/SYCL-CTS/pull/634).
Remove sycl::cl_* types from these tests because they are not available in SYCL 2020.
Remove target::device from accessor_legacy tests to reduce execution time because accessor with target::device is tested in accessor tests.

Update accessor legacy

---

tests/handler/handler_exceptions.cpp

Add check for exception with handler::require and empty accessor.

Cover gap for handler::require exception

---

tests/buffer/buffer_api_common.h

Added checks for `sycl::buffer` `has_property()/get_property()` member functions with `use_host_ptr` property and basic functionality test with `host_accessor`. Additionally, applied new clang format.

sycl::buffer use_host_ptr() property tests 

---

tests/device/device_info.cpp

Fix return type checks for device::get_info to expect correct types according to  [4.6.4.2. Device information descriptors](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_device_information_descriptors).

Fix return type checks for device::get_info

---

tests/kernel_bundle/sycl_join_kernel_bundles_with_diff_ctx.cpp

Implemented tests for `sycl::join` `errc::invalid` exception matching when passing a vector with different context as [spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_joining_kernel_bundles) says.

sycl::join exception throwing tests

---

tests/h_item/h_item_api.cpp

Added `run_type_check()` function. Results validation was joined with API call checks. Accessor's indices in `run_1d_checks()` function was rewritten to improve readability.

sycl::h_item tests for return type

---

tests/buffer/buffer_api_common.h
tests/queue/queue_properties.cpp

Added checks for `sycl::buffer` and `sycl::queue` `get_property()` member function `errc::invalid` exception when trying to get a property which object does not have.

get_property() exception tests for buffer and queue

---

tests/context/context_constructors.cpp

Added new constructors check for `context` with empty `property_list`.

sycl::context empty property list constructors

---

tests/accessor/accessor_common.h
tests/accessor/accessor_default_values_core.cpp
tests/accessor/accessor_exceptions_core.cpp
tests/accessor/accessor_implicit_conversions_core.cpp
tests/accessor/generic_accessor_api_core.cpp
tests/accessor/generic_accessor_common_buffer_constructors_core.cpp
tests/accessor/generic_accessor_def_constructor_core.cpp
tests/accessor/generic_accessor_linearization_core.cpp
tests/accessor/generic_accessor_placeholder_buffer_constructor_core.cpp
tests/accessor/generic_accessor_placeholder_buffer_constructor_exceptions_core.cpp
tests/accessor/generic_accessor_placeholder_buffer_range_constructor_core.cpp
tests/accessor/generic_accessor_placeholder_buffer_range_constructor_exceptions_core.cpp
tests/accessor/generic_accessor_placeholder_buffer_range_offset_constructor_core.cpp
tests/accessor/generic_accessor_placeholder_buffer_range_offset_constructor_exceptions_core.cpp
tests/accessor/generic_accessor_placeholder_zero_length_buffer_constructor_core.cpp
tests/accessor/generic_accessor_placeholder_zero_length_buffer_range_constructor_core.cpp
tests/accessor/generic_accessor_placeholder_zero_length_buffer_range_offset_constructor_core.cpp
tests/accessor/generic_accessor_properties_core.cpp
tests/accessor/generic_accessor_zero_dim_constructor_core.cpp
tests/accessor/host_accessor_api_core.cpp
tests/accessor/host_accessor_constructors_core.cpp
tests/accessor/host_accessor_linearization_core.cpp
tests/accessor/host_accessor_properties_core.cpp
tests/accessor/local_accessor_access_among_work_items_core.cpp
tests/accessor/local_accessor_api_core.cpp
tests/accessor/local_accessor_constructors_core.cpp
tests/accessor/local_accessor_linearization_core.cpp
tests/common/type_coverage.h

Reduced the accessor test build and run time by moving checks for some types to FULL_CONFORMANCE mode.
In regular mode vec and marray type as accessor data type run only for int and for the reduced number of sizes.

Reduce accessor build and run time

---

tests/address_space/address_space_common.h
tests/atomic/atomic_constructors_common.h
tests/common/async_work_group_copy.h
tests/device_event/device_event_api.cpp
tests/group_functions/group_of.h
tests/group_functions/group_reduce.h
tests/group_functions/group_scan.h
tests/multi_ptr/multi_ptr_access_members.h
tests/multi_ptr/multi_ptr_accessor_constructor.h
tests/multi_ptr/multi_ptr_arithmetic_op.h
tests/multi_ptr/multi_ptr_common_assignment_ops.h
tests/multi_ptr/multi_ptr_common_constructors.h
tests/multi_ptr/multi_ptr_comparison_op.h
tests/multi_ptr/multi_ptr_convert_assignment_ops.h
tests/multi_ptr/multi_ptr_deduction_guides.cpp
tests/multi_ptr/multi_ptr_explicit_conversions.h
tests/multi_ptr/multi_ptr_implicit_conversions.h
tests/multi_ptr/multi_ptr_prefetch_member.h
tests/multi_ptr/multi_ptr_subscript_op_common.h
tests/stream/stream_api.cpp
tests/vector_load_store/generate_vector_load_store.py

Updated tests that are use accessor and multi_ptr - get_pointer returns T* for target::device and get_multi_ptr should be used instead.
Changed accessors that are used in multi_ptr to read_write instead of read to accommodate this Spec change https://github.com/KhronosGroup/SYCL-Docs/pull/405  
Changed async_work_group_copy to take decorated ptr as per Spec.

Update tests usage of accessor providing multi_ptr

---

tests/math_builtin_api/math_builtin.h
tests/math_builtin_api/modules/test_generator.py

In math_builtin tests, in check_function_multi_ptr_local changed single_task to parallel_for due to restriction of using accessor with target = local inside single_task.
Also changed deprecated accessor with target = local to local_accessor.

Fixed deprecated accessor with target = local inside handler.single_task in math_builtin tests

---

tests/kernel_bundle/sycl_join_kernel_bundles_with_diff_ctx.cpp

To make sure that test are getting correct kernel_bundles with supported kernels.

Fix test for sycl::join with diff contexts

---

tests/accessor/accessor_common.h

`res_acc` is accessed through subscript operator under certain conditions, so it should not be a placeholder.

Fix generic_accessor_placeholder_buffer_constructor

---

tests/reduction/reduction_common.h

In a case of `reduction_without_identity_param_fp16`, a reduction with a half multiplication functor using the "each_work_item_twice" kernel is invoked. The result should be the product of the list `0, 0, 1, 1, 2, 2, ..., 8, 8, 9, 9`. Depending on how the product is computed, the result can either be `0` (e.g. left to right multiplication) or `nan` (e.g. right to left will overflow for half and then compute `inf*0=nan`). Both of these should be allowed as the SYCL spec does specify the order the the reduction must be computed. However, the assertion checks the reduction result against result from `std::accumulate` (a left to right reduction), so there is a potential for a discrepancy (as is the case for DPC++). The `number_iterations` variable determines the input range used in the …

Reduce number of iterations in reduction tests

---

tests/extension/oneapi_memcpy2d/memcpy2d_handler.h
tests/extension/oneapi_memcpy2d/memcpy2d_handler_exceptions.h
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut.h
tests/extension/oneapi_memcpy2d/memcpy2d_queue_shortcut_exceptions.h

Added missed queue.wait_and_throw() call to avoid memory corruption.

Fix memcpy2d tests

---

tests/property/property_api.cpp

According to the [SYCL 2020 specification](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_unsampled_image_accessors) the access mode of `unsampled_image_accessor` must either be `read` or `write`. This commit fixes the use of the `read_write` access mode in one such accessor.

Fix invalid access mode in unsampled_image_accessor

---

test_plans/use_pinned_host_memory.asciidoc

Test plan for `buffer` property extension described [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_use_pinned_host_memory_property.asciidoc)

use_pinned_host_memory extension test plan

---

test_plans/oneapi_discard_queue_events.asciidoc

Added test plan according to the [spec](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_discard_queue_events.asciidoc).

Test plan for "discard queue events" oneapi extension

---

.github/workflows/cts_ci.yml
docker/dpcpp/Dockerfile
docker/dpcpp/configure.sh

intel/llvm project provides daily built docker images with pre-built
DPC++ compiler. Using this image saves us time to build the compiler
from sources.

Base DPC++ docker container on the image from intel/llvm.

---

test_plans/oneapi_queue_priority.asciidoc

Add test plan according to the [spec](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_queue_priority.asciidoc)

Test plan for oneapi extension queue priority

---

tests/sycl_external/CMakeLists.txt
tests/sycl_external/sycl_external.cpp
tests/sycl_external/sycl_external_separate_unit.cpp

Add tests for [SYCL_EXTERNAL](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#subsec:syclexternal) according to [test plan](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/sycl_external.asciidoc).

Add tests for SYCL_EXTERNAL

---

tests/accessor/accessor_common.h

`res_acc` is accessed through subscript operator under certain conditions, so it should not be a placeholder.

Fix placeholder_zero_length_buffer_constructor

---

test_plans/oneapi_queue_empty.asciidoc

Added test plan according to the [spec](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_queue_empty.asciidoc).

Test plan for oneapi "queue empty" extension

---

tests/optional_kernel_features/kernel_features_common.h

Returned lost attribute to kernel lambda with non decorated dummy function.

Fix optional_kernel_features test

---

test_plans/oneapi_local_memory.asciidoc

Add test plan for `sycl_ext_oneapi_local_memory` extension according to the [extension specification](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_local_memory.asciidoc)

Test plan for oneapi extension local memory

---

tests/common/range_index_space_id.h
tests/group/group_members.cpp
tests/h_item/h_item_members.cpp
tests/id/id.cpp
tests/item/item_members.cpp
tests/nd_item/nd_item_members.cpp
tests/nd_range/nd_range_members.cpp
tests/range/range_members.cpp
tests/sub_group/sub_group_members.cpp

Covered gap with checks for 'dimensions' member of ranges/id-like types according to [4.9.1. Ranges and index space identifiers](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#ranges-identifiers) and PR [#351](https://github.com/KhronosGroup/SYCL-Docs/pull/351).

Add checks for ranges/id-like types member 'dimensions'

---

tests/group_functions/group_functions_common.h
tests/group_functions/group_reduce.h
tests/group_functions/group_scan.h
tests/reduction/identity_helper.h
tests/reduction/reducer_api.h
util/type_traits.h

Added checks for rest operations for scan tests, some fixes in reduce tests (added guards to run tests with valid combinations of tested type and operation, e.g. bitwise operations can't be tested with float types, fixed the type of input data in `init_reduce_over_group()` function)

Cover gaps for scan

---

tests/accessor/accessor_common.h

Value checks for local_accessor<const T, Dim> disabled due to the impossibility of passing data to such local_accessor.

Fix checks for local_accessor ctors

---

tests/atomic_ref_stress/atomic_ref_stress_atomic64.cpp
tests/atomic_ref_stress/atomic_ref_stress_common.h
tests/atomic_ref_stress/atomic_ref_stress_core.cpp

Add sycl::atomic_ref stress tests according to  test plan section [3.2.5. Atomicity with respect to atomic operations in host code](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/atomic_ref.asciidoc#325-atomicity-with-respect-to-atomic-operations-in-host-code).

Add tests sycl::atomic_ref atomicity with respect to host code 

---

tests/accessor/host_accessor_api_common.h

Fixed comparison of value on accessor start with value, according to accessor offset.

Fix check for host accessor with offset

---

cmake/FindDPCPP.cmake

This commit adds the -fsycl-link-huge-device-code to the linker flags for DPC++. This allows the linking of very large device-code object files, which can be produced by select categories in the CTS in full conformance mode. This flag is currently not supported on Windows.

Add -fsycl-link-huge-device-code linker flags for DPCPP

---

tests/kernel_bundle/sycl_is_compatible.cpp

max_work_item_sizes info query returns range now, but not id. Range type isn't convertible to size_t.
https://github.com/intel/llvm/pull/9946

Fix sycl_is_compatible.cpp

---

tests/item/item_api.cpp
tests/item/item_constructors.cpp

Added `operator size_t()` and `operator item<Dimensions, true>()` tests for `item`.

sycl::item missing operators tests

---

tests/atomic_ref/atomic_ref_common.h

Because of type long can have size greater than 32 bits added checking of its size. Now this type is included in `atomic64` type pack if its size greater than 4 bytes.

Fix type pack creation for atomic_ref tests

---

tests/is_device_copyable/CMakeLists.txt
tests/is_device_copyable/is_device_copyable_api.cpp

Created tests for `sycl::is_device_copyable` type trait according to [test plan](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/is_device_copyable.asciidoc)

sycl::is_device_copyable tests implementation

---

tests/group_functions/group_reduce.h

This avoids meaningless overflowed results for reducing over smaller types (e.g. `char`).
Signed-off-by: Yilong Guo <yilong.guo@intel.com>
Co-authored-by: Jie Zhang <jiez.zhang@intel.com>

[group_functions] Reduce test size to avoid overflow

---

test_plans/intel_queue_index.asciidoc

Add test plan according to the [spec](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_queue_index.asciidoc)

Test plan for intel extension queue index

---

tests/kernel_bundle/use_kernel_bundle.h
tests/kernel_bundle/use_kernel_bundle_invoke_kernel_with_incompat_dev_no_second_queue.cpp
tests/kernel_bundle/use_kernel_bundle_invoke_kernel_with_incompat_dev_with_second_queue.cpp

Updated the tests for `use_kernel_bundle()` with incompatible device. Added check if exception with error code `kernel_not_supported` is thrown in case of `use_kernel_bundle()` call inside command group with incompatible device of secondary queue.

Cover gaps for use_kernel_bunde()

---

tests/optional_kernel_features/kernel_features_common.h
tests/optional_kernel_features/kernel_features_reqd_work_group_size.cpp
tests/optional_kernel_features/kernel_features_speculative_compilation.cpp
tests/optional_kernel_features/kernel_features_sub_group_size_exceptions.cpp

Added checks for reqd_work_group_size according to updated test plan [2.2. Runtime exception if device doesn’t support required work group size](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/optional_kernel_features.asciidoc#22-runtime-exception-if-device-doesnt-support-required-work-group-size).
Fix tests to use correct attribute.

Add checks for reqd_work_group_size for different dimensions and fix test

---

tests/accessor/accessor_common.h

Fix zero sized range as kernel parameter in accessor tests.

Fix zero sized range as kernel parameter

---

tests/handler/handler_copy_common.h
tests/handler/handler_copy_core.cpp

Added checking of `copy(acc, acc)` operation with source accessor which target is `constant_buffer`.
Added checking if exception is thrown on `copy(acc, acc)` operation in case of destination memory size is too small.

Cover gaps for explicit memory operation copy(acc, acc)

---

CMakeLists.txt
tests/extension/oneapi_discard_queue_events/CMakeLists.txt
tests/extension/oneapi_discard_queue_events/discard_queue_events_tests.cpp

Added tests according to the [test plan](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/oneapi_discard_queue_events.asciidoc).

Test for oneapi extension "discard queue events"

---

tests/accessor/generic_accessor_api_common.h
tests/accessor/local_accessor_api_common.h

This commit makes the following accessor test changes:
* Fixes the expected first and last element of an accessor with offset.
* Removes the exclusion of 0-dimensional accessor from the swap test.
* Fixes the expected first value in the iterator tests for 0-dimensional local_accessor.

Fix faulty accessor tests

---

tests/accessor/generic_accessor_api_common.h

The SYCL specification states that get_pointer on an accessor or local_accessor can only be called inside a command. This commit fixes a use of get_pointer outside a command. Additionally it moves the surrounding code out of the encapsulating submission.

Remove invalid use of get_pointer on placeholder accessor

---

tests/common/type_coverage.h
tests/extension/oneapi_sub_group_mask/sub_group_mask_all.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_any.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_common.h
tests/extension/oneapi_sub_group_mask/sub_group_mask_constructors.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_count.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_extract_bits.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_find_high.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_find_low.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_flip_api.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_flip_id.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_insert_bits.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_none.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_reference.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_reset_api.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_reset_high.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_reset_id.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_reset_low.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_set_api.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_set_id.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_size.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_subscript.cpp
tests/extension/oneapi_sub_group_mask/sub_group_mask_test.cpp

Cover gaps in oneapi_sub_group_mask extension according to  [oneapi_ext_sub_group_mask test plan](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/sub_group_mask.asciidoc) test plan and refactor existing tests.

Cover gaps in oneapi_sub_group_mask extension

---

test_plans/mem_channel.asciidoc

Created test plan for [mem_channel](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_mem_channel_property.asciidoc) extension.

mem_channel extension test plan

---

test_plans/bfloat16.asciidoc

Addresses a review comment in the test implementation (#738).

Avoid some bit_cast in bfloat16 test plan

---

CMakeLists.txt
tests/extension/oneapi_bfloat16/CMakeLists.txt
tests/extension/oneapi_bfloat16/bfloat16_api.cpp

Created tests for [bfloat16](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_bfloat16.asciidoc) extension

Tests for oneAPI bfloat16 extension

---

docker/dpcpp/Dockerfile

I just randomly noticed that CI run times are going absolutely through the roof again, with runs taking anywhere from [FOUR](https://github.com/KhronosGroup/SYCL-CTS/actions/runs/5527166953) to [SIX](https://github.com/KhronosGroup/SYCL-CTS/actions/runs/5513029710) hours. While not really addressing the root problem, our fix for this so far was to use `ccache`, which has worked rather well.
It looks like `ccache` was lost in the switch to the DPC++ nightly containers (#712), so with this I'm bringing it back.
Note: I haven't tested this, so after the cache has been primed by the CI run for this PR we'll have to launch a second run to see if it actually works.
---
Side node / reminder: we generate a [detailed report](https://github.com/KhronosGroup/SYCL-CTS/suites/14194910821/artifacts/7964 …

CI: Bring back ccache for DPC++

---

tests/accessor/local_accessor_api_common.h

* The test should expect the return type of the deprecated `local_accessor::get_pointer()` which is `multi_ptr<T, local_space, legacy>`, while it  expected `std::add_pointer<T>` which is the return type of the function in according to SYCL-2020 specifications.

Fix check on expected return type of local_accessor::get_pointer()

---

tests/h_item/h_item_members.cpp
tests/id/id.cpp
tests/item/item_members.cpp
tests/nd_item/nd_item_members.cpp
tests/nd_range/nd_range_members.cpp
tests/range/range_members.cpp

This commit enables a number of test cases previously disabled for DPC++ due to missing `dimensions` member in `id`, `range`, `nd_range`, `h_item`, `item`, and `nd_item`.

Enable dimension item/id/range dimension checks for DPC++

---

tests/group_functions/group_barrier.cpp

Otherwise, the initialization performed by the following code may change the result buffer.
Signed-off-by: Yilong Guo <yilong.guo@intel.com>

[group_functions] Insert barrier after each validation

---

tests/accessor/generic_accessor_api_common.h

Reverts KhronosGroup/SYCL-CTS#757
From https://github.com/KhronosGroup/SYCL-CTS/pull/757#issuecomment-1653958589.
> `res_acc` is being changed in `test_accessor_ptr_device`, so this change is dismissing the results from that function.

Revert "Fix bool check on generic accessor api"

---

tests/accessor/accessor_common.h
tests/accessor/generic_accessor_api_common.h
tests/accessor/local_accessor_api_common.h

According to recent changes in SYCL2020 spec (https://github.com/KhronosGroup/SYCL-Docs/pull/432), update expected return types for `get_pointer()` in different cases.

Fix expected return type for get_pointer().

---

tests/accessor_legacy/accessor_api_utility.h
tests/common/cts_selector.h
tests/common/once_per_unit.h
tests/exceptions/exceptions.h

This should suppress the warning about defining unused functions.

Add inline to function definitions in headers

---

tests/accessor/accessor_common.h

Following the resolution of
https://github.com/KhronosGroup/SYCL-Docs/issues/408 with https://github.com/KhronosGroup/SYCL-Docs/pull/434 DPC++ has been changed to not throw for empty accessors. As such, the test cases using check_zero_length_buffer_constructor can now be enabled.

Enable check_zero_length_buffer_constructor for DPCPP

---

tests/accessor/host_accessor_api_common.h

Reduce the numbers, so linear_index doesn't exceed CHAR_MAX. Otherwise the test fails here with the char type:
CHECK(value_operations::are_equal(acc_ref1, linear_index));
As acc_ref1 contains corrupted by the overflow value.

Fix host_accessor_api_core test

---

tests/handler/handler_invoke_parallel_for_with_range_size_t.cpp

This patch should be merged after 
- https://github.com/intel/llvm/pull/10660 
is merged.

Enable handler_invoke_parallel_for_with_range_size_t for DPCPP

---

tests/kernel/kernel_attributes_vec_hint.cpp

This commit enables the vec_hint attribute tests for DPC++.

Enable vec_hint test for DPCPP

---

tests/kernel_bundle/get_kernel_bundle.h

1. Device images may already be filtered according to the device before the Selector call, so there is no gurantee that the Selector will meet all kernels. Need to check the kernel for compatibility to see if it was already filtered out.
2. Also need to check for compatibility before calling get_kernel_bundle for a certain kernel. It may lead to an exception if the kernel is not compatible.

Fix kernel_bundle bugs

---

tests/optional_kernel_features/kernel_features_common.h

In these functions, the current usage of these features when they are `half` or `double` can be optimized out (ultimately, the kernel always stores `false` to the accessor), which can lead tests in `kernel_features_device_has_exceptions.cpp` to expect an exception to be thrown when one will not be thrown.

Use accessor and feature more in optional kernel features tests

---

tests/extension/oneapi_bfloat16/bfloat16_api.cpp

This patch fixes the following compfail in oneapi_bfloat16 test:
```
error: no matching function for call to 'bit_cast'
bfloat16 bf_min = sycl::bit_cast<bfloat16>(0b0000000010000000);
^~~~~~~~~~~~~~~~~~~~~~~~
```

Fix oneapi_bfloat16 compfail

---

tests/common/common_vec.h

Disable `check_vector_as` comparisons for cases where the size of the elements differs after conversion. This matches the restriction described in KhronosGroup/SYCL-Docs#447.

Disable invalid `vec::as` test cases

---

ci/dpcpp.filter

This enables compilation of all tests with DPC++ in CI.

[CI] Empty DPC++ filter

---

tests/group_functions/group_joint_reduce.cpp
tests/group_functions/group_joint_reduce_fp16.cpp
tests/group_functions/group_joint_reduce_fp64.cpp
tests/group_functions/group_joint_reduce_fp64_fp16.cpp
tests/group_functions/group_joint_scan.cpp
tests/group_functions/group_joint_scan_fp16.cpp
tests/group_functions/group_joint_scan_fp64.cpp
tests/group_functions/group_joint_scan_fp64_fp16.cpp
tests/group_functions/group_reduce_over_group.cpp
tests/group_functions/group_reduce_over_group_fp16.cpp
tests/group_functions/group_reduce_over_group_fp64.cpp
tests/group_functions/group_reduce_over_group_fp64_fp16.cpp
tests/group_functions/group_scan.h
tests/group_functions/group_scan_over_group.cpp
tests/group_functions/group_scan_over_group_fp16.cpp
tests/group_functions/group_scan_over_group_fp64.cpp
tests/group_functions/group_scan_over_group_fp64_fp16.cpp

In an attempt to reduce the compile-time overhead of the group_scan and group_reduce tests, this commit splits them by joint_* and *_over_group variants.
Additionally, it refactors the structure of the scan tests to avoid excessive template instantiations, leaving slightly more for runtime execution.

Refactor group_scan and group_reduce tests to improve compile time

---

tests/accessor_legacy/accessor_api_buffer_common.h

In
https://github.com/KhronosGroup/SYCL-CTS/blob/2c00dc28a7ecd29a0b4422407e35ccdaec976c71/tests/accessor_legacy/accessor_api_buffer_common.h#L1186-L1189 and
https://github.com/KhronosGroup/SYCL-CTS/blob/2c00dc28a7ecd29a0b4422407e35ccdaec976c71/tests/accessor_legacy/accessor_api_buffer_common.h#L1214-L1219 we create a buffer with {1, 4, 2} dimensions. Later in 
https://github.com/KhronosGroup/SYCL-CTS/blob/2c00dc28a7ecd29a0b4422407e35ccdaec976c71/tests/accessor_legacy/accessor_api_buffer_common.h#L65
we create an accessor with range {0, 2, 1} which is empty. As such, any tests that try to verify its content or make any check against its `get_pointer()` are invalid. Fix that by adjusting accessor's range so it is not empty.

Avoid empty accessors in tests/accessor_legacy/accessor_api_buffer_common.h

---

tests/group_functions/group_scan.h

Two issues were fixed:
- incorrect (static, not dynamic) index used in `joint_*` functions validation
- incorrectly computed indicies into results buffer, which caused validation only of 3/4th of the results

Fix results validation in group_scan tests

---

tests/common/common_vec.h

The convert function checks would assume a certain set of values to convert and would construct invalid reference results if the values are not in that set. This patch fixes this by instead using the reference math functions to do the proper rounding.

Fix convert function checks

---

tests/multi_ptr/multi_ptr_deduction_guides.cpp

This commit fixes a mistake in the multi_ptr_deduction_guide test causing it to not correctly instantiate the accessor.

Fix instantiation of accessor in multi_ptr_deduction_guide

---

tests/group_functions/group_scan.h

Prior to this PR, we were misusing types, having `InPtr` where we should be using `OutPtr` and the other way around, causing multiple validation issues and even segmentation faults. Also, this PR fixes an out of range access.

Use correct types in JointScanDataStruct and fix out of range error.

---

tests/group_functions/group_of.h

When the sub-group size is 1, the 'one_true' and 'some_true' predicates return true, so we should instead be checking that `all_of` returns true.

Fix incorrect all_of validation when sub-group size is 1

---

tests/optional_kernel_features/kernel_features_speculative_compilation.cpp

`run_separate_lambda_nd_range` invokes a `parallel_for` over an `nd_range` using the `separate_lambda_nd_item_arg` argument. However, there were some places in `kernel_features_speculative_compilation.cpp` that called `run_separate_lambda_nd_range` with a lambda with an item argument, which is incorrect.

Pass lambda with nd_item arg to run_separate_lambda_nd_range

---

tests/accessor_legacy/accessor_api_common_buffer_local.h
tests/accessor_legacy/accessor_api_utility.h
tests/optional_kernel_features/kernel_features_speculative_compilation.cpp

This commit fixes the use of item and id arguments in nd_range parallel_for kernels.

Fix invalid argument for nd-range kernels

---

tests/group_functions/group_scan.h

Check that the maximum value of `T` is large enough to store the results of the scan functions. This check prevents overflow for small types. Also, remove the largest `check_scan` test case.

Prevent signed integer overflow in `check_scan_over_group`

---

tests/kernel/kernel_info.cpp

If the device doesn't report any valid sub-group sizes, it's better to halt the test than to segfault when dereferencing `std::max_element`.

Fix potential segfault in kernel_info test

---

tests/common/common_vec.h

1. According to https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#swizzled-vec-class __swizzled_vec__ shouldn't escape the expression it was constructed in. So I refactored the test to create __swizzled_vec__ and then call a required function in the same place.
2. There is a bug in check_vector_convert() Since check_vector_convert_modes() accepts sycl::vec argument, we don't really test convert() method for __swizzled_vec__ as it's impicitly converted to sycl::vec. Also refactored this part to fix it.

Fix vector_api test

---

tests/vector_api/generate_vector_api.py

https://github.com/KhronosGroup/SYCL-Docs/pull/448 limited sycl::vec alignment to 64 bytes

Apply sycl::vec 64 bytes limit

---

tests/accessor/generic_accessor_api_common.h
tests/accessor/host_accessor_api_common.h
tests/common/get_group_range.h
tests/kernel/kernel_attributes_wg_hint.cpp
tests/optional_kernel_features/kernel_features_reqd_work_group_size.cpp

These tests were all relying on `<cmath>` being included by `<sycl/sycl.hpp>`, which cannot be relied upon.
See https://github.com/intel/llvm/commit/9bbbc77 for a change which exposed this problem when building with DPC++.

Explicitly include <cmath> where required

---

tests/accessor/accessor_exceptions.h

The "exception for local accessor" test previously used a USM shared memory pointer as a write destination to produce a side effect. However, since not all devices support Shared USM and it doesn't seem to be a requirement of the test, it has been replaced with a "normal" accessor.

Change local accessor exception test to not use USM

---

test_plans/auto_local_range.asciidoc

This PR adds a test plan for the [`auto_local_range`](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_auto_local_range.asciidoc) extension.

Create test plan for `auto_local_range` extension

---

tests/usm/usm_api.h

In the test usm_api_copy_queue_multiple_events, it takes up 
about 800KB of stack memory. With default limit of 1MB stack 
memory in Windows, the program will failed due to stack overflow.

[NFC] Avoid using too much stack memory

---

run_conformance_tests.py

This commit makes the run_conformance_tests.py script use the implementation name given in its related argument as the SYCL_IMPLEMENTATION argument in the CMake configuration.

Use implementation name for configuration in conformance script

---

tests/usm/usm_api.h

Different USM allocation types are locked behind different aspects. The USM tests account for this by skipping the test if the aspect for the destination allocation is not present. However, two tests (copy and memcpy) have an allocation for the source memory, which is not checked.
This change adds a "supports_device" method to the USM tests that takes a queue and returns whether the test supports that queue. For the copy and memcpy tests, this checks that the source allocation is supported by the device. All other tests just return true.
(For the avoidance of doubt; I'm employed by Codeplay, a subsidiary of Intel)

Improve support detection for USM copy tests

---

tests/common/common_vec.h

Turned it into a more generic function template to avoid explicitly specializing it for every vector size.

[NFC] Refactor `check_lo_hi_odd_even` helper

---

tests/extension/oneapi_bfloat16/bfloat16_api.cpp

This commit adds an include of cmath to the tests/extension/oneapi_bfloat16/bfloat16_api.cpp test to allow the use of std math functions.

Add cmath include to oneapi_bfloat16 test

---

tests/common/value_operations.h

`assert` is not guaranteed to be supported by a SYCL implementation and therefore we can't really use it in CTS.
Removed `assert` uses from velue operations helpers, which are used by some of CTS tests (`accessor`, `vector_swizzles`).

Do not use `assert` in device code

---

tests/common/vector_swizzle_assignment.template
tests/vector_swizzle_assignment/CMakeLists.txt

Refactored test templates to avoid defining `SYCL_SIMPLE_SWIZZLES` for most of `vector_*` tests. Even though simple swizzles are not used by those tests, defining the macro still increases amount of input source code a compiler should look through, thus unnecessary increasing compilation time.

Improve vector tests compilation time

---

tests/atomic_ref/atomic_ref_add_sub_op_all_types_test_core.cpp
tests/atomic_ref/atomic_ref_add_sub_op_all_types_test_pointers.cpp
tests/atomic_ref/atomic_ref_assign_op_test_core.cpp
tests/atomic_ref/atomic_ref_assign_op_test_pointers.cpp
tests/atomic_ref/atomic_ref_bitwise_op_test_core.cpp
tests/atomic_ref/atomic_ref_compare_exchange_test_core.cpp
tests/atomic_ref/atomic_ref_compare_exchange_test_pointers.cpp
tests/atomic_ref/atomic_ref_exchange_test_core.cpp
tests/atomic_ref/atomic_ref_exchange_test_pointers.cpp
tests/atomic_ref/atomic_ref_fetch_add_sub_all_types_test_core.cpp
tests/atomic_ref/atomic_ref_fetch_add_sub_all_types_test_pointers.cpp
tests/atomic_ref/atomic_ref_fetch_bitwise_test_core.cpp
tests/atomic_ref/atomic_ref_fetch_min_max_test_core.cpp
tests/atomic_ref/atomic_ref_incr_decr_op_test_core.cpp
tests/atomic_ref/atomic_ref_incr_decr_op_test_pointers.cpp

I'm assuming these are typos.
There are some inconsistencies about how we style the test names for ostensibly the same operations: see tests covering one operator (`atomic_ref::operator`) vs those that cover two (`atomic_ref operator/operator` - no colons). I see why it was done, but the inconsistency is noticeable.

Fix typos in atomic_ref test names

---

tests/extension/oneapi_sub_group_mask/sub_group_mask_constructors.cpp

`&value + shift` is invalid.
It's assumed to get the address of &value + (N = shift) bytes.
But we're actually getting &value + sizeof(value) * shift and running out of buffer.

Fix sub_group_mask_constructors

---

tests/CMakeLists.txt

test_all is a special test executable including the tests from all other test executables. For the sake of running the conformance script, it is both a redundant and a resource heavy task to include test_all as part of the run. To avoid excessive work, this commit adds a new target "test_conformance" that includes all test executables except test_all.

Add test_conformance target with all tests except test_all

---

tests/usm/usm_api.h

Since the std::vector\<bool\> type does not have a data() member function,
Using vector<unsigned char> instead of vector<bool>.

Using vector<unsigned char> instead of vector<bool>

---

tests/common/common_python_vec.py
tests/common/vector_swizzles.template

This is a partial refactoring of the test, which aims to:
- reduce kernel size, which allows to speed up JIT compilation and therefore test execution
- improve error reporting from the test, by returning more than just a single `bool` value for all of the checks performed by kernels
Main changes:
- introduced new template for swizzle test kernels
- results of "per-element" `.swizzle<s0, s1, ..., sN>()` operations are now reported back to host where their verification happens instead of doing so on device side

Refactor `vector_swizzles` test

---

tests/group_functions/group_of.h

As discovered/discussed in
https://github.com/KhronosGroup/SYCL-CTS/pull/795, the `predicate_function_of_sub_group` test was using the global linear ID to perform sub-group 'of' checks.
The checks were only being run on the first sub-group (with ID 0). This was implicitly relying on the first sub-group containing the work-items with IDs from 0 up to the sub-group size, as the checks included conditions like exactly one ID being 1. This is not correct in general, as the mapping between work-items and sub-group items is not defined.
In addition, this commit also enhances the sub-group tests to check that *all* sub-groups in the work-group return the correct result. Before we were either checking only the *first* sub-group
(`predicate_function_of_sub_group`) or checking all sub-groups but …

Fix sub-group 'of' tests

---

tests/usm/usm_api.h

The USM API tests previously each had a "supports_device" method that either returned true or checked whether a specific USM allocation type was supported.
This change moves that duplicated code to two inheritable classes that provide those methods instead.
----
This is a follow up implementing the suggestion made by @keryell here: https://github.com/KhronosGroup/SYCL-CTS/pull/822#discussion_r1380420474 .
(For the avoidance of doubt; I'm employed by Codeplay, a subsidiary of Intel)

[NFC] USM test device support refactored

---

util/math_reference.cpp
util/math_reference.h

Unlike OpenCL abs, but like C and C++ abs, in SYCL 2020, taking the absolute value of a signed type produces a signed result and the behavior is undefined if the absolute value is not representable (i.e. if the input is the greatest negative value), so do not check that the SYCL results match the reference results for this case.

Do not check for undefined behavior in abs.

---

.github/workflows/cts_ci.yml
tests/math_builtin_api/modules/sycl_functions.py
util/math_reference.h

Following https://github.com/KhronosGroup/SYCL-Docs/pull/458 the return
type of abs_diff was changed to be the same as the input types. This
commit makes the corresponding changes to the CTS tests for it.
Signed-off-by: Larsen, Steffen <steffen.larsen@intel.com>

Change abs_diff return type

---

tests/group_functions/group_scan.h

Use global linear id to index input data. Store both the sub-group id and item linear id within the sub-group to recover sub-group construction when verifying, so that we don't make any assumption on the implementation-defined sub-group partitioning and ordering.

[group] Refine scan_over_group for sub-group

---

.github/workflows/cts_ci.yml
tests/math_builtin_api/math_builtin.h
tests/math_builtin_api/modules/sycl_functions.py
tests/math_builtin_api/modules/sycl_types.py
tests/math_builtin_api/modules/test_generator.py
util/math_reference.cpp
util/math_reference.h

This commit adds checks for the following new guarantees of SYCL builtins following the changes made to builtin definitions in revision 8:
* Template arguments on some builtin functions.
* Implicit conversion of vector swizzles to vectors.
* Implicit conversion of convertible types to non-templated arguments.
Fixes https://github.com/KhronosGroup/SYCL-CTS/issues/761

Check new builtin guarntees

---

tests/group_functions/group_scan.h

Prior to this patch, there were a number of overflow issues when the output type of scan op was char and the init type was float. After local verification, all tests pass now.

Fix overflow issues in scan tests.

---

util/math_reference.h

Similar to sycl::abs, sycl::abs_diff now has undefined behavior for unrepresentable results. This patch changes the generated tests for abs_diff to avoid UB, similar to how it was done for abs in https://github.com/KhronosGroup/SYCL-CTS/pull/831.

Do not check for undefined behavior in abs_diff

---

tests/optional_kernel_features/kernel_features_reqd_work_group_size.cpp

The test was using a 1-dimensional kernel attribute even with 2- and 3-dimensional work-group sizes. This is against the semantics of the attribute, and the implementation may throw an `nd_range` exception (though the specification isn't entirely clear).
Regardless, the test is not intentionally testing this aspect of the specification; it's instead checking whether an implementation throws a `kernel_not_supported` exception if N > "max work-group size", and a `nd_range` exception otherwise.

Fix reqd_work_group_size test

---

tests/kernel_args/kernel_args.cpp

It throws sycl::exception instead of sycl::feature_not_supported when failed to test kernel args with samplers.

Catching the right type of exception

---

tests/queue/queue_shortcuts_usm.h

Fixed a bug where `sizeof(int)` was used even if T!=int, which meant char and fp16 cases failed. Now all queue tests pass for the CUDA backend.

Fixed bug in queue test: `sizeof(int)` was used even if T!=int.

---

tests/math_builtin_api/modules/sycl_functions.py
tests/math_builtin_api/modules/sycl_types.py

The spec has been updated in
https://github.com/KhronosGroup/SYCL-Docs/pull/519/, this PR aligns CTS with it.

Switch nan-tests to verify fixed-width arg types for marray

---

tests/atomic_ref/atomic_ref_T_op_test_pointers_fp64.cpp
tests/atomic_ref/atomic_ref_add_sub_op_all_types_test_pointers_fp64.cpp
tests/atomic_ref/atomic_ref_assign_op_test_pointers_fp64.cpp
tests/atomic_ref/atomic_ref_common.h
tests/atomic_ref/atomic_ref_compare_exchange_test_pointers_fp64.cpp
tests/atomic_ref/atomic_ref_constructors_pointers_fp64.cpp
tests/atomic_ref/atomic_ref_exchange_test_pointers_fp64.cpp
tests/atomic_ref/atomic_ref_fetch_add_sub_all_types_test_pointers_fp64.cpp
tests/atomic_ref/atomic_ref_incr_decr_op_test_pointers_fp64.cpp
tests/atomic_ref/atomic_ref_is_lock_free_test_pointers_fp64.cpp
tests/atomic_ref/atomic_ref_store_test_pointers_fp64.cpp

This commit splits the testing of atomic_ref with double * into separate tests to allow for fp64 support checks. This is related to https://github.com/KhronosGroup/SYCL-Docs/issues/526.

Split double * atomic_ref testing

---

tests/buffer/buffer_deduction_guides.cpp
tests/common/type_list.h
tests/multi_ptr/multi_ptr_access_members.h
tests/multi_ptr/multi_ptr_accessor_constructor.h
tests/multi_ptr/multi_ptr_common_assignment_ops.h
tests/multi_ptr/multi_ptr_common_constructors.h
tests/multi_ptr/multi_ptr_comparison_op.h
tests/multi_ptr/multi_ptr_convert_assignment_ops.h
tests/multi_ptr/multi_ptr_deduction_guides.cpp
tests/multi_ptr/multi_ptr_explicit_conversions.h
tests/multi_ptr/multi_ptr_implicit_conversions.h
tests/multi_ptr/multi_ptr_prefetch_member.h
tests/spec_constants/spec_constants_common.h
tests/spec_constants/spec_constants_defined_various_ways.h
tests/spec_constants/spec_constants_defined_various_ways_helper.h
tests/spec_constants/spec_constants_exceptions_throwing_common.h
tests/spec_constants/spec_constants_external.h
tests/spec_constants/spec_constants_multiple.h
tests/spec_constants/spec_constants_same_command_group_common.h
tests/spec_constants/spec_constants_same_name_inter_link.h
tests/spec_constants/spec_constants_same_name_inter_link_helper.h
tests/spec_constants/spec_constants_same_name_stress_helper.h
tests/spec_constants/spec_constants_separate_unit.cpp
tests/spec_constants/spec_constants_via_handler_common.h
tests/spec_constants/spec_constants_via_kernel_bundle.h

Newer versions of `clang` make it error by default, which affect clang-based implementations (like DPCPP).

Fix `-Wc++11-narrowing` warnings

---

util/sycl_exceptions.h

That API was removed from the SYCL 2020 specification in KhronosGroup/SYCL-Docs#431

[NFC] Drop code related to `error_category_for`

---

tests/marray/marray_common.h
tests/marray/marray_constructor.h
tests/marray/marray_members.h
tests/marray/marray_operators.h
tests/marray/marray_operators_arithmetic_assignment_core.cpp
tests/marray/marray_operators_arithmetic_assignment_fp16.cpp
tests/marray/marray_operators_arithmetic_assignment_fp64.cpp
tests/marray/marray_operators_arithmetic_binary_core.cpp
tests/marray/marray_operators_arithmetic_binary_fp16.cpp
tests/marray/marray_operators_arithmetic_binary_fp64.cpp
tests/marray/marray_operators_bitwise_assignment_core.cpp
tests/marray/marray_operators_bitwise_assignment_fp16.cpp
tests/marray/marray_operators_bitwise_assignment_fp64.cpp
tests/marray/marray_operators_bitwise_binary_core.cpp
tests/marray/marray_operators_bitwise_binary_fp16.cpp
tests/marray/marray_operators_bitwise_binary_fp64.cpp
tests/marray/marray_operators_post_unary_core.cpp
tests/marray/marray_operators_post_unary_fp16.cpp
tests/marray/marray_operators_post_unary_fp64.cpp
tests/marray/marray_operators_pre_unary_core.cpp
tests/marray/marray_operators_pre_unary_fp16.cpp
tests/marray/marray_operators_pre_unary_fp64.cpp
tests/marray/marray_operators_relational_binary_core.cpp
tests/marray/marray_operators_relational_binary_fp16.cpp
tests/marray/marray_operators_relational_binary_fp64.cpp

This commit makes marray tests run checks on both device and host, where they would only run on host previously. Additionally it splits operator tests up in separate categories to reduce compilation overhead.
Fixes https://github.com/KhronosGroup/SYCL-CTS/issues/821

Test marray on device

---

tests/math_builtin_api/math_builtin.h

KhronosGroup/SYCL-Docs#511 essentially removed any precision guarantees for math built-ins invoked on host and this PR aligns CTS with that direction.

Drop precision requirements for host math built-ins

---

test_plans/oneapi_kernel_compiler_spirv.asciidoc

This PR adds a test plan for the [`sycl_ext_oneapi_kernel_compiler_spirv`](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler_spirv.asciidoc) extension.

Create test plan for `sycl_ext_oneapi_kernel_compiler_spirv` extension

---

tests/group_functions/group_broadcast.h

The test made incorrect assumptions about work-items mapping to sub-groups, i.e. it expected that sub-groups are formed from subsequent work-items and thus the last element in the first sub-group of an nd-range would have its global linear id equal to sub-group size.
However, SYCL specification does not mandate any specific mapping of work-items into sub-groups and therefore assumptions made by test are incorrect.
This PR rewrites the test so that kernel stores both original and broadcasted values into corresponding buffers and the former is used as a reference for the latter and checked on host.

Fix sub-group broadcast test

---

tests/spec_constants/spec_constants_defined_various_ways.h
tests/spec_constants/spec_constants_multiple.h
tests/spec_constants/spec_constants_same_name_inter_link.h
tests/spec_constants/spec_constants_same_name_stress.h

Let these spec_constants tests skip validation when no target kernel is available to make them pass in AOT mode (since no input state bundles will be available under AOT mode). Previously they do validate the results despite printing log statements like "kernel_bundle doesn't contain target kernel ... (**skipped**)", which cause these tests to fail unexpectedly when running under AOT mode.
Below is a listed of the affected (i.e. fixed) test cases:
specialization_constants_defined_various_ways_via_kb_core
specialization_constants_defined_various_ways_via_kb_fp16
specialization_constants_defined_various_ways_via_kb_fp64
specialization_constants_multiple_via_kb_core
specialization_constants_multiple_via_kb_fp16
specialization_constants_multiple_via_kb_fp64 …

Fix errors for some spec_constants tests when running in AOT mode

---

tests/nd_item/nd_item_constructors.cpp
tests/nd_item/nd_item_equality.cpp

This change allows stateless nd_item implementation as discussed in https://github.com/KhronosGroup/SYCL-Docs/issues/532. The list of changes includes removal of checks which compare nd_team objects shared between work-items or on the host from tests/nd_item/nd_item_equality.cpp and removal of checks invoking "device-only" methods on the host from tests/nd_item/nd_item_constructors.cpp.
Now tests check equality only on device within single work-item.

Update nd_item constructors and equality tests.

---

test_plans/non_uniform_groups.asciidoc

This commit adds a test plan for the [oneapi_non_uniform_groups](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_non_uniform_groups.asciidoc) oneAPI extension.

Add test plan for oneapi_non_uniform_groups extension

---

.github/workflows/cts_ci.yml

This commit bumps the version of DPCPP to b209b321b5a8540263af9ba317c89a1882f06120.

Bump DPCPP version to b209b321b5a8540263af9ba317c89a1882f06120

---

tests/vector_api/generate_vector_api.py

This PR adds testing logic to verify that the type described by the vec::value_type alias is the same as the underlying type of the vector.

Add test for value_type alias in vector_api

---

tests/marray/marray_constructor.h

Remove redundant host `run_checks` in marray_operators.h. It will overwrite all device checking results.

Align marray ctor checking with comments

---

tests/common/common.h
tests/kernel_bundle/sycl_build_verify_kernel_invoked_and_kernel_in_result_bundle.cpp
tests/kernel_bundle/sycl_join_kernel_bundle_with_empty_one.cpp
tests/kernel_bundle/sycl_link_verify_kernel_invoked_and_kernel_in_result_bundle.cpp

Some of the kernel_bundle tests make faulty assumptions about the set of devices used in the kernel bundles. This commit fixes these assumptions.

Fix kernel_bundle tests for multi-device systems

---

tests/hierarchical/hierarchical_non_uniform_local_range.cpp

As I understand - this API was never part of the specification.
Found out this test fails to compile after https://github.com/intel/llvm/commit/f98e99c9e858984b19633825c31d8379d25a806b.

Replace deprecated id -> range conversion

---

tests/buffer/buffer_storage_common.h

In the buffer storage tests, the case using a vector iterator reserves size in the buffer and then expects to be able to access through the specified size. However, this is not the intention of reserve, as it does not change the end of the vector. Instead, this should use resize.

Replace reserve with resize for write-back buffer

---

tests/CMakeLists.txt

There are some test categories (e.g. math_builtin_api) that need to be generated. Such categories are not listed during build configuration as "skipped" if they are excluded.

List excluded generated tests

---

tests/math_builtin_api/math_builtin.h
tests/math_builtin_api/modules/sycl_functions.py
tests/math_builtin_api/modules/test_generator.py

Though the expected precision of math builtins are now defined by the backend specifications, the CTS currently checks the error accuracy based on the tolerances specified by the OpenCL C specification. For `mix` and `smoothstep` these tolerances are defined in "absolute error tolerance" rather than in ULP. This commit makes it possible for the tests to switch between ULP and "absolute error tolerance" checks based on the builtins. Likewise, it applies these to `mix` and `smoothstep` in accordance with the OpenCL C specification.

Add "absolute error tolerance" accuracy mode check

---

tests/extension/oneapi_non_uniform_groups/group_reduce.h
tests/extension/oneapi_non_uniform_groups/group_scan.h

The recently merged tests for the oneAPI non-uniform groups extension are failing on Windows due to missing includes of the map header. This commit fixes this issue.

Add missing include of map in non-uniform group tests

---

CMakeLists.txt

Add a CTS option for enabling root group tests and enable it when `SYCL_CTS_ENABLE_EXT_ONEAPI_TESTS` is on. We forgot this when merging #799.

Add `SYCL_CTS_ENABLE_EXT_ONEAPI_ROOT_GROUP_TESTS` option

---

tests/accessor/accessor_common.h

accessor::get_pointer() should return global_pointer<value_type>, but not global_pointer<DataT>
Spec: https://github.com/KhronosGroup/SYCL-Docs/pull/549

Update test_accessor according to the spec change

---

tests/common/common_python_vec.py
tests/common/vector_swizzles.template
tests/vector_swizzles/CMakeLists.txt
tests/vector_swizzles/generate_vector_swizzles.py

The vector swizzle tests are failing to compile on machines with 16 GB of RAM due to the huge size of some of the test .cpp files that are generated by the scripts. This PR makes the necessary changes to enforce splitting of these test files into smaller and more manageable files that can be compiled without requiring a large memory footprint. As of the time of this writing, I've chosen the number of batches aka chunks to be 32 so that each large file will be subdivided into 32 smaller files. I chose this number because with 16 chunks I was seeing flaky results where a compilation would succeed or fail depending on the state of the machine at the time of compilation. With 32 however, compilation was succeeding constantly. Nevertheless, this can easily be adjusted according to our needs.

Split up vector_swizzle tests into smaller chunks to improve compilation times

---

tests/extension/oneapi_non_uniform_groups/group_of.h

The group_of tests have all active items trying to write to the same index in the memory. For non-uniform groups this can be problematic as not all the results are the same, which means optimizations like vectorization may stumble. This commit splits the results into separate values that are in turn validated. This also allows more precise identification of error origin.

Avoid non-uniform group contesting access to memory in group_of tests

---

tests/extension/oneapi_composite_device/enumerating_composite_devices.cpp

The logic in the test for checking that composite devices are not root devices as it checks that "none of the root devices *are not* the same as any composite device" instead of "none of the root devices *are* the same as any composite device." This commit fixes this check.

Fix check for composite devices not being root devices

---

.github/workflows/cts_ci.yml

This commit bumps the version of DPCPP to 20a088e1231c4ac85fd74c0de79c563977d2f38c.

Bump DPCPP version to 20a088e1231c4ac85fd74c0de79c563977d2f38c

---

tests/extension/oneapi_non_uniform_groups/group_barrier.cpp
tests/extension/oneapi_non_uniform_groups/group_barrier.h
tests/extension/oneapi_non_uniform_groups/group_broadcast.cpp
tests/extension/oneapi_non_uniform_groups/group_broadcast.h
tests/extension/oneapi_non_uniform_groups/group_broadcast_fp16.cpp
tests/extension/oneapi_non_uniform_groups/group_broadcast_fp64.cpp
tests/extension/oneapi_non_uniform_groups/group_joint_reduce.cpp.in
tests/extension/oneapi_non_uniform_groups/group_joint_scan.cpp.in
tests/extension/oneapi_non_uniform_groups/group_of.cpp
tests/extension/oneapi_non_uniform_groups/group_of.h
tests/extension/oneapi_non_uniform_groups/group_permute.cpp
tests/extension/oneapi_non_uniform_groups/group_permute.h
tests/extension/oneapi_non_uniform_groups/group_permute_fp16.cpp
tests/extension/oneapi_non_uniform_groups/group_permute_fp64.cpp
tests/extension/oneapi_non_uniform_groups/group_reduce_over_group.cpp.in
tests/extension/oneapi_non_uniform_groups/group_scan_over_group.cpp.in
tests/extension/oneapi_non_uniform_groups/group_shift.cpp
tests/extension/oneapi_non_uniform_groups/group_shift.h
tests/extension/oneapi_non_uniform_groups/group_shift_fp16.cpp
tests/extension/oneapi_non_uniform_groups/group_shift_fp64.cpp
tests/extension/oneapi_non_uniform_groups/non_uniform_group_common.h
tests/group_functions/group_functions_common.h

To avoid case where tests are skipped for supported non-uniform groups because of a skip in the cases for unsupported non-uniform groups, this commit changes all the test cases to be templated on packs of these group types, based on their aspect groupings.

Template non-uniform group test cases on the group type

---

tests/math_builtin_api/math_builtin.h
tests/math_builtin_api/modules/test_generator.py

Following https://github.com/KhronosGroup/SYCL-Docs/pull/555 this commit adds raw pointer tests to the cases generated by the SYCL math builtin generator script.

Add raw pointer cases to math builtin tests

---

run_conformance_tests.py

This patch adds new option `--run-only` to `run_conformance_tests.py` to be able to execute tests on already built binaries.

Add option to execute tests on already built binaries

---

.github/workflows/cts_ci.yml

In our CI testing, the system is running out of disk space while building the `test_all` executable. That said, the resulting executable is reundant, as it is a combined executable of all the other test category executables produced. This commit changes the target built by CI to `test_conformance` which only builds the test category executables.

Build test_conformance instead of test_all in CI

---

tests/platform/platform_info.cpp

Fixes https://github.com/KhronosGroup/SYCL-CTS/issues/929.
Corresponding spec change: https://github.com/KhronosGroup/SYCL-Docs/pull/608

Remove testing of removed info::platform::profile.

---

README.md
ci/generate_exclude_filter.py
docs/README.adoc
tests/CMakeLists.txt

After the conformance submission discourages the use of test_all and the CI has moved away from using test_all, all the benefit of it becomes convenience when wanting to run all tests. However, as it is an overall target and with the size of it increasing with the test suite, to general users it will just be an inconvenience, as it results in longer compilation times and higher resource requirements. Given this, this commit removes the test_all target.

Remove test_all target

---

run_conformance_tests.py
tools/stylesheet.xml

This patch adds a command line option for run_conformance_report.py to
save the SYCL-CTS commit hash in the conformance_report.xml.
This option is optional and serves to help to determine the version of
the suite.

Add option to save commit hash in report

---

tests/accessor_legacy/accessor_constructors_buffer_utility.h
tests/accessor_legacy/accessor_types_core.h
tests/accessor_legacy/accessor_types_fp16.h
tests/accessor_legacy/accessor_types_fp64.h
tests/accessor_legacy/accessor_types_image_core.h
tests/accessor_legacy/accessor_types_image_fp16.h
tests/buffer/buffer_api_fp16.cpp
tests/buffer/buffer_api_fp64.cpp
tests/buffer/buffer_constructors_fp16.cpp
tests/buffer/buffer_constructors_fp64.cpp
tests/buffer/buffer_storage_fp16.cpp
tests/buffer/buffer_storage_fp64.cpp
tests/common/common.h
tests/common/type_list.h
tests/group/group_async_work_group_copy.cpp
tests/group/group_async_work_group_copy_fp16.cpp
tests/group/group_async_work_group_copy_fp64.cpp
tests/nd_item/nd_item_async_work_group_copy.cpp
tests/nd_item/nd_item_async_work_group_copy_fp16.cpp
tests/nd_item/nd_item_async_work_group_copy_fp64.cpp
tests/scalars/scalars_interoperability_types.cpp

This improves compatibility with implementations that do not expose OpenCL interop (notably [SimSYCL](https://github.com/celerity/SimSYCL), and AFAIK also AdaptiveCpp / hipSYCL).
This change is probably incomplete, but enough to get some tests to build with SimSYCL that otherwise wouldn't. 
`group_async_work_group_copy.cpp` had `!is_same` checks between cl types and stdint types - please correct me if it's wrong to remove these checks, it appears to me as though performing the same check twice is not an issue - but maybe there's symbol clashes.

Compatibility: Only use `cl_*` types if SYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS is set

---

conformance/submission_details_template.txt

The "Supported optional features" in the conformance submission template does not add any useful information that is not already covered by the rest of the document, so this patch proposes its removal.

Remove non-informative "Supported optional features" section

---

tests/multi_ptr/multi_ptr_explicit_conversions.h
tests/multi_ptr/multi_ptr_explicit_conversions_core.cpp
tests/multi_ptr/multi_ptr_explicit_conversions_fp16.cpp
tests/multi_ptr/multi_ptr_explicit_conversions_fp64.cpp

Add `(decorated_|raw_)generic_ptr` aliases definitions.
These aliases were previously referenced in the SYCL specification, but not defined and not tested in the CTS.

Add missing tests for `multi_ptr` aliases for `access::address_space::generic`

---

conformance/submission_details_template.txt

This commit splits one of the fields in the "Conformant Product"  and "Conformance submission details" sections of the submission_details_template file. This brings the fields closer in line with the conformant products page.

Split conformant product fields in submission template

---

tests/accessor_legacy/accessor_constructors_buffer_utility.h
tests/accessor_legacy/accessor_constructors_image_utility.h

Accessor shouldn't use buffer::property.
It looks like there is no real need for `properties` to contain any property, as the test just checks all possible constructors.

Fix accessor using unsuitable property

---

oclmath/fpcontrol.h
oclmath/rounding_mode.cpp
oclmath/rounding_mode.h

This replaces fpcontrol.h and rounding_mode.cpp/.h with the versions from OpenCL CTS. The old version included in SYCL-CTS did not support AArch64, and although it would be possible to just make the smallest possible change to get that to work, it seems like it will be easier for future changes for the OpenCL and SYCL versions of these files to be the same.

Update oclmath to add AArch64 support.

---

.github/workflows/cts_ci.yml
test_plans/kernel.asciidoc
test_plans/kernel_bundle.asciidoc
test_plans/queue_constructors.asciidoc
tests/invoke/parallel_for_simplifications.cpp

The default branch has been renamed from `SYCL-2020` to `main`. There are places in the source code where we still use old name.

Fix branch name in CI workflow and links to test plans.

---

tests/range/range_api.cpp

In function test_range_kernels, range[2] is 64 and range_two[2] is 128. It is undefined behavior to use either of them as rhs of bitwise shift operator because the rhs is not smaller than the number of bits in range value type. This PR divides rhs by 4 so that it is smaller than 64.

[range_api] Fix bitwise shift rhs out-of-range

---

cmake/FindDPCPP.cmake

`-DCMAKE_EXE_LINKER_FLAGS="/link /stack:2097152"` will break linking stage on Windows because all options following "/link" are passed to linker. And "-o" passed to linker can't be recognized by linker and trigger an error

Gather linker flags to prevent /link break linking stage

---

oclmath/rounding_mode.cpp
oclmath/rounding_mode.h

In commit 33be1b17, I updated rounding_mode.* to their current OpenCL-CTS versions without noticing that the old versions had an intentional deviation from OpenCL-CTS: a call to vlog_error had been commented out, and the headers that were needed only for that were also left out. This commit reapplies those changes.

Fix MSVC build.

---

tests/multi_ptr/multi_ptr_explicit_conversions.h
tests/multi_ptr/multi_ptr_explicit_conversions_core.cpp
tests/multi_ptr/multi_ptr_explicit_conversions_fp16.cpp
tests/multi_ptr/multi_ptr_explicit_conversions_fp64.cpp

Enable generic pointer aliases tests in DPCPP as they were added in 82d874f49293d342eb2e2ffe2eb8174778d4ceab.

Enable generic pointer aliases tests in DPCPP

---

tests/language/CMakeLists.txt
tests/language/constant_evaluation.cpp

There are a lot of restrictions for kernel code, except when present in a constant evaluated context.
This is a test corresponding to the specification clarification introduced by PR https://github.com/KhronosGroup/SYCL-Docs/pull/388

Check forbidden kernel constructs in constant evaluated context

---

CMakeLists.txt
tests/extension/oneapi_local_memory/CMakeLists.txt
tests/extension/oneapi_local_memory/local_memory.cpp

Implement the tests from [this](https://github.com/KhronosGroup/SYCL-CTS/blob/bbe812fdfcf81cff5711bb6e1e19eb89474304b8/test_plans/oneapi/local_memory.asciidoc) test plan.

Implement tests for `sycl_ext_oneapi_local_memory` extension

---

tests/kernel_bundle/sycl_link_different_device_for_sycl_link.cpp

This patch addresses issue of test assuming that devices from `get_devices` that are not in the set of associated devices for kernel bundle.  However in some scenarios when only 2 devices are available of same type test will fail because `q.get_context()` includes both devices and test doesn't issue exception with `errc::invalid` which was expected.

Fix for `sycl_link_different_device_for_sycl_link` test

---

.github/workflows/cts_ci.yml

New version fixes the `SYCL_LANGUAGE_VERSION` macro definition.

Uplift DPC++ version to df00dcb50e4ce07dc475dd0bf176acc323e0a240.

---

tests/accessor_basic/accessor_common.h
tests/common/common.h
tests/common/common_vec.h
tests/group_functions/group_functions_common.h
tests/group_functions/group_joint_reduce.cpp.in
tests/group_functions/group_joint_scan.cpp.in
tests/group_functions/group_reduce_over_group.cpp.in
tests/group_functions/group_scan_over_group.cpp.in
tests/kernel_bundle/kernels.h
tests/kernel_bundle/sycl_is_compatible.cpp
tests/marray_basic/marray_operators.h
tests/math_builtin_api/math_builtin.h
tests/optional_kernel_features/kernel_features_device_has_exceptions.cpp
tests/optional_kernel_features/kernel_features_separate_unit.cpp
tests/optional_kernel_features/kernel_features_speculative_compilation.cpp
tests/reduction/identity_helper.h
tests/reduction/reduction_without_identity_param_common.h
tests/scalars/scalars_sycl_types.cpp
tests/spec_constants/spec_constants_defined_various_ways.h
tests/spec_constants/spec_constants_multiple.h
tests/spec_constants/spec_constants_same_name_inter_link.h
tests/spec_constants/spec_constants_same_name_stress.h
util/accuracy.h
util/math_helper.h
util/math_reference.cpp
util/math_reference.h
util/type_names.h
util/type_traits.h

This PR improves compatibility with implementations that do not expose the `sycl::half` type (notably, [SimSYCL](https://github.com/celerity/SimSYCL) built with GCC).
There might be additional usages I missed, in tests that SimSYCL is currently unable to compile for other reasons.
**Question** to the reviewers: Is it necessary to exclude some translation units in CMake when the file names are `*fp16.cpp` or are these handled automatically?

Compatibility: Only use `sycl::half` if SYCL_CTS_ENABLE_HALF_TESTS is set

---

.github/workflows/cts_ci.yml

The CI jobs fail with the error:
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Moving to version 4 to fix the error.

Uplift GitHub Action upload-artifact version.

---

tools/stylesheet.xml

The link to SYCL logo has changed: the old link is not valid anymore, updating it.

Update SYCL logo in conformance reports

---

.github/workflows/cts_ci.yml
docker/dpcpp/Dockerfile

Intel has restricted access to Docker containers with pre-installed DPC++ compiler.
Let's build the containers here using pre-built DPC++ binaries still available on GitHub.

[CI] Fix DPCPP container creation

---

tests/extension/oneapi_local_memory/local_memory.cpp

This PR makes the following changes to the tests for the oneAPI local memory extension:
1. Updates the tests to use `sycl_cts::util::get_cts_object::queue()` instead of the default-constructed queue.
2. Changes `#ifdef SYCL_CTS_ENABLE_FULL_CONFORMANCE` to `#if SYCL_CTS_ENABLE_FULL_CONFORMANCE`.
3. Adds a check for `has(sycl::aspect::fp64)` to test cases that use `double` in device code.

Fix issues in `oneapi_local_memory` test

---

tests/queue/queue_constructors.cpp

Add test cases for queue default context

---

tests/sub_group/sub_group_semantics.cpp

Fixes https://github.com/KhronosGroup/SYCL-CTS/issues/848.

Do not use C99 VLA in C++ code

---

test_plans/khr/free_function_commands.asciidoc

Spec: https://github.com/KhronosGroup/SYCL-Docs/pull/644
In general this is a copy-paste of test_plans/oneapi/enqueue_functions.asciidoc

Add a test plan for sycl_khr_free_function_commands

---

CMakeLists.txt
tests/extension/khr_queue_empty_query/CMakeLists.txt
tests/extension/khr_queue_empty_query/queue_empty.cpp

Related to: https://github.com/KhronosGroup/SYCL-Docs/pull/700

Add khr_queue_empty tests

---

cmake/FindDPCPP.cmake

The purpose of this PR is to add flag which enables testing for unfinished KHR extensions.

Add flag for unfinished KHR extensions

---

tests/accessor_legacy/accessor_api_local_common.h

Both `target::constant_buffer` and `target::local` have the restriction that `get_pointer()` may only be called from within a command.

Don't call `accessor::get_pointer()` from outside command when not allowed

---

CMakeLists.txt

New macro for `SYCL Next` to be able to differentiate between SYCL 2020 and SYCL Next CTS tests.
https://github.com/KhronosGroup/SYCL-CTS/issues/952

Add new macro for SYCL Next CTS tests

---

tests/address_space/address_space_core.cpp

This PR purpose is to add tests for the new shorthand aliases of address spaces. 
https://github.com/KhronosGroup/SYCL-CTS/issues/952
Changes depend on macro proposed in https://github.com/KhronosGroup/SYCL-CTS/pull/1049

Add tests for the new shorthand aliases of address spaces

---

tests/vector_constructors/generate_vector_constructors.py
tests/vector_operators/generate_vector_operators.py

Following the specification change in https://github.com/KhronosGroup/SYCL-Docs/pull/676.

Remove `vec::vector_t` tests

---

tests/common/common_vec.h
tests/vector_operators/generate_vector_operators.py

Seems to have been removed accidentally in https://github.com/KhronosGroup/SYCL-CTS/pull/130.
https://github.com/KhronosGroup/SYCL-Docs/pull/675 might be considered somewhat related.

Restore relational/logical operators tests for `sycl::vec`

---

.github/workflows/cts_ci.yml

GitHub deprecated Ubuntu 20.04 images on February 1. The support will
end completely on April 1.
Update image to `ubuntu-latest` to simplify future maintainanace of
docker images. All jobs we update are independent of a specific Ubuntu
version and are expected to work out of the box on any future Ubuntu
version.

[CI] Update Ubuntu image to latest version

---

.github/workflows/cts_ci.yml

Today we use our own implementation of clang-format check which posts
the diff proposed by clang-format to GitHub actions summary. Switching
to cpp-linter action enables use of review suggestions, which are more
user friendly.

[CI] Switch clang-format to cpp-linter action

---

tests/event/event.cpp

There's two variants of the host task, one that does interop and one that doesn't.
The only difference between the two is that the one that does interop takes an `interop_handle`.
In this event test using `(auto)` for the host task lambda will be interpreted as taking an `interop_handle` which means the interop version of the host task will be used.
This test doesn't do or check any interop so this is unnecessary, and I suspect it also wasn't intended when the test was written.

Don't use interop host task for event tests

---

.github/workflows/cts_ci.yml

DPC++ compiler fixed the problem blocking ccache functionality reported in https://github.com/intel/llvm/issues/5260.
Unfortunately, we can't remove the workaround due to the overhead added by the default "preprocessor mode". Rebuilding the cache in "preprocessor mode" on GitHub runners takes more than 6h, which is a limit for our plan.

[CI][NFC] Update ccache workaround comments

---

tests/opencl_interop/opencl_interop_constructors.cpp

`make_queue` accepts both a native handle and a context. While the spec
doesn't explictly say so, it's my understanding that the "internal"
native handle of the provided context must match the context of the
provided handle.
This fixes the `opencl_interop_constructors` test, which was incorrectly
trying to construct a sycl::queue from a native handle created from a
different context.

OpenCL Interop: Use matching context when constructing queue

---

CMakeLists.txt

* Catch2 framework is not respecting page fault handler chain affecting other layers

fix: disable `Catch2` signal handlers

---

tests/CMakeLists.txt
tests/common/common_python_vec.py
tests/common/common_vec.h
tests/common/vector.template
tests/common/vector_swizzle_assignment.template
tests/common/vector_swizzles.template
tests/vector_api/generate_vector_api.py
tests/vector_constructors/generate_vector_constructors.py
tests/vector_load_store/generate_vector_load_store.py
tests/vector_operators/generate_vector_operators.py
tests/vector_swizzle_assignment/generate_vector_swizzle_assignment.py

Spec changes are at https://github.com/KhronosGroup/SYCL-Docs/pull/674.

Enable `std::byte` as `vec`'s element type

---

tests/accessor_legacy/accessor_api_local_common.h

`log_accessor` doesn't take a `kernelName` template parameter, so this would fail to build.

Fix test_accessor_legacy build with SYCL_CTS_ENABLE_VERBOSE_LOG

---

tests/extension/oneapi_non_uniform_groups/group_barrier.h

Previously, test `oneapi_non_uniform_groups-group_barrier` has been failing flakily on PVC machines. It turns out to be a test issue caused by race conditions between sub groups inside the test case. Therefore, revising the test case to get rid of this issue.

Fix flaky issue in test `oneapi_non_uniform_groups-group_barrier`

---

tests/common/common_vec.h

Reference math function uses std math function, which may not work for a backend target if the function fails to be lowered to llvm intrinsic that the target supports.
Using sycl version in device code should work for all targets.

Replace reference math functon with sycl version in common_vec.h

---

test_plans/khr/dynamic_addrspace_cast.asciidoc
test_plans/khr/static_addrspace_cast.asciidoc

Adds test plans for the extensions defined in https://github.com/KhronosGroup/SYCL-Docs/pull/650.

Add test plans for `sycl_khr_addrspace_cast` extensions

---

tests/extension/oneapi_enqueue_functions/enqueue_functions.cpp

This PR updates queue creation to avoid using default device selection because if they are created by default device selector. It causes CTS run on unexpected devices sometimes.
For example:
Test is run on machine with CPU and GPU, and test is specified for to run on specific device and by using default selector test might not run on desired device.

Update queue creation to avoid using default device selection in `oneapi_enqueue_functions` tests

---

cmake/FindDPCPP.cmake

clang-cl doesn't support "/debug" and "/INCREMENTAL", and it will throw errors if CMake build type is set to "Debug".

Remove /debug and /INCREMENT for clang-cl under CMAKE debug configuration
