KhronosGroup/SYCL-CTS

tests/nd_item/nd_item_global_barrier.cpp
The current version of the test is sharing data through local memory
(tile) between work items. Since the barrier argument is global_space,
this is not guaranteed to produce deterministic results.
This patch enables sharing through global memory.
=> Fix data sync in nd_item_global_barrier test

tests/accessor/accessor_api_buffer_common.h
Made these methods return the values of the accessor,
not the buffer from which this accessor was created.
Corresponding SYCL specification update:
https://github.com/KhronosGroup/SYCL-Docs/pull/57
Patch by Alexey Voronov.
Signed-off-by: Alexey Voronov <alexey.voronov@intel.com>
Signed-off-by: Alexey Bader <alexey.bader@intel.com>
=> Fix checks for get_count()/get_size() of accessor class.

tests/math_builtin_api/generate_math_builtin.py, tests/vector_constructors/generate_vector_constructors.py
- Fix #pragma OPENCL EXTENSION usage 
- Fix uninitialized variable warning
=> [NFC] Fix two kinds of compilation warnings in generated files

util/test_base_opencl.cpp
=> Make test_base_opencl framework respect SYCL device selector choice

tests/image/image_api.cpp
* Construct final data before the image
* Closes #38
=> Construct final data before the image

cmake/FindIntel_SYCL.cmake
Set specific INTERFACE_LINK_OPTIONS option for Clang.
=> Set INTERFACE_LINK_OPTIONS for Clang

tests/math_builtin_api/generate_math_builtin.py, tests/math_builtin_api/math_builtin.h, tests/math_builtin_api/modules/test_generator.py, util/math_helper.cpp, util/math_helper.h, util/math_reference.cpp, util/math_reference.h
Remaining gap (test coverage): result correctness isn't checked
for Math functions, Integer functions, Geometric Functions, Relational functions
=> Added check for result correctness for Common functions

tests/header/header_test.cpp
CL_SYCL_LANGUAGE_VERSION -> SYCL_LANGUAGE_VERSION
=> Update language version macro check for SYCL 2020

cmake/FindIntel_SYCL.cmake, tests/math_builtin_api/generate_math_builtin.py, tests/math_builtin_api/math_builtin.h, util/math_helper.h, util/math_reference.cpp, util/math_reference.h
Remaining gap (test coverage): result correctness isn't checked for Integer functions, Geometric Functions, Math functions
=> Added check for result correctness for Relational functions (4.13.7)

cmake/FindIntel_SYCL.cmake
Initial commit's author: Lazarev <vladimir.lazarev@intel.com>
=> Improve windows build configuration

tests/CMakeLists.txt, tests/math_builtin_api/CMakeLists.txt
1. Added `DEPENDS` argument to `generate_cts_test`
2. Added files for `math_builtin_api` test to depend on
=> [Test generation] Add DEPENDS argument

tests/common/get_cts_object.h, tests/hierarchical/hierarchical_functor.cpp, tests/hierarchical/hierarchical_id.cpp, tests/hierarchical/hierarchical_implicit_barriers.cpp, tests/hierarchical/hierarchical_implicit_conditional.cpp, tests/hierarchical/hierarchical_implicit_reduce.cpp, tests/hierarchical/hierarchical_lambda.cpp, tests/hierarchical/hierarchical_non_uniform_local_range.cpp, tests/hierarchical/hierarchical_private_memory.cpp
Depends on PR https://github.com/KhronosGroup/SYCL-CTS/pull/90
Only last commit https://github.com/KhronosGroup/SYCL-CTS/commit/2d782885da48287de5e02b36d64dee4c952c89cf for this PR
=> Extend coverage for group::parallel_for_work_item for all dims

tests/buffer/buffer_api_common.h, tests/buffer/buffer_api_core.cpp, tests/buffer/buffer_api_fp16.cpp, tests/buffer/buffer_api_fp64.cpp, tests/buffer/buffer_constructors_common.h, tests/buffer/buffer_constructors_core.cpp, tests/buffer/buffer_constructors_fp16.cpp, tests/buffer/buffer_constructors_fp64.cpp, tests/buffer/buffer_storage_common.h, tests/buffer/buffer_storage_core.cpp, tests/buffer/buffer_storage_fp16.cpp, tests/buffer/buffer_storage_fp64.cpp, tests/buffer/buffer_type_list.h, tests/common/type_coverage.h, tests/common/type_list.h
Depends on PR https://github.com/KhronosGroup/SYCL-CTS/pull/91
Only last commit https://github.com/KhronosGroup/SYCL-CTS/commit/363844071cfa674d6dc67e6ff6d121c99ef4ea4c for this PR
=> Added type coverage for buffer

tests/common/once_per_unit.h, tests/math_builtin_api/generate_math_builtin.py, tests/math_builtin_api/math_builtin.h, tests/math_builtin_api/modules/sycl_functions.py, tests/math_builtin_api/modules/test_generator.py, util/accuracy.h, util/math_reference.cpp, util/math_reference.h
Remaining gap (test coverage): result correctness isn't checked for Integer functions, Geometric Functions
=> Added check for result correctness for Math functions

tests/exception_handling/synchronous_exceptions.cpp
Verify exception API calls and basic exception usage for synchronous errors
=> Provide result verification for synchronous exceptions

tests/multi_ptr/multi_ptr_api.cpp, tests/multi_ptr/multi_ptr_api_common.h, tests/multi_ptr/multi_ptr_api_fp16.cpp, tests/multi_ptr/multi_ptr_common.h, tests/multi_ptr/multi_ptr_constructors.cpp, tests/multi_ptr/multi_ptr_constructors_common.h, tests/multi_ptr/multi_ptr_constructors_fp16.cpp
Checks for pointer values and underlying data verification were added
=> Add result verification for multi_ptr tests

conformance_filters/core.csv, tests/usm/CMakeLists.txt, tests/usm/usm_fill_memset_memcpy.cpp
Provide verification for functions/APIs from Unified Shared Memory (USM) fill, memcpy and memset
=> Adding new test for USM

tests/buffer/buffer_api_common.h
This PR fixed problem with flaky test running failure while tests running
=> Fix alignment for type-pun to guarantee test to work correctly

tests/common/common_python_vec.py, tests/common/common_vec.h, tests/vector_api/generate_vector_api.py
replace get_count() with size() and get_size() with byte_size()
=> Update sycl::vec functions from 1.2.1 to 2020

tests/exceptions/CMakeLists.txt, tests/exceptions/exceptions.h, tests/exceptions/exceptions_make_error_code.cpp
Provide verification for sycl::make_error code and verify same work std::error_code and sycl::make_error_code
=> Add test for sycl::make_error_code

tests/usm/usm_api.h, tests/usm/usm_api_copy_handler_no_events.cpp, tests/usm/usm_api_copy_queue_multiple_events.cpp, tests/usm/usm_api_copy_queue_no_events.cpp, tests/usm/usm_api_copy_queue_single_event.cpp, tests/usm/usm_api_fill_handler_no_events.cpp, tests/usm/usm_api_fill_queue_multiple_events.cpp, tests/usm/usm_api_fill_queue_no_events.cpp, tests/usm/usm_api_fill_queue_single_event.cpp, tests/usm/usm_api_mem_advise_handler_no_events.cpp, tests/usm/usm_api_mem_advise_queue_multiple_events.cpp, tests/usm/usm_api_mem_advise_queue_no_events.cpp, tests/usm/usm_api_mem_advise_queue_single_event.cpp, tests/usm/usm_api_memcpy_handler_no_events.cpp, tests/usm/usm_api_memcpy_queue_multiple_events.cpp, tests/usm/usm_api_memcpy_queue_no_events.cpp, tests/usm/usm_api_memcpy_queue_single_event.cpp, tests/usm/usm_api_memset_handler_no_events.cpp, tests/usm/usm_api_memset_queue_multiple_events.cpp, tests/usm/usm_api_memset_queue_no_events.cpp, tests/usm/usm_api_memset_queue_single_event.cpp, tests/usm/usm_api_prefetch_handler_no_events.cpp, tests/usm/usm_api_prefetch_queue_multiple_events.cpp, tests/usm/usm_api_prefetch_queue_no_events.cpp, tests/usm/usm_api_prefetch_queue_single_event.cpp
this issues arose due to comments applying in different PR's with different PR merging order
=> Fix some issues for USM

tests/exceptions/exceptions.h, tests/exceptions/exceptions_error_code.cpp, tests/exceptions/exceptions_make_error_code.cpp, tests/exceptions/exceptions_sycl_category.cpp, tests/exceptions/exceptions_sycl_category_common.h, tests/exceptions/exceptions_sycl_category_try_order_fiasco.cpp, tests/exceptions/exceptions_test_result_checker.cpp
This PR depends on PR https://github.com/KhronosGroup/SYCL-CTS/pull/183
This PR changes starts with commit https://github.com/KhronosGroup/SYCL-CTS/commit/a76501a5e60589a2ed97987d98822c69e27c1b8e
=> Add tests for sycl::sycl_category

tests/exceptions/exceptions_errc_for.cpp
This test provide verification that `sycl::errc_for` implemented according to SYCL-2020 revision 3
=> Add test for sycl::errc_for

.github/workflows/cts_ci.yml, ci/dpcpp.filter
Remove USM tests from CI filter.
=> [CI] Bump dpcpp compiler version in CI to c230f3c

tests/extension/oneapi_device_global/device_global_handler_copy_memcpy_overloads.cpp
This PR provides a patch to `sycl::handler` copy member functions overloads tests. The patch separates all operations with `single_task`,  `copy` and `memcpy` into different command group scopes.
=> Move copy operations to different command group scopes in `sycl::handler` copy member functions overloads tests 

test_plans/sub_group_mask.asciidoc
Adding test plan for recently added tests in https://github.com/KhronosGroup/SYCL-CTS/tree/SYCL-2020/tests/extension/oneapi_sub_group_mask
=> Add test plan for sub_group_mask

tests/exceptions/exceptions_sync_exception.cpp
Test for [2.7. Synchronous exceptions mechanism](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/exceptions.asciidoc#27-synchronous-exceptions-mechanism)
=> Add test for synchronous exceptions mechanism

tests/accessor/accessor_common.h, tests/accessor/generic_accessor_constructors.hpp
This provides tag factory functions for existing and future accessor tests
=> Add tag factory for accessor tests

tests/accessor/local_accessor_access_among_work_items.h, tests/accessor/local_accessor_access_among_work_items_core.cpp, tests/accessor/local_accessor_access_among_work_items_fp16.cpp, tests/accessor/local_accessor_access_among_work_items_fp64.cpp
These tests provides verification that local_accessor can
access to the memory shared among work-items
=> Add test on access to the memory shared among work-items

tests/accessor/host_accessor_api_common.h
Fix minor issue with host_accessor api tests.
Still not enabling tests because it's not fully implemented yet.
=> Fix host_accessor api test

tests/accessor/local_accessor_api_common.h
Fix minor bugs in tests and move test to swap for different section for correct check
=> Fix local_accessor api tests

tests/accessor/generic_accessor_properties.h, tests/accessor/host_accessor_properties.h
Fix wrong implementation of accessor_property tests
=> Fix accessor_property tests

tests/accessor/accessor_common.h, tests/accessor/accessor_exceptions.h, tests/accessor/generic_accessor_api_common.h, tests/accessor/host_accessor_api_common.h, tests/common/type_coverage.h, tests/common/value_operations.h
Fix how device copyable device copy std container types are handled in accessor tests
=> Fix tests for accessors device copyable std containers

tests/accessor/accessor_iterator_requirement.cpp, util/type_traits.h
Fix tests for iterators requirements for sycl::accessor and sycl::host_accessor.
=>  Fix tests for accessor iterators requirements

test_plans/buffers.asciidoc
Test plan for buffer interface test updates relating to SYCL 1.2.1 >> SYCL 2020.
=> Buffers 2020 plan

tests/common/value_operations.h
Fix how tests for accessor write data and checks result for bool type
=> Fix accessor tests for bool type

test_plans/group.asciidoc
Adds a test plan for the stream class as described in Section 4.9.1.7. of the SYCL 2020 specification.
=> Add test plan for group class

test_plans/individual-functions.asciidoc
Test plan for all the test fixes and updates in 4.17 that are not group-based (that were covered by https://github.com/KhronosGroup/SYCL-CTS/pull/400).
=> Non-group functions test plan

test_plans/sub_group.asciidoc
Adds a test plan for the stream class as described in Section 4.9.1.8. of the SYCL 2020 specification.
=> Add test plan for sub group class

test_plans/group_functions.asciidoc
Adds a test plan for group functions as described in sections 4.17.3 "Group functions" and 4.17.4 "Group algorithms library" of the SYCL 2020 specification.
=> Add test plan for group functions

ci/hipsycl.filter, tests/common/type_coverage.h, tests/property/CMakeLists.txt, tests/property/property_api.cpp
Adds tests for `is_property` and `is_property_of` according to test plan #447.
=> Add tests for is_property

tests/exceptions/exceptions_async_handler.cpp
Check that if an asynchronous error occurs async handler is invoked according to [4.13.1.3. Priorities of async handlers](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_priorities_of_async_handlers).
According to test plan update https://github.com/KhronosGroup/SYCL-CTS/pull/449 (not yet merged).
=> Add tests for async handler priorities

tests/kernel_bundle/device_image_api.cpp, tests/kernel_bundle/get_kernel_bundle.h
Adds tests for the device image class according to #434.
=> Add tests for device image class

tests/namespace/CMakeLists.txt, tests/namespace/namespace.cpp.in
=> Add tests for header files and namespaces

test_plans/exceptions.asciidoc
Add cases for asynchronous errors according to [4.13.1.3. Priorities of async handlers](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_priorities_of_async_handlers).
=> Update test plan for exceptions

test_plans/atomic_ref.asciidoc
This test plan based on PR: https://github.com/KhronosGroup/SYCL-CTS/pull/413 and comments from @gmlueck.
=> Test plan for sycl::atomic_ref

tests/sub_group/CMakeLists.txt, tests/sub_group/sub_group_api.cpp
=> Add tests for sub group

test_plans/atomic_ref.asciidoc
Apply @AlexeySachkov comments for atomic_ref test plan
=> Fix atomic_ref test plan

tests/common/value_operations.h, tests/kernel/kernel_parameters.cpp
Add tests according to [Test plan for parameter passing to kernels](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/kernels_parameters.asciidoc)
=> Add kernel parameters tests

tests/kernel/kernel_api.cpp, tests/kernel/kernel_constructors.cpp, tests/kernel/kernel_info.cpp
Add tests for sycl::kernel to cover remaining gaps according to test plan https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/kernel.asciidoc.
=> Add tests for sycl::kernel to cover remaining gaps

tests/atomic_fence/CMakeLists.txt, tests/atomic_fence/atomic_fence.cpp, tests/common/type_coverage.h
Add test for sycl::atomic_fence function
=> Add test for atomic_fence

tests/atomic_fence/atomic_fence.cpp
Added link to issue that caused disabled code in atomic_fence for DPCPP
=> Added link to issue that caused disabled code in atomic_fence

ci/dpcpp.filter
=> [CI] Enable buffer test compilation with DPC++

tests/marray/marray_alias.cpp, tests/marray/marray_constructor.h, tests/marray/marray_operators.h
Partially enabled the tests for marray
=> Enable marray tests partially

tests/invoke/parallel_for_simplifications.cpp
Tests created according to test plan https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/parallel_for_simplifications.asciidoc
=> Add tests for parallel_for simplifications

tests/kernel/kernel_parameters.cpp
The comment doesn't seem necessary after #515.
=> Removes outdated comment.

tests/bit_cast/CMakeLists.txt, tests/bit_cast/bit_cast_helper_functions.h, tests/bit_cast/bit_cast_test.h, tests/bit_cast/bit_cast_test_core.cpp, tests/bit_cast/bit_cast_test_core_fp64.cpp, tests/common/type_list.h, tests/common/value_operations.h
Create test for `sycl::bit_cast` according to [bit cast test plan](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/bit_cast_test_plan.asciidoc)
=> Added test for sycl::bit_cast()

tests/common/semantics_reference.h, tests/common/string_makers.h, tests/context/context_info.cpp, tests/function_objects/function_objects_core.cpp, tests/function_objects/function_objects_fp64.cpp, tests/image/default_image.h, tests/image/image_semantics.cpp, tests/property/property_api.cpp
Add issue links to 
common
context
function_objects
image
property
=> Add issue links to various tests

tests/math_builtin_api/math_builtin.h, tests/math_builtin_api/modules/test_generator.py, util/math_helper.h, util/math_reference.h, util/math_vector.h
Fixed bugs in python module and math functions for marray in util.
=> Fix math_builtin_api tests

tests/CMakeLists.txt, tests/common/common_python_vec.py, tests/common/common_vec.h, tests/vector_api/generate_vector_api.py, tests/vector_constructors/generate_vector_constructors.py, tests/vector_load_store/generate_vector_load_store.py, tests/vector_operators/generate_vector_operators.py, tests/vector_swizzle_assignment/generate_vector_swizzle_assignment.py
Covered vector gaps for bool and subscript operator
=> Added bool type for vector tests and covered [] operator

tests/kernel/kernel_info.cpp
Check results for kernel.get_info() for different descriptors.
=> Add check results for kernel info queries

tests/math_builtin_api/modules/test_generator.py
Added template args `<decorated::yes>` and `<decorated::no>` to `multi_ptr `in math_builtin_api tests to properly use `multi_ptr` according to [4.17.1. Description of the built-in types available for SYCL host and device](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_description_of_the_built_in_types_available_for_sycl_host_and_device):
> genfloatptr - All permutations of multi_ptr<DataT, AddressSpace, IsDecorated> where DataT is all types within genfloat, AddressSpace is access::address_space::global_space, access::address_space::local_space and access::address_space::private_space and IsDecorated is access::decorated::yes and access::decorated::no.
=> Add template args<decorated::yes> and <decorated::no> to multi_ptr in math_builtin_api tests

tests/image/default_image.h, tests/image_accessor/generic_image_accessor_semantics.cpp, tests/image_accessor/host_image_accessor_semantics.cpp
This commit fixes some mistakes in the image tests.
=> Fix image accessor tests

tests/accessor/accessor_common.h, tests/accessor/generic_accessor_api_common.h, tests/accessor/generic_accessor_api_core.cpp, tests/accessor/generic_accessor_api_fp16.cpp, tests/accessor/generic_accessor_api_fp64.cpp, tests/accessor/local_accessor_api_common.h, tests/accessor/local_accessor_api_core.cpp, tests/accessor/local_accessor_api_fp16.cpp, tests/accessor/local_accessor_api_fp64.cpp
Add checks for accessor with const T and refactor checks for zero-dim accessor.
Update links to product bug issues.
=> Fix bugs in local accessor api tests

test_plans/atomic_ref.asciidoc
Update atomic_ref test plan according to comment https://github.com/KhronosGroup/SYCL-CTS/pull/590#discussion_r1194331314
=> Update atomic_ref test plan

tests/accessor/accessor_common.h
To make sure that placeholder accessor usage in kernel is not optimized out.
=> Fix placeholder accessor tests

.github/workflows/cts_ci.yml
This addresses deprecation warnings and avoid CI to break when deprecated APIs support is dropped.
=> [CI] Update GitHub Actions workflow script

tests/common/semantics_by_value.h, tests/range/range_constructors.cpp
Add checks in kernel for range and refactor common code in common/semantics_by_value.h.
=> Cover gap for range by-value semantic

tests/atomic_ref_stress/atomic_ref_stress_common.h
Add checking with possible error range for floating point type as per test plan.
Limit size for range to prevent possible overflow in calculations.
=> Fix atomic_ref stress tests

tests/kernel/kernel_attributes.h, tests/kernel/kernel_attributes_vec_hint.cpp, tests/kernel/kernel_attributes_wg_hint.cpp
Created tests for kernel attributes according to [test plan](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/kernel_attributes.asciidoc)
=> Kernel attributes tests implementation

test_plans/intel_device_info.asciidoc
Created test plan for [extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_device_info.md)
=> Test plan for Intel's Extensions for Device Information

tests/accessor/host_accessor_api_common.h
Removed check write correctness for host_accessor with read mode.
=> Fix check for read only host_accessor

tests/invoke/execution_and_memory_models.cpp
Added tests for SYCL execution and memory model according to [test plan](https://github.com/KhronosGroup/SYCL-CTS/pull/632)
=> Execution and memory model tests

tests/nd_range/nd_range_constructors.cpp, tests/nd_range/nd_range_equality.cpp
Added checks for copy and move constructors, added tests in kernel function and refactored.
=> Cover nd_range semantic by-value gaps

CMakeLists.txt, tests/extension/oneapi_enqueue_barrier/CMakeLists.txt, tests/extension/oneapi_enqueue_barrier/enqueue_barrier.cpp
Added tests according the to test plan [enqueue_barrier.asciidoc](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/enqueue_barrier.asciidoc).
=> Tests for enqueue barrier extension

tests/accessor/accessor_implicit_conversions_core.cpp, tests/accessor/accessor_implicit_conversions_fp16.cpp, tests/accessor/accessor_implicit_conversions_fp64.cpp
No functional changes in this pull request.
=> Update the macro for the implementation check

tests/sub_group/sub_group_semantics.cpp
Passing sub_group instances captured from outside is UB.
=> Fix sub_group test

test_plans/root_group.asciidoc
Create test plan for extension [sycl_ext_oneapi_root_group](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_root_group.asciidoc).
=> Create test plan for root_group extension

tests/extension/oneapi_root_group/CMakeLists.txt, tests/extension/oneapi_root_group/root_group.cpp
Implement the tests from the test plan in https://github.com/KhronosGroup/SYCL-CTS/pull/573.
=> Implement tests for root_group extension

tests/group_functions/group_scan.h
Local linear ID should be group_id * local_range + local_id
=> Compute group local linear id correctly

tests/vector_load_store/generate_vector_load_store.py
This commit expands the testing of vec load and store with:
* Test cases for multi_ptr with local and private address space.
* Test cases for raw pointers with global, local and private address space. This functionality was added in https://github.com/KhronosGroup/SYCL-Docs/pull/555.
=> Expand testing of vec load and store

tests/extension/khr_queue_empty_query/CMakeLists.txt
=> [KHR_QUEUE_EMPTY] fix cmakelist

tests/spec_constants/spec_constants_via_kernel_bundle.h
Currently `bundle_factory` in `spec_constants_via_kernel_bundle` tests creates `kernel_bundle` without specifying kernel_id for some scenarios when it doesn't matter which bundle to use. That leads to the situation that all device images from executable are used which might be a lot if all tests are compiled into a single executable.
I.e., before change
`./bin/test_spec_constants  "*via_kernel_bundle_core"`
has been causing compilation of all kernels from the executable (including the ones completely  unrelated to kernel_bundle/spec_constants) which is unnecessary.
So, this change fixes bundle_factory to use specific kernel id.
=> Fix `bundle_factory` to avoid compiling unnecessary kernels
